### ISSUE TITLE
kubeadm: node name is always IPv4 address

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#1052]
Even when specifying a hostname in the userdata and creating an IPv6-only kubernetes system, kubeadm names the node by its IPv4 address.

Expected would be that if a hostname is declared in the userdata, kubeadm would be instructed to name the joining node by that name.

**Comment by bradbeam** [comment]
Assuming it's a bug introduced in https://github.com/talos-systems/talos/pull/1017. Will look tomorrow.

**Comment by Ulexus** [comment]
Ah, I didn't realize it was a brand new option.  It just hasn't been hooked into the kubeadm run, then.
