### ISSUE TITLE
`osctl validate` needs some love

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#1140]
Right now, `osctl validate` doesn't do anything but attempt to read in data and fit it to the struct, then spit out the Go data.  This is completely uninformative and pretty unhelpful.

At a minimum, it should re-format the yaml so that the user can verify the data was interpreted successfully.

Also, it doesn't have support for v1 userdata.

**Comment by andrewrynhard** [comment]
@Ulexus Take a look again. I have updated this code to have a legit validation step. The implementation of validation for `v1alpha1` could be more robust, but we at least have the ability to validate using `osctl validate` against any support config version.

**Comment by andrewrynhard** [comment]
@Ulexus Gonna close as I think the new validate stuff works as you would expect.
