### ISSUE TITLE
osctl context flag

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#1171]
We should support one off context changes 

```
osctl ps --context=cluster-a
```

**Comment by sekerin** [comment]
Hello, can i take it?  And can you tell me more about this issue?

**Comment by andrewrynhard** [comment]
@sekerin Yes please. A context here is this:

```
$ cat ~/.talos/config
context: my-cluster
contexts:
  my-cluster:
    target: 127.0.0.1
    ca: ...
```

You can have multiple contexts:

```
$ cat ~/.talos/config
context: my-cluster-2
contexts:
  my-cluster-1:
    target: 127.0.0.1
    ca: ...
  my-cluster-2:
    target: 192.168.1.100
    ca: ...
```

This issue is to allow a oneoff run against any context instead of what is used in the `talosconfig`. The file shouldn't be modified, but `osctl` should use the `--context` specified instead of the `context:` specified in the `talosconfig`.
