### ISSUE TITLE
`osctl kubeconfig`: name context as cluster-name

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#1172]
It would be nice if the name of the talos cluster would be automatically used by the osctl-generated kubeconfig, so that the kubectl context name is predictable and human-friendly.

**Comment by smira** [comment]
`az aks get-credentials` does exactly that in a very clean and friendly way

**Comment by Ulexus** [comment]
Of note:  presently, the kubeconfig context has _no_ name at all, and the generated names for the credentials and endpoints are static, guaranteeing conflict in the case of multiple talos clusters.

**Comment by Ulexus** [comment]
Ah, yes (regarding the Azure CLI):  a simple `--name` option to `osctl kubeconfig` would go a long way.  Then just deterministically-generated credential and cluster names, and we should be fine.

**Comment by Ulexus** [comment]
Deterministically-generated... perhaps a hash of the endpoint(s)?

**Comment by rsmitty** [comment]
Closed via talos-systems/talos#1801 and https://github.com/talos-systems/bootkube/pull/8
