### ISSUE TITLE
Publish version info on a release

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#1190]
We should publish version notes for:

- kubernetes
- containerd
- linux

for a given Talos release.

**Comment by particledecay** [comment]
This would be super useful. When using ansible to provision new clusters or download compatible `kubectl` binaries, I'd like to know what version of k8s to target for a given version of Talos.

If this existed in a consistent format in the GH release notes, I can at least scrape that info using something like https://github.com/particledecay/ansible-scrape :)
