### ISSUE TITLE
Digital Ocean Support

### ISSUE THREAD

**Issue by kloudtrader-github** [talos-systems/talos#1206]
Hey! Brilliant project. Really like the work it does for the security end. Going through the docs, we saw AWS, GCP and bare metal. We were wondering if there's support coming up for Digital Ocean. We are an avid users of Digital Ocean and would really like use this with it. Thanks!

**Comment by andrewrynhard** [comment]
We are big fans of DO as well! The v0.2 version of Talos had a technical limitation that prevents us from adding support for DO. In that version of Talos, static IPs are required but DO does not support floating IPs for custom VMs. However, we are changing the design in v0.3 and we plan on landing support for DO in that release. I would be happy to keep you updated and maybe you guys could test it out for us.

**Comment by kloudtrader-github** [comment]
Awesome. Looking forward to the experience!

**Comment by Ulexus** [comment]
@andrewrynhard This isn't _totally_ true:  you _can_ bind a floating IP to a droplet via API... so a platform implementation for DO _could_ do this, if we had a valid API key and the ID of the floating IP.  That's way more complicated than anything presently in the platform implementations, but it _is_ possible.

**Comment by Ulexus** [comment]
Oh, actually, you can retrieve the ID of a float IP by IP address, too.  So you actually only need the API key.

**Comment by Ulexus** [comment]
I still misread the API docs (there isn't a separate ID for a floating IP).  All you need it [this](https://developers.digitalocean.com/documentation/v2/#assign-a-floating-ip-to-a-droplet).

**Comment by andrewrynhard** [comment]
@Ulexus interesting. 🤔 . So far we haven't required any cloud credentials, and I'm hesitant to do so. That being said, DO would be awesome to land support for.

I think you are aware of this, but we are planning on having workers discover the trustd endpoints via Kubernetes _after_ Kubernetes is up. If we can manage that, then it removes the whole floating IP requirement.

**Comment by Ulexus** [comment]
Right, and that is a more general solution.  I'll bet we _will_ need cloud-provider-specific platform implementations down the road, but this should be a non-issue in the near term.

**Comment by andrewrynhard** [comment]
> I'll bet we will need cloud-provider-specific platform implementations down the road, but this should be a non-issue in the near term.

Potentially yeah.

**Comment by andrewrynhard** [comment]
@kloudtrader-github We will be landing DO support shortly: #1352

**Comment by Immortalin** [comment]
@andrewrynhard hi, just wanted to let you know that DO now supports KVM nested virtualization. This opens the path for stuff like kata containers which would help further lock down things.

**Comment by andrewrynhard** [comment]
> @andrewrynhard just wanted to let you know that DO now supports KVM nested virtualization. This opens the path for stuff like kata containers which would help further lock down things.

Oh nice. We landed KVM support on our kernel but the last thing we need is the ability to flex on what to use for the CRI. Right now we only support containerd. I will open an issue we can use to track implementing multiple CRIs.
