### ISSUE TITLE
Improve error messages from osctl waiting for cluster startup

### ISSUE THREAD

**Issue by tgerla** [talos-systems/talos#1230]
If you try running `osctl kubeconfig` too soon after `osctl cluster create`, you will get an error message:

`error fetching kubeconfig: rpc error: code = Unknown desc = open /etc/kubernetes/admin.conf: no such file or directory`

This might be tricky for new users to figure out. It would be nice if this error were trapped and we spat out something helpful, like "Please wait, the cluster is still starting."

**Comment by sekerin** [comment]
Hello, can i take it?

**Comment by tgerla** [comment]
Hi @sekerin, please do! Let us know if you have any questions, and thanks!

**Comment by Ulexus** [comment]
Personally, I would like to see the details of the error (state) retained, but you are certainly correct that it needs to be indicated to the user that this is normal during bootstrapping.

I would suggest perhaps just wrapping the error with something like:

```go
errors.Wrap(err, "waiting for cluster to start; missing files are expected")
```

**Comment by Ulexus** [comment]
A more fancy version would be to print a log indicating the waiting and, if at the end of the timeout, there is still an error, print it then.

**Comment by andrewrynhard** [comment]
^ I like the wait with a timeout idea

**Comment by andrewrynhard** [comment]
@sekerin If your up for it, you could use the code we are going to merge in https://github.com/talos-systems/talos/pull/1239 to perform a retry with a timeout.
