### ISSUE TITLE
Low Entropy causes delayed/stuck boot

### ISSUE THREAD

**Issue by realdavidops** [talos-systems/talos#1240]
I'm attempting to use matchbox within VMWare ESXi to boot a talos k8s cluster. When I attempt to do this it seems the VM is stuck at attempting to run https://github.com/talos-systems/talos/blob/master/pkg/startup/rand.go#L16

![Screenshot from 2019-10-06 22-16-50](https://user-images.githubusercontent.com/10410822/66283065-a64ffe00-e887-11e9-8410-503df66b04b2.png)

Here is a snippet of my matchbox config for this host:

```
{
  "id": "talos",
  "name": "Talos Systems",
  "boot": {
    "kernel": "/assets/talos/0.2.0/vmlinuz",
    "initrd": [
      "/assets/talos/0.2.0/initramfs.xz"
    ],
    "args": [
      "talos.platform=metal",
      "talos.userdata=http://10.1.1.2:8080/assets/master-1.yaml"
    ]
  }
}
```
Logs from matchbox look as follows:
```

time="2019-10-07T03:15:43Z" level=info msg="HTTP GET /boot.ipxe",
time="2019-10-07T03:15:43Z" level=info msg="HTTP GET /ipxe?uuid=7c434d56-1a4d-1a0d-7629-6d8a3982b058&mac=00-0c-29-82-b0-58&domain=&hostname=&serial=VMware-56%204d%2043%207c%204d%201a%200d%201a-76%2029%206d%208a%2039%2082%20b0%2058",
time="2019-10-07T03:15:43Z" level=debug msg="Matched an iPXE config" labels="map[serial:VMware-56 4d 43 7c 4d 1a 0d 1a-76 29 6d 8a 39 82 b0 58 uuid:7c434d56-1a4d-1a0d-7629-6d8a3982b058 mac:00:0c:29:82:b0:58 domain: hostname:]" profile=talos,
time="2019-10-07T03:15:43Z" level=info msg="HTTP GET /assets/talos/0.2.0/vmlinuz",
time="2019-10-07T03:15:43Z" level=info msg="HTTP GET /assets/talos/0.2.0/initramfs.xz"
```

I'm gonna let the VM run overnight to see if it boots at all /shrug. I'm on slack if needed also.

**Comment by andrewrynhard** [comment]
@realdavidops try putting this in the kernel arts:

random.trust_cpu=on

**Comment by andrewrynhard** [comment]
We should document this.

**Comment by realdavidops** [comment]
It does seem this fixes the issue with entropy, but I will leave this open unless you have a master issue or PR for documentation.

**Comment by andrewrynhard** [comment]
https://askubuntu.com/questions/1070433/will-ubuntu-enable-random-trust-cpu-in-the-kernel-and-what-would-be-the-effect
