### ISSUE TITLE
regression: kernel commandline arguments from user-supplied config not longer being applied to baremetal bootloader

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#1244]
Regression as like #1102

**Comment by andrewrynhard** [comment]
Gah. Sorry about that. This is my fault when moving to the Configurator interface. We really need a way to test booting the full Talos stack. Containers have their limitations in our tests.

**Comment by andrewrynhard** [comment]
No I think that is exactly what we plan on doing. We have a PR pending to enable KVM, but need to wait for the new `bldr` stuff to merge before we can support multiple versions of Talos. That should be merged today or tomorrow.

**Comment by Ulexus** [comment]
This doesn't actually describe the regression.  The real problem is a problem detecting the baremetal platform resulting in the loss of configuration data.
