### ISSUE TITLE
baremetal installs with `bootloader:false` do not work

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#1257]
It appears that the boot process gets very confused after the installation is done with bootloader=false.  Something in the boot process gets confused, thinking talos is actually installed on the system, and it tries to resize the disk.  When it does so, it comes up with a truncated device name (the following should be `/dev/nvme1n1`), for some reason.

```
[   12.670725] [talos] WARNING: no ESP partition was found
[   12.676612] [talos] [phase]: platform tasks error running task: resize: error opening block device "nvme1n": open /dev/nvme1n: no such file or directory
[   12.691313] [talos] [phase]: platform tasks done, 102.544676ms
panic: boot failed: error running phase "platform tasks": 1 error occurred:
        * resize: error opening block device "nvme1n": open /dev/nvme1n: no such file or directory
```

Setting bootloader=yes during install, regardless of whether you actually boot off the local disk, prevents the issue.

**Comment by andrewrynhard** [comment]
Thanks for the bug report. I know we started chatting about the appropriate way to handle the case of pure PXE nodes. Thinking we should go ahead and get that going. It shouldn't be _too_ hard.

**Comment by Ulexus** [comment]
I wouldn't treat it as a high priority.  There's plenty already on the table for 0.3.  I just wanted to get this down, as it is a regression.

**Comment by Ulexus** [comment]
The general boot process and check of what constitutes an "installed" system, though, has been an issue for a while.

**Comment by andrewrynhard** [comment]
> The general boot process and check of what constitutes an "installed" system, though, has been an issue for a while.

Agree. Its worth at least cleaning this up a bit.

**Comment by andrewrynhard** [comment]
Just to verify, the disk name is good if the `bootloader==true`?

**Comment by Ulexus** [comment]
Bizarre as it is, yes.  The disk name is perfectly fine (and I assume the filesystem is successfully resized) if `bootloader=true`.

**Comment by Ulexus** [comment]
I suppose the only thing I can say for certain is that I do not get the error from the resize, and that the system generally seems to work just fine.
