### ISSUE TITLE
reboot of init node causes etcd to fail

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#1279]
After the etcd cluster is formed, if the master-1 (init) node is rebooted, etcd will fail to start:

```
[   39.199973] [talos] service[etcd](Waiting): Error running Containerd(etcd), going to restart forever: task "etcd" failed: exit code 2
```

It is possible (likely?) that this is not unique to the init node, but I have not yet had the opportunity to try.

According to etcd issue [10372 commentary](https://github.com/etcd-io/etcd/issues/10372#issuecomment-451713487), this may be a permission problem.

**Comment by andrewrynhard** [comment]
Closed by talos-systems/talos#1392.
