### ISSUE TITLE
upgrading init node causes etcd bifurcation

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#1280]
Since on upgrade, the disk is wiped, etcd on the init node thinks that it is a new install and creates a new cluster.  This ends up with master-2 and master-3 being in the "old" cluster and master-1 being in a new cluster.

We will need some way to set a persistent checkpoint flag which signals that master-1 has, at one time, formed a cluster, thus indicating that without manual user intervention, it should not form a new one.

@andrewrynhard indicated one option here is to set a flag file on the boot partition.

**Comment by andrewrynhard** [comment]
This was fixed in a number of different PRs so no ticket to point to.
