### ISSUE TITLE
Example scripts based on the getting started guides

### ISSUE THREAD

**Issue by tgerla** [talos-systems/talos#1337]
It would be really nice if we had some example shell scripts or Ansible playbooks to automate, in a simple way, the steps necessary to run Talos on a public cloud. For instance, the AWS guide here: https://github.com/talos-systems/talos/pull/1329 could be implemented as a shell script or a playbook with some basic configurable options.

The goal would be to simplify setup and evaluation of Talos on those platforms, and to serve as a starting point for users' more advanced infrastructure automation.

**Comment by andrewrynhard** [comment]
I think this would be great to have in a `contrib` directory.

**Comment by andrewrynhard** [comment]
https://github.com/Timoses/virtual-playground
