### ISSUE TITLE
Fix goroutine log output

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#1364]
For an unknown reason, goroutine based services do not log to the log file.

**Comment by smira** [comment]
Do you have an example of that? 

One thing is that goroutine based services should use the log writer provided to the `main` function as there's no way to automatically intercept default `log.` calls.

**Comment by smira** [comment]
ah, if that is about `bootkube`, I know what's wrong, I can patch it to make logs go right direction

**Comment by andrewrynhard** [comment]
Yep sorry. That was what I was talking about. But to your point about there custom logger, bootkube does does its own printing. Not sure how to fix that.

**Comment by smira** [comment]
I think I can make a patch to bootkube to allow to override stdout/stderr destinations, if that's okay for us (as we would probably diverge more with upstream version)

**Comment by andrewrynhard** [comment]
> I think I can make a patch to bootkube to allow to override stdout/stderr destinations, if that's okay for us (as we would probably diverge more with upstream version)

yeah that was the plan ... but we were waiting until bootkube is official moved over to @kubernetes-sigs
