### ISSUE TITLE
osctl config generate should append `https` prefix on loadbalancer/endpoint address

### ISSUE THREAD

**Issue by bradbeam** [talos-systems/talos#1372]
May also want to look into throwing a non-fatal warning if no port is specified.

**Comment by Ulexus** [comment]
n.b. : prepend

This just bit me.

**Comment by Ulexus** [comment]
A note on URL parsing: https://play.golang.org/p/F-RnAcvkAq0

**Comment by Ulexus** [comment]
There seems to be a reasonable question here of whether the default should be https/443 or https/6443.

It might be best to just validate the input, requiring a fully-qualified URL (and print a user-understandable note if it isn't valid) rather than trying to "correct" it silently.

**Comment by andrewrynhard** [comment]
> There seems to be a reasonable question here of whether the default should be https/443 or https/6443.
> 
> It might be best to just validate the input, requiring a fully-qualified URL (and print a user-understandable note if it isn't valid) rather than trying to "correct" it silently.

Agree. The URL parsing breaks down if there is no scheme. I'm leaning towards the validation idea, just so users get more explicit when using Talos in the future.
