### ISSUE TITLE
Target flag is broken for logs

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#1397]
Something like `osctl logs -t $IP ntpd` does not get the logs from $IP, but from the node that is in the talosconfig.

**Comment by bradbeam** [comment]
We only have support for non-streaming endpoints atm

**Comment by andrewrynhard** [comment]
> We only have support for non-streaming endpoints atm

The `--target` flag should still work for every API IMO. I think we can just gate streaming APIs with a check on the value of `target` and enforce that it be a single IP.
