### ISSUE TITLE
Clean up osctl kubeconfig client code

### ISSUE THREAD

**Issue by bradbeam** [talos-systems/talos#1450]
I think there's some duplication around `Kubeconfig`, `KubeconfigRaw`, `readStream`, and `extractTarGz`. We should hopefully be able to drop `KubeconfigRaw` and just make use of `readStream` (think this is done already) and `extractTarGz` ( in `cmd/osctl/cmd/kubeconfig` ).

**Comment by smira** [comment]
I feel `extractTarGz` is a bit scary for `kubeconfig`, as it might potentially overwrite any file in the working directory (if Talos goes wrong and sends more files or different files than it should).

And what we should actually be doing in `osctl kubeconfig` is merging the kubeconfig into user's `~/.kube/config` as a new context (or updating existing context), that is much better experience overall than doing `kubectl --kubeconfig=kubeconfig`

**Comment by andrewrynhard** [comment]
@smira Can we close this with some of the recent CLI work?

**Comment by smira** [comment]
yep, looks like it's all done as described by Brad in the description
