### ISSUE TITLE
Support DNS in Talos API path

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#1512]
Everything from `osctl` to `apid` should be able to use DNS names.

**Comment by Ulexus** [comment]
Ex:
$ osctl -t sn0.cluster1.mydomain.com read /proc/partitions
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for sn0, not sn0.cluster1.mydomain.com"

**Comment by andrewrynhard** [comment]
@Ulexus Ahh yep. Thanks, that will help. Are you able to confirm that the domain name is set properly?

`osctl read /proc/sys/kernel/domainname`

**Comment by Ulexus** [comment]
I can confirm it is _not_ set correctly:

```
$ osctl read /proc/sys/kernel/domainname
(none)
```

**Comment by Ulexus** [comment]
Nope; I lied.  It is _not_ in the machine.network config... oops. Let me recheck everything.

**Comment by Ulexus** [comment]
No, I didn't lie.  I just checked the wrong machine.

```
$ yq r sn0.yaml machine.network.domainname
cluster1.mydomain.com
```

```
$ osctl -t 172.16.199.100 read /proc/sys/kernel/domainname
(none)
```

**Comment by andrewrynhard** [comment]
Hmm I don't see `domainname` as a valid option in the go struct. @bradbeam What is the way to get the domain name set? Do we need to set `hostname` to the FQDN and then Talos does magic to set `domainname`?

**Comment by Ulexus** [comment]
Ah... perhaps we lost it.  I'm reasonably certain it _used_ to be there.

**Comment by bradbeam** [comment]
yeah, set hostname to FQDN. 

https://github.com/talos-systems/talos/blob/master/internal/app/networkd/pkg/networkd/networkd.go#L342-L368

should split the config.network.hostname field by `.`. the parts[0] = short name and parts[1:] = domain

**Comment by Ulexus** [comment]
Oops. I failed to notice that.  Thanks, I will retest... perhaps I shouldn't have piggy-backed this issue.

**Comment by Ulexus** [comment]
Okay, confirmed that with the correct config, `/proc/sys/kernel/domainname` is set correctly, but that `osctl -t <fqdn>` still fails because the cert is not generated to respond for the FQDN.

**Comment by andrewrynhard** [comment]
Thanks. I'm thinking that we could automatically set certSANs based on `hostname` + `domainname`, as a good first pass at solving this?

**Comment by Ulexus** [comment]
Good first pass, yes.  I would still like to see the control plane nodes _also_ include additional SANs eventually, but including FQDN would be a good step.

**Comment by Ulexus** [comment]
Aside from a concern for topological separation, it would be sufficient to me to just include those same SANs from cluster.apiServer.certSANs.

**Comment by andrewrynhard** [comment]
> Aside from a concern for topological separation, it would be sufficient to me to just include those same SANs from cluster.apiServer.certSANs.

Yeah the strange part here is that we have a clear separation logically between K8s configuration and Talos configuration. So figuring that out will be interesting.

**Comment by Ulexus** [comment]
That separation really _should_ exist.  I think that's a good thing.  I think we just need to be add a similar thing for the talos side.

There used to be a separation between the _talos_ cluster and the _kubernetes_ cluster.  That been basically removed with the current config template.

We could, however, add back a `cluster.talos` section for this.  I would still have preferred a categorical separation between cluster[kubernetes] and cluster[talos], but I can live with a talos subsection on cluster.

**Comment by Ulexus** [comment]
Well... that doesn't really work.  There is not a separation even between `cluster` and `machine`.  That is, there are kubernetes components in `machine`... mainly, this is kubelet, which really is machine-oriented.

In any case, that makes `cluster.talos` not really particularly useful name.   Worse, there is already `machine.certSANs`, which would be an equally valid option, but it is for the kubelet.  Maybe _those_ could cross over, though, since they really _are_ the same, looking strictly from the connotation of its config tree name and placement.

**Comment by andrewrynhard** [comment]
Looks like we have a field for this: https://github.com/talos-systems/talos/blob/master/pkg/config/types/v1alpha1/v1alpha1_types.go#L80. Just needs to be implemented.

**Comment by Ulexus** [comment]
That's what I was talking about above.  The comment on it says it's for the kubelet.

**Comment by andrewrynhard** [comment]
I think it just may be confusing, because that is what I thought at first too: https://github.com/talos-systems/talos/blob/master/pkg/config/types/v1alpha1/v1alpha1_types.go#L71-L80

**Comment by Ulexus** [comment]
:man_facepalming:
