### ISSUE TITLE
Control plane components extraArgs are non-functional

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#1523]
Setting `cluster.controllerManager.extraArgs` results in those args not being added to the final `deploy/kube-controller-manager` manifest.

This is also true for `cluster.apiServer.extraArgs`.

**Comment by Ulexus** [comment]
This is a bit of a quandary, though, since this may be more of a bootkube thing... so this may need to wait until the bootkube manifest customization mechanism is more formalized.

**Comment by andrewrynhard** [comment]
Yeah this is something we will need in bootkube first :(

**Comment by andrewrynhard** [comment]
Research:
- What changes will be needed in bootkube
- Create an issue in upstream bootkube to discuss the implementation
