### ISSUE TITLE
http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by sridher** [talos-systems/talos#1524]
I created cluster by fallowing [https://www.talos.dev/docs/v0.3/#Getting%20Started](https://www.talos.dev/docs/v0.3/#Getting%20Started ) when i deploy app containing local registry
giving error
`kubelet, worker-1  Failed to pull image "192.168.1.100:32000/core:0.2.19": rpc error: code = Unknown desc = failed to pull and unpack image "192.168.1.100:32000/core:0.2.19": failed to resolve reference "192.168.1.100:32000/core:0.2.19": failed to do request: Head https://192.168.1.100:32000/v2/core/manifests/0.2.19: http: server gave HTTP response to HTTPS client`
my docker damon `/etc/docker/daemon.json `
has 
`"insecure-registries" : ["localhost:32000",  "192.168.1.100:32000"]`

its working fine in local machine to push and pull by same address ie. `192.168.1.100:32000`

_it is working fine in microk8s cluster after changing_ 

```
cat /var/snap/microk8s/current/args/containerd-template.toml | grep 192.
	[plugins.cri.registry.mirrors."192.168.1.100:32000"]
          endpoint = ["http://192.168.1.100:32000"]
```

How to fix this in talos ?

**Comment by andrewrynhard** [comment]
@sridher Thanks for reporting this. At the moment we don't have an easy solution for this, but I don't think it would be too difficult to fix this. I'll chat with the team on how we might fix this and I will keep you updated!

**Comment by andrewrynhard** [comment]
See #1718.

**Comment by andrewrynhard** [comment]
@smira Did your work in v0.4 for mirrors fix this?

**Comment by smira** [comment]
yep, `registries:` in https://www.talos.dev/docs/v0.4/#v0.4/en/configuration/v1alpha1
