### ISSUE TITLE
vSphere install docs issue

### ISSUE THREAD

**Issue by hickwillie** [talos-systems/talos#1572]
Not sure where to put this, so I will put it here.

Documentation at https://www.talos.dev/docs/v0.3/#VMware needs to be updated for the vSphere install:

`curl -LO https://github.com/talos-systems/talos/releases/download/v0.3.0-alpha.2/talos.ova`
- now alpha.10?  This statement gets a github 404.

`govc import.ova -name talos-v0.3.0-alpha.2 $talos/build/talos.ova`
- Shouldn't this be `govc import.ova -name talos-v0.3.0-alpha.2 talos.ova`

And the ova is currently `vmx-13`, does it need to be or can it be a lower version (more compatibility) ?

**Comment by rsmitty** [comment]
@hickwillie Thanks for the feedback on this! I think you're definitely right about the first two questions. I'll fix those in docs straight away. 

On the last one, I'm not super sure if that hardware version is specifically required or it's just what we picked as a starting point. Is there a version that would be better to use? 

/cc @bradbeam for some context around that last bit.

**Comment by bradbeam** [comment]
The hardware version is from the platform we were doing our initial testing against. From a talos perspective, I think it can be lowered safely, but if you're looking at using the [vsphere/vmware cloud provider](https://cloud-provider-vsphere.sigs.k8s.io/tutorials/kubernetes-on-vsphere-with-kubeadm.html), they actually recommend increasing the hardware version to 15:

```
Upgrade Virtual Machine Hardware

VM Hardware should be at version 15 or higher.

# govc vm.upgrade -version=15 -vm '/datacenter/vm/k8s-node1'
# govc vm.upgrade -version=15 -vm '/datacenter/vm/k8s-node2'
# govc vm.upgrade -version=15 -vm '/datacenter/vm/k8s-node3'
# govc vm.upgrade -version=15 -vm '/datacenter/vm/k8s-node4'
# govc vm.upgrade -version=15 -vm '/datacenter/vm/k8s-master'
Check the VM Hardware version after running the above command:

# govc vm.option.info '/datacenter/vm/k8s-node1' | grep HwVersion
HwVersion:           15
```

**Comment by rsmitty** [comment]
@hickwillie I'm going to close this since I've updated the vmware instructions. Thx again for the feedback. If you have issues with the hw version create a new issue or pop into our slack and we'll be happy to help you troubleshoot.
