### ISSUE TITLE
Fail fast on upgrade if image is unavailable

### ISSUE THREAD

**Issue by bradbeam** [talos-systems/talos#1606]
Currently we get pretty far into an upgrade before we attempt to pull the upgrade container. With the need to specify the image with `docker.io` or 'registry', this can inadvertently break a node. 
We should attempt to pull the image / verify the image prior to initiating the upgrade.

**Comment by rsmitty** [comment]
specifically, this ticket is for ensuring that the installer image exists. will throw a new ticket out around validating that the image that is pulled is actually a talos installer.
