### ISSUE TITLE
node plugins

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#1635]
There is a use case for the concept of things which must be executed on boot of a node.  A specific example is Rook's Ceph OSD implementation, which expects volume groups to have been activated by the host.

**Comment by andrewrynhard** [comment]
Very interesting idea.

**Comment by Ulexus** [comment]
Interesting idea yes, but I don't immediately see a good way of implementing it outside of the machine config, which is not very flexible over time

**Comment by Ulexus** [comment]
I suppose we could add an initContainers to the machine config and expose an API by which we could extend those on a node over time.

**Comment by andrewrynhard** [comment]
I'm thinking that _maybe_ this could be our "plugin" mechanism. Allows us to stay true to not having talos be a general purpose OS for long running processes, but also allows extensibility.

**Comment by Ulexus** [comment]
Sounds reasonable.

I'm trying to find ways to structure it better than simply having wide-open container specs, but maybe that's a bad idea.

**Comment by Ulexus** [comment]
See Google Doc "Plugins" for further discussion/details
