### ISSUE TITLE
[osctl] consider moving config to $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by jsimonetti** [talos-systems/talos#1676]
On many linux systems it is these days custom to place configuration files in `$XDG_CONFIG_HOME/<appname>` (For talos the default would become `~/.config/talos/`)

Consider moving the osctl config file from `~/.talos/config` to `$XDG_CONFIG_HOME/talos/config`.

(The default value for `$XDG_CONFIG_HOME` is `$HOME/.config`)

Ref:
- https://wiki.archlinux.org/index.php/XDG_Base_Directory
- https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by andrewrynhard** [comment]
Since `osctl` can be used on a Mac as well, this wouldn't be consistent everywhere we expect `osctl` to be used. Thanks for the suggestion. If you _really_ wanted to do this you can set `TALOSCONFIG` env var to `$XDG_CONFIG_HOME/talos/config` in your `.bashrc` and `osctl` will use that path.
