### ISSUE TITLE
Publish list of images for given release

### ISSUE THREAD

**Issue by rsmitty** [talos-systems/talos#1737]
We should figure out how to make it clear for users that a given talos release expects a list of images to be present/pulled. Useful for airgapped installs so that users can keep up with the images and avoid pulling from the internet.

**Comment by jsimonetti** [comment]
With #1799 fixing the last technical hurdle, this issue becomes more important to track changes in the required/used images and to prevent having to do trial/error runs to see if the registry has all images.

**Comment by andrewrynhard** [comment]
I am adding a command to `talosctl` that lists the images.
