### ISSUE TITLE
Single node master upgrade fails

### ISSUE THREAD

**Issue by mzahorik** [talos-systems/talos#1768]
What occurs:

I installed a node with an "init" configuration.

I issued the command:

`osctl upgrade -i docker.io/andrewrynhard/installer:acpi -n 172.24.3.31`

To get the latest ACPI fixed by Andrew.  The output of dmesg:

`172.24.3.31: user: warning: [2020-01-13T00:01:55.481220792Z]: [talos] [phase]: cordon and drain node`
`172.24.3.31: user: warning: [2020-01-13T00:01:55.538204792Z]: [talos] skipping DaemonSet pod kube-proxy-gcc76`
`172.24.3.31: user: warning: [2020-01-13T00:01:55.540434792Z]: [talos] skipping DaemonSet pod calico-node-h2kvx`
`172.24.3.31: user: warning: [2020-01-13T00:01:55.543688792Z]: [talos] skipping DaemonSet pod kube-apiserver-fnq84`
`172.24.3.31: user: warning: [2020-01-13T00:01:55.546667792Z]: [talos] skipping DaemonSet pod pod-checkpointer-vpgnl`
`172.24.3.31: user: warning: [2020-01-13T00:01:58.677078792Z]: [talos] leaving etcd cluster`
`172.24.3.31: user: warning: [2020-01-13T00:01:58.681622792Z]: [talos] [phase]: cordon and drain node error running task: etcdserver: re-configuration failed due to not enough started members`

It doesn't reboot.  When an `osctl reboot` is issued, dmesg logs a message but fails:

`172.24.3.31: user: warning: [2020-01-13T00:12:35.111990792Z]: [talos] reboot via API received`

What I expected:

The upgrade to succeed.

Details about my environment:

v0.3.0-beta.3 PXE booted to a laptop
haproxy load balancer in front of the API server
calico manifests for a custom CNI

**Comment by andrewrynhard** [comment]
Thanks @mzahorik. How many control plane nodes are you running? Can you run:

```
osctl -n $ip1,$ip2,$ip3 services etcd
```

**Comment by mzahorik** [comment]
This was a single node control plane.  It's a different set of failures for multiple control nodes; I was going to file a different issue for that, but have to reset things to grab those logs.

**Comment by mzahorik** [comment]
`osctl -n 172.24.3.31 service etcd
NODE     172.24.3.31
ID       etcd
STATE    Running
HEALTH   OK
EVENTS   [Running]: Health check successful (6m5s ago)
         [Running]: Started task etcd (PID 2867) for container etcd (6m7s ago)
         [Preparing]: Creating service runner (6m7s ago)
         [Preparing]: Running pre state (6m18s ago)
         [Waiting]: Waiting for service "containerd" to be "up" (6m19s ago)`

**Comment by andrewrynhard** [comment]
> This was a single node control plane.
I should have looked at the issue title :D

**Comment by andrewrynhard** [comment]
See #1770.

**Comment by andrewrynhard** [comment]
We have support for this in v0.4. `talosctl upgrade --preserve=true`.
