### ISSUE TITLE
[osctl] cluster create firecracker should check for prerequisites

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#1781]
Add pre-flight checks for CNI modules required, /dev/kvm accessibility, etc.

This should make it easier for first-time users to successfully complete `osctl cluster create --provisioner=firecracker`

**Comment by andrewrynhard** [comment]
Looks like `CONFIG_BRIDGE_VLAN_FILTERING` is required in the kernel.

**Comment by andrewrynhard** [comment]
iptables is required

**Comment by andrewrynhard** [comment]
initramfs.xz, and vmlinuz are required

**Comment by smira** [comment]
> Looks like `CONFIG_BRIDGE_VLAN_FILTERING` is required in the kernel.

looks like this got fixed upstream: https://github.com/containernetworking/plugins/commit/cc6154603e4fe0cfdeb1c1e046de259b73559235

**Comment by smira** [comment]
* `xz` for `bzImage` extraction
