### ISSUE TITLE
osctl config generate requires port 6443 to be specified

### ISSUE THREAD

**Issue by crodetsky** [talos-systems/talos#1784]
Documentation on talos.dev and documentation in osctl state that you must supply a "load balancer IP or DNS name" for when you run `osctl config generate` but does not specify that a port is required. If a port is not specified bootkube fails. This should probably be corrected by both having a default of 6443 and updating documentation to inform the user of what we're actually specifying and why.

**Comment by andrewrynhard** [comment]
Thanks @crodetsky . Good points. We will have that documented better soon.
