### ISSUE TITLE
etcd does not bind to IPv6 interface

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#1842]
etcd does not appear to be binding to the IPv6 address(es) of the node, listening only on IPv4.  This will be a problem for IPv6-only installations.

**Comment by Ulexus** [comment]
This is a bit more complicated than it may seem at first.  The IPv6 equivalent of `0.0.0.0` is `[::]`, which works as expected _except_ that `etcd` interprets this as a "specific" address which triggers the requirement of the `--advertise-client-urls` option.

That is not necessarily a problem; we could discover or specify that, but that would need to be done.

Moreover, `--listen-peer-urls` and `--listen-client-urls` are currently blacklisted from override _and_ statically declared as `0.0.0.0`, explicitly limiting them to IPv4.

**Comment by Talos-Hope** [comment]
Thank you for entering this issue and providing the additional detail.
