### ISSUE TITLE
ip=dhcp breaks networking

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#1869]
In the `buildKernelOptions` `func` we return an empty string for the interface name, but later in the setup we require a valid name.

https://github.com/talos-systems/talos/blob/cebd88f77c312c3886a023881f2aa6d89e0228b9/internal/app/networkd/pkg/networkd/netconf.go#L176-L180

https://github.com/talos-systems/talos/blob/2a449aea2ffb7234a28536d4a3105e8b22f93d38/internal/app/networkd/pkg/nic/nic.go#L67-L71

**Comment by Ulexus** [comment]
Yeah, we need to check the return from `buildKernelOptions` [here](https://github.com/talos-systems/talos/blob/master/internal/app/networkd/pkg/networkd/networkd.go#L66) and only add to the netconf map if we have a non-empty interface name.

**Comment by andrewrynhard** [comment]
👍 Yeah that should be a simple enough fix.
