### ISSUE TITLE
Allow specifying kubeconfig admin user certificate lifetime

### ISSUE THREAD

**Issue by salkin** [talos-systems/talos#1906]
When deploying clusters with external authentication methods like GitHub / oauth2 etc, the kubernetes admin user certificate should have a very short lifetime just enough to let the cluster bootstrap itself. 

Now one cannot enforce the usage of external centralized authentication as users may fetch the kubeconfig directly from the cluster.

**Comment by andrewrynhard** [comment]
Good idea. I’m not in front of a computer but I think this may be as simple as adding a flag to the generation command.
