### ISSUE TITLE
Research VLAN support for interfaces

### ISSUE THREAD

**Issue by rsmitty** [talos-systems/talos#1914]
We should allow users to create VLAN devices as links to their physical nics. A TL;DR on what we need to implement: https://wiki.archlinux.org/index.php/VLAN

**Comment by Ulexus** [comment]
Keep in mind, though, that VLANs can also be applied to aggregated (bonded) devices.  We don't yet support bridges, but they can _also_ handle vlan tagging (though with some pretty serious caveats).  In any case, it's best to not restrict this to "physical nics"; it can be applied to anything which handles ethernet frames.
