### ISSUE TITLE
Document upgrades

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#1932]

**Comment by alex1989hu** [comment]
Is it about how to upgrade k8s components on Talos cluster? I don't have a clue how to upgrade `kubelet`. Okay, I can do it with newer Talos image - if there is a newer one, but what should we do without a newer Talos image?

For the reaming part: there was a solution worked until `v.19.0` -  `hyperkube`. This is also not clear and need a clarification.

FYI:
```
## Update kube-apiserver
## Take a deep breath; fingers crossed ... pod-checkpointer
kubectl -n kube-system set image daemonset/kube-apiserver kube-apiserver=k8s.gcr.io/hyperkube:v1.18.8 --record
## Update kube-controller-manager
kubectl -n kube-system set image daemonset/kube-controller-manager kube-controller-manager=k8s.gcr.io/hyperkube:v1.18.8 --record
## Update kube-schedule
kubectl -n kube-system set image daemonset/kube-scheduler kube-scheduler=k8s.gcr.io/hyperkube:v1.18.8 --record
```

**Comment by andrewrynhard** [comment]
@alex1989hu hyperkube was deprecated upstream, so we the upgrade from 0.5 to 0.6 will be a little different. We will throw up a PR in the AM. This PR could be  reference for you in the mean time: https://github.com/talos-systems/bootkube-plugin/commit/78d7183391b6f80ea86c5396e9f416b3c59bef95. The kubelet image will change to `docker.io/autonomy/kubelet:ZZZ` where `ZZZ` is the version you want.

**Comment by andrewrynhard** [comment]
Expanding the scope of this ticket a bit to make the goal a more generic upgrade guide. We should have a place that outline how to upgrade Talos, Kubernetes, and any spell out any specific upgrade pitfalls.
