### ISSUE TITLE
Add support for common cloud-init setups

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#1935]
A lot of the existing tooling out there assumes cloud-init, but we don't actually use it. However, we should support reading the config from well known cloud-init setups (e.g. config-drive).

**Comment by hex2a** [comment]
as discussed on slack, e.g. Proxmox supports nocloud v1 and configdrive v2
https://cloudinit.readthedocs.io/en/latest/topics/datasources/configdrive.html#version-2

**Comment by andrewrynhard** [comment]
I wonder if this is worth implementing given that dynamic machine configuration is on the roadmap?
