### ISSUE TITLE
/etc/hosts can not be appended as before

### ISSUE THREAD

**Issue by alex1989hu** [talos-systems/talos#1948]
**SCENARIO**:
We wanted to append `/etc/hosts` to override DNS server given IP address before modifying the DNS entry on the DNS provider.

I know, it worked before: there was a bug where `/etc/resolv.conf` is filled by DHCP given nameservers, so we had to manually append host entries to `/etc/hosts`. It was always filled, even if static network configuration was set. *(That was the bug, see the fix below)*

My best guess `/etc/hosts` appending worked before 93218687ec1a2a3116911d66a45d200461b02b02 / ebc9ea44e5b22f768f5db207ecc4f346e22df3b9 - I think this solved that DHCP given nameserver is not appear in `/etc/resolv.conf`. But the side-effect is that you are not able to append it to anymore. Maybe other commit causes that, it is just an assumption.

**CURRENT STATUS:**
Appending `/etc/hosts` is not possible with `v0.4.0-alpha.6`.

**Comment by rsmitty** [comment]
@alex1989hu please give the new config option a try and make sure it works for you

**Comment by alex1989hu** [comment]
I have just checked it (replaced sensitive data to general one) with `v0.4.0-alpha.8-21-g314edf63`:
```bash
$ talosctl read /etc/hosts
127.0.0.1       localhost
192.168.1.1       master-1
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters



192.168.22.1 foo.bar
```

**Comment by rsmitty** [comment]
Glad this is working. Going to close this issue!
