### ISSUE TITLE
new ARP related healthcheck prevents worker node start

### ISSUE THREAD

**Issue by alex1989hu** [talos-systems/talos#1951]
**SCENARIO:**
If you configure static IP for Talos `worker`, then the new *healthcheck* - introduced in `v0.4` (e9113537f909cee7d96d49fc7d96934d69841dce) - prints `healthapi.HealthCheck_NOT_SERVING`. Thus, prevents the "boot" process. The experience is that from 10 installation 6 stuck.

**WORKAROUND:**
After some investigation we found a way how to overcome this. We must ping each worker node - it populates the **ARP** table somehow.

**IMPORTANT NOTE:**
Neither `init`, nor `control-plane` nodes are not affected.

**Comment by smira** [comment]
I wonder if it's related to etcd joining the cluster which populates the ARP table while trying to join other peers for control plane nodes.

**Comment by smira** [comment]
Should be fixed with #1978
