### ISSUE TITLE
arm64 build of osctl/talosctl

### ISSUE THREAD

**Issue by dave93cab** [talos-systems/talos#1958]
Hi,

Is it possible to get an ARM build of osctl/talosctl?

Thanks

**Comment by andrewrynhard** [comment]
@dave93cab Seems reasonable. Just to be clear, the client can be ARM no problem, but Talos itself does not have ARM support, yet.

**Comment by dave93cab** [comment]
Sure, use case here is I have my DHCP, load balancer etc on arm and would like to do the config from there. Thanks
