### ISSUE TITLE
possible to install to usb flash drive

### ISSUE THREAD

**Issue by dave93cab** [talos-systems/talos#1967]
I can see my USB disk detected in dmesg output as 

`new SuperSpeed Gen 1 USB device number 2 using xhci_hcd`

but I don't see the expected usb-storage, scsi device etc. messages and no message about e.g. /dev/sdb

Is there a kernel parameter I can pass to enable usb-storage?

**Comment by andrewrynhard** [comment]
Anything showing up with `talosctl ls -l /dev`?

**Comment by dave93cab** [comment]
I can install it to the HD and check. I have this array of small machines with one HD and want the whole disk to use with gluster

**Comment by dave93cab** [comment]
```
10.20.0.163: kern:    info: [2020-03-24T03:34:25.138216603Z]: usb 4-6: new SuperSpeed Gen 1 USB device number 5 using xhci_hcd
 SUBSYSTEM=usb
 DEVICE=+usb:4-6
10.20.0.163: kern:    info: [2020-03-24T03:34:46.806594603Z]: usb 4-6: USB disconnect, device number 5
 SUBSYSTEM=usb
 DEVICE=c189:388
```

no change to /dev and only sda1 and sda2 in /dev/disk/by-label etc

**Comment by dave93cab** [comment]
@andrewrynhard 

So I see the following lines in dmesg output:
```
usbcore: registered new interface driver usbfs
usbcore: registered new interface driver hub
usbcore: registered new device driver usb
usbcore: registered new interface driver usbhid
```
but i think the following would be expected for USB mass storage:
`usbcore: registered new interface driver usb-storage`

Any ideas?

I am using 0.4.0a7 btw

**Comment by andrewrynhard** [comment]
Hmm. Not off the top of my head. 🤔. Let me see if I can reproduce.

**Comment by dave93cab** [comment]
@andrewrynhard 
[https://github.com/talos-systems/pkgs/blob/f2a8e95fb14deac7e58e343dd5b194cdff833fc5/kernel/config-amd64#L3968](https://github.com/talos-systems/pkgs/blob/f2a8e95fb14deac7e58e343dd5b194cdff833fc5/kernel/config-amd64#L3968)

**Comment by andrewrynhard** [comment]
Oh wow. I thought we merged a PR for that a while back. What I get for assuming.

**Comment by rsmitty** [comment]
https://github.com/talos-systems/pkgs/pull/97/files is the PR we did for USB support. But I suppose that only handled USB net devices and not storage devices. I can get this enabled this morning.

**Comment by rsmitty** [comment]
@dave93cab I'll be cutting a new v0.4.0 alpha this afternoon. Please give that a shot and make sure it works for you. I was able to see a USB drive plugged into a Talos machine using the new kernel.

**Comment by dave93cab** [comment]
@rsmitty sure thing. I will attempt an install to USB and report back. Thank you!
