### ISSUE TITLE
bootkube wrapper should allow dual-stack

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#2055]
## Feature Request

Presently, while bootkube itself now supports multiple service and pod subnets, Talos' bootkube wrapper does not.

### Description

We need to update the talos-side bootkube wrapper to support dual-stack CIDRs.

**Comment by andrewrynhard** [comment]
Out of scope for this issue, but I wonder if we should actually define a config to our liking for our plugin, and then embed it in the Talos config. This way we could just leverage the plugin libraries.
