### ISSUE TITLE
ux: cluster create should add a waiting for apid step

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#2065]
## Feature Request

The user experience could be improved by adding a "waiting for apid" step before "waiting for etcd"

### Description

The current user experience may lead to users scratching their head because etcd should not be running on port 50000:

```
$ talosctl cluster create 
validating CIDR and reserving IPs
generating PKI and tokens
creating network talos-default
creating master nodes
creating worker nodes
waiting for etcd to be healthy: ...
waiting for etcd to be healthy: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: read tcp 127.0.0.1:48094->127.0.0.1:50000: read: connection reset by peer"
```

**Comment by smira** [comment]
`apid` won't come up iirc waiting for the certs, that's why `etcd` is the first check, but I guess we could wait for `apid` on init node or something close to that.

**Comment by smira** [comment]
I think with recent change for `--with-init-node false` (which should be the default one!), we can close this one, as it waits for apid

**Comment by andrewrynhard** [comment]
> I think with recent change for `--with-init-node false` (which should be the default one!), we can close this one, as it waits for apid

Agree. Since this will be the default (in v0.7 or even v0.6 if we really want to), I will close this.
