### ISSUE TITLE
[ux][minor] Installer should not print WARNING when ESP does not exist

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#2071]
## Feature Request

Because it is a normal, expected occurrence, the installer should not, ideally, throw a big, loud WARNING when it fails to find the ESP.

```
[   55.301032] [talos] pulling "registry.cycore.io/talos/installer:latest"
[   58.203979] 2020/04/29 12:30:00 WARNING: failed to find ESP: file does not exist
```

### Description

This is a trivial user-experience optimization.

**Comment by Ulexus** [comment]
The log does not appear to be coming from the standard Talos logger, so it may be difficult to intercept.

**Comment by andrewrynhard** [comment]
I think we can drop this warning now actually, since we conditionally run the `MountBootPartition` task based on whether or not an installation was detected. We didn't have that information before so the best we could do was try and not fail.
