### ISSUE TITLE
documentation "Edit this page" link is not working

### ISSUE THREAD

**Issue by zerodayz** [talos-systems/talos#2076]
### Description

Visit website: https://www.talos.dev/docs/v0.4/#v0.4/en/guides/getting-started/firecracker

Click on "Edit this page" you are forwarded to 404 link:
https://github.com/talos-systems/talos/edit/master/docs/website/content/v0.4/en/guides.md

The right link would be
https://github.com/talos-systems/talos/blob/master/docs/website/content/v0.4/en/guides/getting-started/firecracker.md

**Comment by tgerla** [comment]
Thanks, Robin! I will take a look at this one.

**Comment by tgerla** [comment]
Hey Robin, I think I've got a fix here with some other cleanups I'm doing in preparation for 0.5 docs. This preview site should have the fix: https://deploy-preview-2077--talos-dev.netlify.app/docs/v0.4/ -- I'll merge soon. Thanks!

**Comment by zerodayz** [comment]
Hi @tgerla much better! Good job.
