### ISSUE TITLE
proposal: `client.New`

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#2093]
## Feature Request

Presently, we have `client.NewClientContextAndCredentialsFromConfig` and `...FromParsedConfig`, but we have no way (inside `client`) to actually construct a `client.Client`.   Instead, this is done in `/cmd/talos/cmd/talosctl/cmd/talos/root.go:WithClient`.

Any objections to moving the important points of `WithClient` to `client.New()`?

### Description

Make client API easier to use.

Add `client.New()`.  Add `client.WithEndpoints()`.

**Comment by andrewrynhard** [comment]
I think this makes sense. The more we can push into public packages to make the client code more library friendly the better IMO.

**Comment by Ulexus** [comment]
Okay, I'll get started with a PR, then.  Thanks!
