### ISSUE TITLE
"talos cluster --nameserver $nameservers" is ignored by talos container

### ISSUE THREAD

**Issue by Nold360** [talos-systems/talos#2109]
### Description

Hi, first of: I love your project & i wanted to give talos a shot in my dev environment. Sadly I ran into a problem, setting the Nameservers. As it seems `talosctl` is parsing the IPs just fine, but the running talos containers do not use these nameservers.

This causes the problem that - since my firewall doesn't allow clear DNS into the internet - the `k8s.gcr.io/etcd:3.3.15-0` image can not be pulled. 

I tested it on two different machines, both running up2date Debian buster. Maybe it's what you mean by `(VM only)` in `--nameservers strings         list of nameservers to use (VM only) (default [8.8.8.8,1.1.1.1]) `. Anyways, this seems pretty bad for airgapped systems.

I've set the dns-servers in my docker daemon.json, too:
``` json
 # cat /etc/docker/daemon.json 
{
  "dns": ["192.168.1.111", "192.168.1.1"]
}
```

cmdline: `talosctl cluster create --wait --nameservers "192.168.1.111,192.168.1.1"`

"Proof":
```
 # docker cp ${master-id}:/etc/resolv.conf .
 # cat resolv.conf 
nameserver 1.1.1.1
nameserver 8.8.8.8
```
### Logs

From master / talosctl output:
``` 
failed to pull image "k8s.gcr.io/etcd:3.3.15-0": 6 error(s) occurred:
failed to pull image "k8s.gcr.io/etcd:3.3.15-0": failed to resolve reference "k8s.gcr.io/etcd:3.3.15-0": failed to do request: Head "https://k8s.gcr.io/v2/etcd/manifests/3.3.15-0": dial tcp: lookup k8s.gcr.io on 8.8.8.8:53: read udp 10.5.0.2:34080->8.8.8.8:53: i/o timeout
failed to pull image "k8s.gcr.io/etcd:3.3.15-0": failed to resolve reference "k8s.gcr.io/etcd:3.3.15-0": failed to do request: Head "https://k8s.gcr.io/v2/etcd/manifests/3.3.15-0": dial tcp: lookup k8s.gcr.io on 8.8.8.8:53: read udp 10.5.0.2:39899->8.8.8.8:53: read: connection refused
failed to pull image "k8s.gcr.io/etcd:3.3.15-0": failed to resolve reference "k8s.gcr.io/etcd:3.3.15-0": failed to do request: Head "https://k8s.gcr.io/v2/etcd/manifests/3.3.15-0": dial tcp: lookup k8s.gcr.io on 8.8.8.8:53: read udp 10.5.0.2:37123->8.8.8.8:53: read: connection refused
failed to pull image "k8s.gcr.io/etcd:3.3.15-0": failed to resolve reference "k8s.gcr.io/etcd:3.3.15-0": failed to do request: Head "https://k8s.gcr.io/v2/etcd/manifests/3.3.15-0": dial tcp: lookup k8s.gcr.io on 8.8.8.8:53: read udp 10.5.0.2:58186->8.8.8.8:53: i/o timeout
failed to pull image "k8s.gcr.io/etcd:3.3.15-0": failed to resolve reference "k8s.gcr.io/etcd:3.3.15-0": failed to do request: Head "https://k8s.gcr.io/v2/etcd/manifests/3.3.15-0": dial tcp: lookup k8s.gcr.io on 8.8.8.8:53: read udp 10.5.0.2:58074->8.8.8.8:53: i/o timeout
        timeout
context deadline exceeded
```

### Environment

- Talos version: 0.4.1 & 0.5.0-beta.0
- Kubernetes version: v1.17.0
- Platform: debian:buster / amd64

**Comment by rsmitty** [comment]
@Nold360 Thanks for the heads up on this. I'll poke at it and see if I can reproduce on my side!

**Comment by rsmitty** [comment]
Yep, I can see that as well, even on my Mac. Let me dig in and see if I can find where this is breaking down.

**Comment by rsmitty** [comment]
@Nold360 the master branch should have this fixed for you. Let me know if you find that it's not working for you in one way or another, but I was able to do this locally:

```bash
$ talosctl cluster create --nameservers 192.168.1.200
...
...
$ talosctl read /etc/resolv.conf
nameserver 192.168.1.200
```

**Comment by Nold360** [comment]
Wow, that's what i call fast response time! Works like a charm now. Thanks a lot & keep up the good work! :)

```
✔ ~/git/talos/_out [master|✔]
11:29 $ ./talosctl-linux-amd64 read /etc/resolv.conf
nameserver 192.168.1.111
nameserver 192.168.1.1
```
