### ISSUE TITLE
Device.CIDR should be Device.CIDRs

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#2118]
## Feature Request

Devices should be able to have any number of CIDRs bound; thus `runtime.Device.CIDR` should actually be `runtime.Device.CIDRs` and be a slice of strings.  Similarly, the machine config should accept multiple values for cidrs.

**Comment by andrewrynhard** [comment]
You think we need to add the cidrs field and deprecate the other?

**Comment by Ulexus** [comment]
Probably the same as we did for bootkube, yeah.

**Comment by Ulexus** [comment]
I don't think there's any particular urgency here; I just ran across it, and it surprised me that I hadn't noticed it before.

**Comment by andrewrynhard** [comment]
@Ulexus is this something you think we should do for 0.6?
