### ISSUE TITLE
docs: improve contributing/development documentation

### ISSUE THREAD

**Issue by Nold360** [talos-systems/talos#2119]
### Description

For me it's still pretty unclear how to setup a dev environment & run a local [docs] server. Some parts are documented in the `Makefile`, some in the `CONTRIBUTING.md`. 

But there is also a bug in `CONTRIBUTING.md`, line 48-49:

```bash                                                                                                                                                                                    
GO111MODULE=on go get              
make ci
```     
But `ci` is no valid target:
``` bash
$ GO111MODULE=on go get
$ make ci
make: *** No rule to make target 'ci'.  Stop.
```

As for the docs-part, AFAIK running `npm run dev` in `/docs/website` should start a local server. But I think it would be great to have a  Dockerfile for this.

**Comment by andrewrynhard** [comment]
Agree. We went all in on doing nearby everything else in Docker. IMHO `CONTRIBUTING.md` should be very high level. We should pull out the specifics. The `Makefile` can be self documenting and the `help` target can be pretty dynamic.
