### ISSUE TITLE
Unexpected shutdown leads to data corruption

### ISSUE THREAD

**Issue by changsheng1239** [talos-systems/talos#2128]
## Bug Report
Talos failed to boot due to data corruption after forced shutdown

### Logs
![reboot](https://user-images.githubusercontent.com/29444534/82283626-80680b80-99c9-11ea-995c-5927223eba3e.PNG)

![error](https://user-images.githubusercontent.com/29444534/82283621-7e9e4800-99c9-11ea-84b1-261acbfda36f.PNG)

**Comment by andrewrynhard** [comment]
Thanks @changsheng1239 . We will look into this ASAP.

**Comment by andrewrynhard** [comment]
I think we may have fixed this in https://github.com/talos-systems/talos/pull/2443. Before this PR we had bind mounts into containers to the config, which was in the boot partition. We have found that even though you can successfully `unmount` the partition, the bind mounts would still exist to some degree, and the partition would never _really_ be unmounted. This could be the source of the corruption.

**Comment by andrewrynhard** [comment]
@changsheng1239 we fixed this in v0.7 ... we switched to using XFS.
