### ISSUE TITLE
docs: Add global architecture overview

### ISSUE THREAD

**Issue by patatman** [talos-systems/talos#2130]
### Description
As a new user i'd like to see all the running parts of a new installation. What are key components, and what are things to look out for.
For example:
 in 0.4 it's critical for the init node to be correctly up and running, before anything else. 
A simple visual/flowchart/diagram would make this clear for new users. This makes troubleshooting for new users more efficient.

**Comment by andrewrynhard** [comment]
Thanks @patatman ... agree we need this badly. At the end of the day things are simple, but since Talos breaks a lot of older conventions this is needed to make the transition easier.

**Comment by patatman** [comment]
When I have some more experience with my running cluster, I'll make a proposal here to add it to the docs.

**Comment by patatman** [comment]
This is a simple diagram showing the flow for a Bare-metal cluster.
![Untitled Diagram](https://user-images.githubusercontent.com/15031001/82464586-88ee3e00-9abe-11ea-8c1c-4996d2302838.png)

**Comment by andrewrynhard** [comment]
We should change talosctl to kubectl ... kubernetes is the only thing handled by the load balancer. Talosctl will talk directly to each control plane node.

**Comment by rsmitty** [comment]
Only other small nit I see is that step 2 of the controlplane should "Get controlplane.yaml" like the other two node types. But this is awesome, I love it!

**Comment by patatman** [comment]
New revision: 
Changelog: 
 - Added controlplane.yaml
 - Changed arrow direction of webserver (should be towards node)
 - Changed Talosctl to Kubectl.
![Talos_metal-flow (1)](https://user-images.githubusercontent.com/15031001/82788068-08d22a80-9e68-11ea-94b9-52aa2f466fbc.png)
