### ISSUE TITLE
docs: Add custom CA for internal registry

### ISSUE THREAD

**Issue by patatman** [talos-systems/talos#2181]
## Feature Request
Write docs dedicated to adding CA
### Description
Some companies have an internal CA which needs to be available to the OS before being able to pull from an internal registry for example. 
Currently using the docs for a corporate proxy: https://www.talos.dev/docs/v0.5/en/customization/proxy#appending-the-certificate-authority-of-mitm-proxies 

But it would be better to have docs for this specific use-case.

**Comment by andrewrynhard** [comment]
Good idea 👍. Maybe even one for using mirrors too.
