### ISSUE TITLE
Docs: Add latest tag

### ISSUE THREAD

**Issue by patatman** [talos-systems/talos#2204]
## Feature Request
Add latest tag instead of release tag
### Description
To link to the latest doc, it would come in handy to point to "latest" instead of a version tag.
This prevents sending users wrong docs, for older versions.

I noticed this when linking on our company Wiki to the Talosctl docs, it hard linked to 0.5. 
When someone comes along we might already be on v1.0 and thus linking to the wrong version.

**Comment by andrewrynhard** [comment]
:+1: Sounds like a good idea to me.
