### ISSUE TITLE
Node Reboot Check is Broken

### ISSUE THREAD

**Issue by rsmitty** [talos-systems/talos#2235]
We see this a lot in our nightly testing. In the talos integration tests when we do the "reboot all nodes" test, the nodes will reboot and the uptime doesn't seem to go down. Need to deep dive into why this is happening.

**Comment by smira** [comment]
I wonder if that is timeout on reboot, but I'm happy to dig into that

**Comment by rsmitty** [comment]
I closed this issue because the wording was off about what was actually broken, but the log output is a good example. Looks like the reboot happens, connectivity is restored, but uptime never actually goes down.

https://github.com/talos-systems/talos/issues/2229

**Comment by smira** [comment]
I feel there should be something else there, unless actually uptime doesn't go down after reboot?

**Comment by andrewrynhard** [comment]
> I feel there should be something else there, unless actually uptime doesn't go down after reboot?

Do we error if the reboot API call fails?

**Comment by rsmitty** [comment]
Another possible datapoint: we see this fairly often in our nightlies. Here's a good example of it failing with the same logs in GCP
https://ci.dev.talos-systems.io/talos-systems/talos/9455/1/33

**Comment by smira** [comment]
> Do we error if the reboot API call fails?

not sure, but on other hand looks like API is not responsive for some time after we issue reboot call.

I was also thinking if we should include crashdump here

**Comment by smira** [comment]
I hope this got better with #2245, but need more nightlies to verifiy that

**Comment by smira** [comment]
Looks like things are improving, going to close this one
