### ISSUE TITLE
integration tests: use boot_id to detect reboots

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#2268]
Currently we're using `/proc/uptime` to detect node reboots (uptime goes down)

We could have used `/proc/sys/kernel/random/boot_id` instead (thanks @Ulexus)

Need to double check it works with cloud VMs and firecracker.

**Comment by mdnix** [comment]
Hi @smira,

What types of cloud VMs should be checked for compatibility with /proc/sys/kernel/random/boot_id?

**Comment by smira** [comment]
@mdnix this issue is only about integration tests, so Talos itself doesn't use that

this feature should be available in any LInux cloud VM, as it's just part of standard Linux kernel procfs

**Comment by mdnix** [comment]
@smira Ah yes, I see. May I tackle this issue? I could change the integration tests to rely on `/proc/sys/kernel/random/boot_id`.

**Comment by smira** [comment]
@mdnix sure thing, please feel free to ask any questions here or in Talos slack https://slack.dev.talos-systems.io/

**Comment by smira** [comment]
Closed via #2451
