### ISSUE TITLE
integration tests: use filesystem uuid to detect node reset

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#2269]
In integration tests today we don't test properly that reset API wipes the node, we just test for reboot.

We could have used filesystem UUID change to verify that node got wiped and re-installed. (thanks @Ulexus)

**Comment by mdnix** [comment]
@smira I suppose the test can be added to RebootSuite?

**Comment by smira** [comment]
This ticket was for tests which `reset` (wipe) the node causing reinstall. But it looks like fetching filesystem UUID is not trivial, so I thought we should put it on hold for now

**Comment by Ulexus** [comment]
/dev/disk/by-uuid contains symlinks of the filesystem UUIDs to their respective block devices.  Note, however, that not all filesystems (looking at you, VFAT) implement proper UUIDs.

**Comment by smira** [comment]
Thanks! Probably we could use simple list API then and compare lists before and after reset

**Comment by mdnix** [comment]
That's cool. Is this issue still on hold or should we do something?

**Comment by smira** [comment]
Marco, please feel free to take it!

`List API` is something you can trigger with `talosctl -n <node> ls
/dev/disk/by-uuid`, if you can see what changes after reset, you can
capture that as a check in the integration test.

**Comment by smira** [comment]
we ended up checking kubelet cert hash, so probably we can close this one now
