### ISSUE TITLE
upgrade golangci-lint to 1.28.3

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#2272]
golangci-lint now has integrated gofumpt, so we can get rid of extra invocation.

**Comment by smira** [comment]
looks like we can't replace `gofumpt` for now, as `golangci-lint` doesn't support `-local`

**Comment by smira** [comment]
new interesting linters: `exhaustive` and `noctx`

**Comment by andrewrynhard** [comment]
`exhaustive` looks awesome. `noctx` caused me more work :D ... but its a good one.
