### ISSUE TITLE
usage of `files:` with `op: create` and `/var` persistence

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#2278]
## Bug Report

When using config [files](https://www.talos.dev/docs/v0.5/en/configuration/v1alpha1#files) with `op: create` on `/var` partition works fine on the first boot (as file doesn't exist), but fails on the next boot as file already exists.

### Description

Should we prohibit `create:` on `/var` paths?

Or should we make `create:` idempotent by ignoring the action if file already exists and matches the expected content?

**Comment by andrewrynhard** [comment]
I think we need to rethink the paths that we allow files to be created on. Let's put this on the agenda for either this week or the next.
