### ISSUE TITLE
Make machine types public again

### ISSUE THREAD

**Issue by rsmitty** [talos-systems/talos#2308]
In v0.6, we moved the machine types and machine config info under internal/app/runtime. We use these in our CAPI provider to determine what type of node we're dealing with before we generate machine configs. Additionally, the generate package requires these machinetypes as input when calling `generate.Config()`. We need to figure out a way to make that info public again so we can use it in the bootstrap provider. 

It falls over [here](https://github.com/talos-systems/cluster-api-bootstrap-provider-talos/blob/master/controllers/talosconfig_controller.go#L262) and [here](https://github.com/talos-systems/cluster-api-bootstrap-provider-talos/blob/master/controllers/talosconfig_controller.go#L331)

**Comment by smira** [comment]
yep, that was something I tried to explain with machined refactor, some of these types should be public interface of Talos (as they're part of the config for example)

**Comment by andrewrynhard** [comment]
I have some ideas on this related to some of our import restriction goals. Let's chat about this tomorrow some time.
