### ISSUE TITLE
create CNI bundle for Talos provisioning

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#2382]
## Feature Request

Both firecracker and qemu depend on subset of standard CNI plugins + `tc-redirect-tap`.

It would be nice if `talosctl cluster create` could download CNI plugins (if system-wide CNI is missing) to a local directory and use them for provisioning.

This way for qemu provisioner users only need to install `qemu` from their distro, and CNI will be installed automatically.

### Description

Problem: no release/binary download for [tc-redirect-tap](https://github.com/awslabs/tc-redirect-tap).

One possible solution: create Talos repo which downloads/builds subset of CNI plugins + tc-redirect-tap and publishes it as some .tar.gz for download. `talosctl cluster create` downloads that to ~/.talos/cni` for example.

**Comment by andrewrynhard** [comment]
We could also publish the cni bundle with the Talos release.

**Comment by andrewrynhard** [comment]
Then we could release a known version of CNI that we use daily in our tests.
