### ISSUE TITLE
CNCF SIG-Runtime discussion/presentation(?)

### ISSUE THREAD

**Issue by raravena80** [talos-systems/talos#2404]
### Description

Hello Talos team,

I'm one of the co-chairs of the [CNCF SIG-Runtime](https://github.com/cncf/sig-runtime), I looked at your project and I think it would be great for you to present/discuss it at one of our meetings. For example, how Talos enables container-based workloads on Kubernetes, how is it different from [Bottlerocket](https://github.com/bottlerocket-os/bottlerocket) or [Flat-car](https://www.flatcar-linux.org/)?

Let me know if this is something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by andrewrynhard** [comment]
@raravena80 Hello :wave:  We would love to present Talos! I will take a look at the agenda. Thanks!
