### ISSUE TITLE
docs: Document NFS compatibility

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#2442]
### Description

The version of NFS that Talos is compatible with is whatever version we install in the kubelet. We should document this.

**Comment by patatman** [comment]
I remember that I needed to use V3, will check on that and see if I can write some docs about it

**Comment by andrewrynhard** [comment]
Thanks @patatman. A little more color here. I think what we need to document is that the the version of nfs within our kubelet image is the version we support. That is another repo, and IIRC it was v4.

**Comment by masoudbahar** [comment]
Where one could find some information on NFS configuration, as there is no mention of the setup, in the guides? I think even an internet search clue will be quite useful.
Thanks.

**Comment by andrewrynhard** [comment]
@masoudbahar NFS in Talos actually really means NFS in Kubernetes: https://kubernetes.io/docs/concepts/storage/volumes/#nfs. The only way Talos influences this is the client version of NFS built into our kubelet container: https://github.com/talos-systems/kubelet.

**Comment by masoudbahar** [comment]
Thank you Andrew; from the reference to Kubelet above, I was wondering if that's the case, or it should be done through the disk configuration; this makes it very clear.
