### ISSUE TITLE
MTU Settings not working

### ISSUE THREAD

**Issue by rsmitty** [talos-systems/talos#2486]
Customer mentioned that mtu settings didn't take effect in 0.6.x release. Need to verify if that's something with talos or with sidero. If it's sidero, we may have fixed it when we pulled in newer config package.

**Comment by rsmitty** [comment]
Finally confirmed this is indeed a Talos issue. Metadata looked correct while eth0 looks like: 

```
NODE            INDEX   NAME           MAC                 MTU     ADDRESS
192.168.254.2   4       eth0           d0:50:99:d3:33:60   1500    192.168.254.2/24
```

**Comment by sergelogvinov** [comment]
It works in my case
talos version v0.6.0
```bash
machine:
  type: worker
  network:
    interfaces:
      - interface: eth0
        dhcp: true
      - interface: eth1
        cidr: "192.168.0.1/24"
        mtu: 8000
      - interface: dummy0
        cidr: "169.254.2.1/32"
        mtu: 3000
```

**Comment by smira** [comment]
@sergelogvinov yep, it works with static address, but it doesn't work with no address mode
