### ISSUE TITLE
Cluster creation is broken on mac

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#2495]
### Description

Looks like `127.0.0.1` is not an valid cert SANs, and the health client uses the internal IP, which isn't routable on a mac.

### Environment

- Talos version: v0.6.0
- Platform: Docker

**Comment by andrewrynhard** [comment]
Invalid ... use `--endpoint 127.0.0.1`

**Comment by smira** [comment]
Should we make this automated on ARM?
