### ISSUE TITLE
Leveled logging

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#256]
Using either the standard library, or something like logrus, we should provide more robust logging.

**Comment by bradbeam** [comment]
Need to review the various log packages to weigh them
- logrus ( ability to inject metadata with fields, native-ish syslog output )
- zap ( fast )
- glog / klog ( k8s uses, semi proven )
- others(?)

Need to figure out the appropriate log structure, ex. 
- If using logrus, do we want to have a standard set of fields we apply to all messages?
- Do we go super verbose on debug level messages to help with tracing?

Need to figure out log pattern -- 
Do we want to always log super verbose level, but filter/query via osctl? ( #wayfuturestate )

Once we get those pieces together, we should be able to just take on a package or so at a time and get this implemented

**Comment by smira** [comment]
with `zap`, there's some ground work done to let it flow to fluentd for aggregation: https://github.com/smira/zap-msgpack-encoder

**Comment by andrewrynhard** [comment]
Closing in favor of internal epic.
