### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#257]
Implement upgrades.

**Comment by TimJones** [comment]
As a note, I think an updating strategy similar to how ContainerLinux works with [CLUO](https://github.com/coreos/container-linux-update-operator).

In summery:
1) a system-level daemon polling for available updates and marking when a node can update with annotations\labels.
2) cluster-level operator coordinate with wait annotations amd\or an etcd lock to ensure only one node restarts at once. Ideally this would also hook into the `osctl reboot` process too.
3) system gets the OK and begins to drain/corden the node.
4) system applies the update
5) system restart

The update operator is really useful as it can coordinate with external processes via node annotations in special cases. E.G. that a rook.io cluster needs to mark the OSDs as temporarily down so as not to cause a re-balance just to reboot the node. Or if using Hashicorp Vault and the current node has the master it can issue a stand-down to gracefully hand off before restarting...

**Comment by andrewrynhard** [comment]
@TimJones Excellent points. I think this aligns more or less with what we have been thinking. The process you outlined I think will also work well in bare metal setups. We originally thought that we would have users create new nodes and destroy old ones, but this would require setups to have at least one swing node available at all times. I have always been a big fan of the CoreOS upgrade strategy. 

I like your thoughts on the integration with Kubernetes. I think this will be an absolute must.

When you get some time, take a look at https://github.com/openshift/cincinnati. It is apparently a reimagination of CoreOS's Omaha protocol. We have to nail upgrades, so we would be glad to brainstorm some more with you on this topic.

**Comment by andrewrynhard** [comment]
Closing, please refer to talos-systems/talos#739 .
