### ISSUE TITLE
talosctl: cluster-destroy should remove client configs on successful destruction

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#2582]
## Bug Report
It appears that `talosctl cluster destroy` does not remove the client configurations after a successful destruction of the cluster.  This means that subsequent invocations of `talosctl cluster create` will likely have unexpected results.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by smira** [comment]
I'm not sure if `talosctl cluster destroy` can ever remove anything, as it doesn't know for sure what is the client config.

`talosctl cluster create` on other hand is totally safe - it always pulls in (and merges) new config into the `~/.talos/config`.

**Comment by andrewrynhard** [comment]
> I'm not sure if `talosctl cluster destroy` can ever remove anything, as it doesn't know for sure what is the client config.
> 
> `talosctl cluster create` on other hand is totally safe - it always pulls in (and merges) new config into the `~/.talos/config`.

This is my fear too. We can't be certain then a file called kubeconfig in the current dir is something we should delete. Sure, it's very unlikely, buy we can't know for sure.

**Comment by Ulexus** [comment]
Yeah, this is a very good point.  It does seem that the suggested default-to-merge solution is the safer option.

**Comment by smira** [comment]
I think we already discussed the `default-to-merge` solution. It will never overwrite existing kubeconfig unless explicitly told to do so. 

btw, `talosconfig` gets merged (and overwritten) silently now for `talosctl cluster create`.
