### ISSUE TITLE
docs: cloud install guides needs `--nodes` option to get kubeconfig

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#2609]
## Bug Report

The next-to-last line of the GCP docs says `talosctl --talosconfig ./talosconfig kubeconfig .`, but this command fails because the `--nodes` option is now required for the kubeconfig command.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by AngelOnFira** [comment]
I believe this is the case for all install guides, not just GCP

**Comment by andrewrynhard** [comment]
@AngelOnFira good point. We will get this fixed 👍.
