### ISSUE TITLE
docs: for each platform, list talosctl limitations

### ISSUE THREAD

**Issue by steverfrancis** [talos-systems/talos#2630]
## Bug Report
e.g. on https://www.talos.dev/docs/v0.6/en/guides/local/docker, mention that upgrades, reboots, etc are not supported.
### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by Ulexus** [comment]
Docker is something of a special case.  Do we have any similar restrictions with any other platform?

**Comment by andrewrynhard** [comment]
@Ulexus I don't _think_ so.

**Comment by smira** [comment]
we have it now by the way in the server/talosctl - talosctl rejects requests with a meaningful error
