### ISSUE TITLE
DOCS - aws.md should specify CP_NODE IP address in register-targets

### ISSUE THREAD

**Issue by rrichardson** [talos-systems/talos#2720]
### Description

In the aws.md illustrating the example deployment process, the step where the registration of the CP nodes with the load balancer could use some clarification:  

```aws elbv2 register-targets \
    --region $REGION \
    --target-group-arn $TARGET_GROUP_ARN \
    --targets Id=$CP_NODE_1  Id=$CP_NODE_2  Id=$CP_NODE_3
```

This doesn't specify whether CP_NODE_1 is an `Instance ID` or an `IP Address`  According to the AWS docs, either one will work, and the AWS examples demonstrate supplying an `Instance ID`. 

**InstanceID will not work for this use case, and will result in incredibly frustratingly difficult to track errors**  
See : https://aws.amazon.com/premiumsupport/knowledge-center/target-connection-fails-load-balancer/

Please update the docs to specify using the `Private IP Address` (it must be private) as targets for `register-targets`

### Environment

- Platform: AWS

**Comment by rsmitty** [comment]
Closed via #2721. Thx @rrichardson!
