### ISSUE TITLE
[networkd] support subinterfaces being down during bond creation

### ISSUE THREAD

**Issue by rsmitty** [talos-systems/talos#2771]
Ran into this error with packet: https://github.com/talos-systems/talos/blob/master/internal/app/networkd/pkg/networkd/networkd.go#L165.

This occurred because we filter out any link with no carrier up above in the code, so eth1 in this case didn't get added to the list of interfaces. We should make sure that any subinterfaces (and virtual interfaces for that matter) make it into the filtered list and dont' require being fully up in order to become part of a bond or get configured.

**Comment by smira** [comment]
Fixed with Talos 0.11 networking rewrite.
