### ISSUE TITLE
extend block device / mount tools to support LUKS/dm-crypt partitions.

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#2786]
We need to be able to:
  - detect whether a partition is encrypted or not (LUKS does this via its metadata)
  - apply a key to encrypt and mount an encrypted partition

Possible tools:
 - [Luks.go](https://github.com/anatol/luks.go)
 - [gocryptfs](https://github.com/rfjakob/gocryptfs)
 - [age](https://github.com/FiloSottile/age)
 - [clevis/tang](https://github.com/latchset/clevis)
 - [sharedsecret](https://github.com/posener/sharedsecret) Shamir's Secret Sharing Algorithm

**Comment by smira** [comment]
As another note, we already have unencrypted meta partition which can be used to store a flag which enforces state encryption, so that we could skip detection

**Comment by Ulexus** [comment]
We could, but LUKS does already handle this with metadata on the partition.

**Comment by Ulexus** [comment]
(Though that would be useful for a flag to explicitly disable opportunistic encryption)

**Comment by Ulexus** [comment]
It's also an option to use something like age to simply encrypt the configuration _file_ or something like gocryptfs to encrypt a _directory_, rather than the entire partition.

**Comment by Ulexus** [comment]
Of note:  the referenced luks.go library does not allow for manipulation of the metadata; it only handles read-only access.  Basically, it can be used to work with an existing LUKS volume, but it cannot currently be used to create one.

**Comment by smira** [comment]
Also some notes I collected a while ago: https://thoughts.smira.ru/disk-encryption
