### ISSUE TITLE
replace bootkube

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#2787]
## Feature Request

Bootkube is mostly unnecessary for Talos.  Having direct control of the controlplane components would be much more flexible and reliable.

However, getting rid of bootkube does mean we need to replace its features:
  - controlplane template generation (mostly handled already, since we maintain a Talos-specific bootkube [plugin](https://github.com/talos-systems/bootkube-plugin) for this)
  - the controlplane components need to be converted into simple static Pods rather than DaemonSets
  - these static pods need to be injected into the kubelet's manifest directory
  - bootkube stores the PKI components as Secrets; we need to instead store these as files and reference them
  - upgrade story (see below)

Once we are off of bootkube, we have full control of the control plane, and hence direct control over the versioning.  We can then handle kubernetes upgrades from Talos.  However, we need to be able to coordinate these upgrades.  That would generally be a job for the talos controller manager.  However, since the talos controller manager runs from inside kubernetes, that presents something of a risk.  It may be better, instead, to take out locks on etcd directly.  This is much safer, and nothing in the upgrade requires any node to reboot, meaning that the native lease-lock mechanism of etcd would work perfectly.

In order to do this, we could consider a certain set of etcd keys:
  - `talos.kubernetes.version`
  - `talos.kubernetes.kubelet.image`
  - `talos.kubernetes.kube-apiserver.image`
  - `talos.kubernetes.kube-scheduler.image`
  - `talos.kubernetes.kube-controller-manager.image`
  - `talos.kubernetes.kube-proxy.image`
  - `talos.kubernetes.kube-proxy.disable`
  - `talos.kubernetes.coredns.image`
  - `talos.kubernetes.coredns.disable`
  - lease of `talos.kubernetes.upgrade_lock`

A kubernetes upgrade request would come in via API on machined of one of the nodes.  That node would attempt to take out a lease on `talos.kubernetes.upgrade_lock`.  If that lease fails, it returns an "upgrade already in progress" error.  

Likewise, machined could perform periodic checks of `talos.kubernetes.version` and check the component versions it is running, at which point it would attempt the upgrade itself.  This covers the case where an upgrade fails and the upgrader gets rebooted or otherwise loses state.

The recommended kubernetes upgrade order is:
  - kube-apiserver
  - kube-scheduler
  - kube-controller-manager
  - kube-proxy (if not disabled)
  - coredns
  - kubelet

In order to achieve this, we will need to enable an (private, perhaps) API call to tell a node to upgrade a particular discrete component.  This way, whatever node is running the upgrade can first upgrade all the apiservers, validating each as it does so, then upgrade each kube-scheduler, etc.

It is worth considering storing the entirety of the talosconfig cluster configuration in etcd, since it really should not be sourced from any node after the initial bootstrapping.  This, then, allows the single source of truth for the entire cluster to be etcd.

NOTE:  special care should be taken with the kube-controller-manager:  it often takes a minute or two to fail after saying that it is all happy up and running.

All of this should be achievable with a standard controller loop:
  - check the desired kubernetes version
  - calculate the appropriate images for each of the control plane components based on that image
  - check the etcd field storing that version; if it differs, iterate through the control plane nodes and make each match your new image
  - update the image reference of the component when all the upgrades of it are complete
  - repeat for each subsequent component

(of course, feel free to modify the suggested etcd schema above to provide whatever flexibility is required)

Another option is to make this process more distributed, and create etcd keys for each node, describing what it should be running.  Then, each node simply monitors those keys for itself, matching whatever it is running with whatever etcd says to run.

**Comment by smira** [comment]
Closing this issue, even though the implementation is different from what is described in this issue, but bootkube is replaced in Talos 0.9.
