### ISSUE TITLE
networkd: static and dhcp should not be mutually-exclusive

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#2804]
## Feature Request

There are many configuration features of a network interface which should be applied regardless of the use of DHCP.  For instance:
  - MTU
  - Static routes

Moreover, it is likely that a person should wish to configure both static CIDRs _and_ use DHCP.

Therefore, the design of the networkd address configurator should change.  There should not be separate "dhcp" and "static" providers, but rather, we should configure things which are declared in each interface config and also optionally run DHCP.

This will likely also change the way DHCP works, since we should _not_ override statically-declared routes (while currently, the routes are completely replaced).

Ref #2789

**Comment by smira** [comment]
In terms of implementation, everything should be ready to support `DHCP` & static addresses in the network controller land

the only thing which should be changed for this ticket is to drop the validation requirement to have either DHCP or static addressing

this can be tested via `talosctl edit mc --immediate` adding a secondary address
