### ISSUE TITLE
Single node upgrade not working to stable v0.7.0 from alpha.8

### ISSUE THREAD

**Issue by salkin** [talos-systems/talos#2806]
## Bug Report
Trying to do an upgrade for single node fails in the upgrade sequence:

### Description

Running upgrade command with -p flag set and v0.7.0 installer image

### Logs

172.26.4.101: [talos] task stopAllPods (1/1): failed
172.26.4.101: [talos] task stopAllPods (1/1): done, 2.863869398s
172.26.4.101: [talos] phase cleanup (2/10): failed
172.26.4.101: [talos] upgrade sequence: failed
172.26.4.101: [talos] upgrade sequence: done: 1m30.735901165s
172.26.4.101: [talos] upgrade failed: error running phase 2 in upgrade sequence: task 1/1: failed, rpc error: code = NotFound desc = failed to get verbose sandbox container info: failed to get task status: task 437228c7ebf26441219b418edcd1655f7f04204d41f75488784f56fce7ce52f0 not found: not found
172.26.4.101: [talos] fatal sequencer error in "upgrade" sequence: message:"sequence failed: error running phase 2 in upgrade sequence: task 1/1: failed, rpc error: code = NotFound desc = failed to get verbose sandbox container info: failed to get task status: task 437228c7ebf26441219b418edcd1655f7f04204d41f75488784f56fce7ce52f0 not found: not found"
172.26.4.101: [talos] rebooting in 10 seconds
172.26.4.101: [talos] rebooting in 9 seconds

### Environment
Server:
        NODE:        172.26.4.101
        Tag:         v0.7.0-alpha.8
        SHA:         50527fe0
        Built:
        Go version:  go1.15.3
        OS/Arch:     linux/amd64

- Kubernetes version: 
1.19.1

- Platform:
qemu

**Comment by smira** [comment]
Is that reproducible?

There should be some race condition in this code, and we should probably ignore not found errors here, but I wonder if there's a way for me to reproduce it

**Comment by salkin** [comment]
Yes, tried two times and have not got it successful yet, can try few more times. 

After that failure is happening the node stays also with taint unschedule set so on need to manually clean up to get it back working.

**Comment by smira** [comment]
@salkin Niklas, I have a potential fix for this bug, but I wasn't able to reproduce it so far to reproduce the fix. If you could post some details which would help me - like CNI being used or some workload running in the cluster triggering that, I would appreciate it.

**Comment by salkin** [comment]
It's multus as the main plugin, flannel/calico (aka canal) as the overlay network. Multiple pods have both flannel + macvlan

**Comment by smira** [comment]
> It's multus as the main plugin, flannel/calico (aka canal) as the overlay network. Multiple pods have both flannel + macvlan

:+1: with just canal as CNI I'm able to reproduce the issue
