### ISSUE TITLE
networkd refactor

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#2809]
## Feature Request

There are a number of growing pains we are experiencing with networkd, and while it could continue to be patched and bodged, it seems reasonable to consider instead a refactor, to fix some of the misaligned base assumptions.

### Description

Deficiencies to address:
  - Events (COSI) and dynamic network situations
  - Separation of physical and logical interfaces
  - Invalid dichotomies (such as DHCP <-> Static)
  - Invalid assumptions (IPv6, routes, CIDRs, etc)

Systemd-networkd offers a good functional pattern, in my opinion.  It has appropriately separated concerns and defined both good, simple defaults and good mechanisms for composing various features.

We need to keep the most common use cases as simple as they are now, but we need better support for more interesting situations.

Particular exemplary issues:
  - #2804 - static and dhcp are not mututally-exclusive
  - #2777 - bonds create duplicate routes
  - #2771 - bonds should allow for subinterfaces being down
  - #2270 - need better network logging
  - #1865 - need logical devices for testing networkd
  - #2789 - always apply MTU, regardless of DHCP operation

### Design

Event-based operation is a key feature.  We need to be able to respond to changes such as:
  - link up/down
  - interface added/removed
  - configuration changes

#### Control Loop

We should run networkd similarly to a kubernetes control loop:  when an event occurs, we read the config and try to make that config true.  Moreover, the failure of any single interface to configure should not cause an abort or failure of any other interface.  The failure of any _type_ of configuration of an interface should not cause the failure of that interface (for instance, DHCP failure when we have a static config also).

Interfaces have a state, but the control loop simply makes best efforts to make its config true.  A particular failure is considered transient and not fatal.  (However, there may be higher level processes which determine that a general network failure may be fatal, causing a reboot.   These just don't belong in networkd itself.)

#### Interface order

The ordering of operation of interfaces should to take into account dependent interfaces (for instance, for bonds, vlans, tunnels, bridges, etc), but the creation of subtended logical interfaces should not require all component interfaces to be "up" for their creation.  Many downstream processes may need to be able to bind to those logical interfaces, even if they are not "up" and "usable".

#### Error handling and states

The result of an execution of networkd's control loop should not, in and of itself, cause a fatal error of Talos.

Failures of a particular interface should always be logged.

#### Flow

Generally, we should adopt an option-branching structure rather than a dualistic "mode" structure.  (For instance, we do not have a sequence for a "dhcp-addressed" interface, but a sequence for running "dhcp _on_ an interface".)

#### Routes

There are two types of routes:  interface-bound routes and system routes.  The former are only added when the associated interface is added (regardless of up status--- the kernel routing table handles this).  The latter are always added after interfaces are processed.

We should also consider in the design the fact that the kernel supports multiple routing _tables_.  For the moment, we do not need to do anything about this, but we should consider this in the design of the config and specification.

**Comment by smira** [comment]
We should also stop the habbit of running network discovery without networkd early in the boot, but run the networkd whole time from the boot till shutdown. Config might change while the node is running, and networkd should adapt accordingly.

**Comment by smira** [comment]
this got resolved in Talos 0.11 except for #2804 which is just a machine configuration change (scheduled for 0.12)
