### ISSUE TITLE
[Docs] Network port usage by talos

### ISSUE THREAD

**Issue by e-nomem** [talos-systems/talos#2870]
### Description
It's not well documented anywhere what ports are used by the various components of Talos. From looking through the code, I see that there are at least the following:
 - `apid` listening on TCP/50000
 - `trustd` listening on TCP/50001

A page documenting these ports and their usage would be nice, especially in the context of building up firewall rules. Some questions that I currently have:
1. What ports does `talosctl` need access to? `apid` seems obvious, but I assume access to `trustd` is required as well?
2. What ports are used for communication between the control plane nodes and worker nodes? (aside from the standard k8s stuff, of course)
3. Anything else that would be relevant?

If these questions can be answered here, I don't mind writing up the documentation myself in a PR.

**Comment by andrewrynhard** [comment]
👋Hello @e-nomem. Thanks for raising this issue. This would certainly be good to document. To answer your questions:

1. `talosctl` only needs access to the `apid` port (50000).
2. communication between control plane and worker nodes is done through the `trustd` port (50001).
3. 🤔 Not that I can think of. Maybe just that the API server listens in 6443.

I hope that helps.

**Comment by rsmitty** [comment]
We can highlight the k8s ones too just so folks know which ones to allow internally if they're using security group in the cloud or something. We'll get this added to our backlog.
