### ISSUE TITLE
single-node upgrade CRI stop issue with Multus CNI

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#2882]
CNI has dependency on kube-apiserver

CNI link https://git.dac.nokia.com/kubernetes/cni/blob/master/canal.yaml

**Comment by smira** [comment]
I did some manual tests for reset and upgrade, so far all tests were successful

**Comment by smira** [comment]
I think we can add reset with options e2e-test for single-node cluster with this specific canal CNI

**Comment by smira** [comment]
Closed via #3002
