### ISSUE TITLE
ARM64 Raspberry Pi apply-config interactive fails

### ISSUE THREAD

**Issue by BobyMCbobs** [talos-systems/talos#2910]
## Bug Report

Running
```
talosctl apply-config --insecure --interactive --nodes 192.168.1.2
```

returns

```
error constructing client: failed to determine endpoints
```

on every node

### Description
I prepared my nodes via:
1. updating the RPi firmware to the latest
2. flashing the latest v0.8.0 release to the RPis
3. running the bootstrap command

as per [the docs](https://www.talos.dev/docs/v0.8/single-board-computers/rpi_4/)

### Logs
Already described

### Environment

- Talos version:
```
Client:
	Tag:         v0.8.0-alpha.2
	SHA:         6f845ae0
	Built:       
	Go version:  go1.15.5
	OS/Arch:     linux/amd64

Server:
error constructing client: failed to determine endpoints
```
(two nodes on the same version)
- Kubernetes version: ['Client Version: v1.19.4', 'Server Version: v1.20.0-rc.0']
- Platform: _arm64_

# Notes

What did work was 

```
talosctl gen config mycluster https://192.168.1.2:6443 --output-dir . --arch arm64 --additional-sans k8s.mynetwork.local --install-disk /dev/mmcblk1 --install-image ghcr.io/talos-systems/installer:latest@sha256:7334e8de85ea7553af776aeff135fd514d02c8bb0cd9c42db4d047b6c4cf695b
talosctl apply-config --insecure --nodes 192.168.1.2 --file init.yaml
```

**Comment by andrewrynhard** [comment]
Thank you for reporting @BobyMCbobs. We will investigate this. In insecure mode the UX is that an endpoint isn't required, but there might be a workaround for now. Can you try the interactive installer and add `--endpoints 192.168.1.2` to the command? Curious if that works.

**Comment by BobyMCbobs** [comment]
> Thank you for reporting @BobyMCbobs. We will investigate this. In insecure mode the UX is that an endpoint isn't required, but there might be a workaround for now. Can you try the interactive installer and add `--endpoints 192.168.1.2` to the command? Curious if that works.

OK! That worked (without `--insecure`) kinda - it didn't go much further for installation (I'll replicate it again soon). Neat installer, I like it!
