### ISSUE TITLE
failed to resolve configuration context: talos config file is empty

### ISSUE THREAD

**Issue by fragolinux** [talos-systems/talos#2956]
hi, trying to install 3vms in proxmox, all booted from iso 0.7.1, saw their IPs and made reservation on router dhcp leases, installed talosctl on proxmox host itself to manage them, i get the error in subject:

```
export CONTROL_PLANE_IP=192.168.1.27
talosctl gen config talos-clu https://$CONTROL_PLANE_IP:6443 --output-dir _out
talosctl apply-config --insecure --nodes $CONTROL_PLANE_IP --file _out/init.yaml

failed to resolve configuration context: talos config file is empty
```

what's wrong? thanks
the files in the _out folder are all there...

**Comment by smira** [comment]
@fragolinux this bug was already fixed in `master`, you can workaround it by adding flag `--talosconfig=talosconfig` for `talosctl apply-config --insecure` command

`0.8.0-alpha.3` release has this bug fixed, but you need to use images from `0.8.0-alpha.3` as well as `talosctl` binary

**Comment by fragolinux** [comment]
thanks, then i'll go for the alpha3 :)

**Comment by fragolinux** [comment]
worked, thanks!
