### ISSUE TITLE
doc: Talos omits machine NTP configuration

### ISSUE THREAD

**Issue by alex1989hu** [talos-systems/talos#3005]
## Bug Report

Given `macnihe.ntp` configuration:

```yaml
version: v1alpha1
machine:
  time:
    servers:
      - ntp.foo.bar
      - ntp1.foo.bar
      - ntp2.foo.bar
      - ntp3.foo.bar
```

Similar issue: https://github.com/talos-systems/talos/issues/2677

### Description
- Start virtual machine *(talos-v0.8.0 OVA)*
- Check `kernel` messages via `talosctl dmesg`
- Talos want to reach `pool.ntp.org` despite the configuration *(see above)*

**Note:** I have just checked `talos-v0.7.0`: kernel does not log any line contains `pool.ntp.org` message.

### Logs
```bash
# Also affects worker node
$ talosctl dmesg
tls-k8s-master-1: kern:  notice: [2020-12-29T10:24:07.214458049Z]: XFS (sda6): Mounting V5 Filesystem
tls-k8s-master-1: kern:    info: [2020-12-29T10:24:07.231556049Z]: XFS (sda6): Ending clean mount
tls-k8s-master-1: kern: warning: [2020-12-29T10:24:07.243821049Z]: xfs filesystem being mounted at /var supports timestamps until 2038 (0x7fffffff)
tls-k8s-master-1: user: warning: [2020-12-29T10:24:10.320135049Z]: [talos] query error: lookup pool.ntp.org on 10.220.220.221:53: no such host
tls-k8s-master-1: user: warning: [2020-12-29T10:24:10.578714049Z]: [talos] task mountEphermeralPartition (1/1): done, 3.375771473s

[...]

tls-k8s-master-1: user: warning: [2020-12-29T10:24:20.20103956Z]: [talos] service[apid](Running): Health check successful
tls-k8s-master-1: user: warning: [2020-12-29T10:25:14.12321256Z]: [talos] failed to do one-time time sync: error querying pool.ntp.org for time, failed to query NTP server: 2 error(s) occurred:
tls-k8s-master-1: user: warning: [2020-12-29T10:25:14.12349656Z]: \x09lookup pool.ntp.org on 10.220.220.221:53: no such host
tls-k8s-master-1: user: warning: [2020-12-29T10:25:14.12363156Z]: \x09context canceled
```

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
```bash
Server:
        NODE:        tls-k8s-master-1
        Tag:         v0.8.0
        SHA:         cf5226a5
        Built:
        Go version:  go1.15.6
        OS/Arch:     linux/amd64
```
- Kubernetes version: [`kubectl version --short`]
`N/A`
- Platform:
`VMware`

**Comment by smira** [comment]
@alex1989hu this is not a bug on its own, Talos tries to do one-time NTP sync early in the boot to sync the time before configuration is loaded. 

To explain why this is needed:

* on SBCs, there's no RTC, so on boot time is completely off always, and for even simple TLS interaction to work (e.g. pulling down container image), Talos needs some NTP service 
* on bare-metal if for some reason RTC has incorrect time, Talos needs one-time sync to make time at least relatively up to date to fetch configuration over https (as once again includes TLS verification)

This is done before config is loaded (as config is coming over https potentially), it's one-time, and it doesn't block the boot. 

Real time sync process can be seen with `talosctl time` or `talosctl logs timed` commands.

**Comment by smira** [comment]
(we need to document this behavior to avoid confusion, but hopefully there's no real issue with time sync once the config is loaded)

**Comment by DWSR** [comment]
@smira It feels weird to me to have a time sync use a server that isn't specified in the configuration once the configuration is applied.

**Comment by smira** [comment]
@DWSR that's true, but on some platforms loading a config requires https interaction, so we need time to be somewhat in sync before we load the config.

It will certainly be improved in the next versions of Talos.

Just to make it clear, it doesn't block the boot nor it doesn't fail on time sync failure

**Comment by smira** [comment]
Documented in #3295
