### ISSUE TITLE
[regression issue] Talos v0.8.0 handles console extraKernelArgs wrongly

### ISSUE THREAD

**Issue by abckey** [talos-systems/talos#3011]
### Description
Things works in v0.7.X, but in talos v0.8.0, something is changed:

Following console args in talosconfig lead to kernel command line `console=ttyS0 console=tty0 console=tty0 console=ttyS1,115200`

```        
            extraKernelArgs:
            - console=tty0
            - console=ttyS1,115200
```

So in the end, the appended args are not taken into use.

### Environment

- Talos version: v0.8.0

**Comment by Unix4ever** [comment]
In v0.8.0 all metal images have these these two arguments defined by default:
```
console=ttyS0 console=tty0
```

So you can remove `console=tty0` from `extraKernelArgs` now.

As of `console=ttyS0`... If I understand how things work it should just enable one additional serial console, not disable others.
If that breaks something on your side maybe we can figure out some way to disable default kernel arguments.

**Comment by smira** [comment]
We need to look into that and see if extra kernel args should overwrite vs. append new valies

**Comment by abckey** [comment]
> We need to look into that and see if extra kernel args should overwrite vs. append new values

h

**Comment by abckey** [comment]
this is quite similiar with sidero agent case: https://github.com/talos-systems/sidero/issues/251
since only first serial console setting is taken into use, I would say if console settings are defined in extraKernelArgs, talos should override the default ones
