### ISSUE TITLE
talosctl list --recurse / --depth handling is confusing

### ISSUE THREAD

**Issue by AlekSi** [talos-systems/talos#3018]
### Description

On 0bd8b0e8008c12e4914c6e9b5faf06dda6c744f7, `talosctl list`'s `--recurse` / `--depth` handling is confusing:

| --recurse       | --depth     | Result     |
| --------------- | ----------- | ---------- |
| false (default) | -1          | one level  |
| false (default) | 0 (default) | one level  |
| false (default) | 1           | one level  |
| false (default) | 2           | one level  |
| true            | -1          | all levels |
| true            | 0 (default) | all levels |
| true            | 1           | one level  |
| true            | 2           | two levels |

Not sure what would be the best fix. Some of the options I see:
1. "Just fix it". But then `talosctl list --recurse=false --depth=0 /etc` should return nothing? Or `--depth` should be ignored if `--recurse` is false? Not sure if that's a good UX.
2. Remove `--recurse` flag (and API field) completely, treat `--depth=0` (or negative) as unlimited depth, and change the default value to 1.

**Comment by smira** [comment]
cc @Unix4ever
