### ISSUE TITLE
Add the network interface status in talosctl network output

### ISSUE THREAD

**Issue by mskumarece** [talos-systems/talos#3020]
## Bug Report
Talosctl should support printing the status of the network interfaces. Whether the interface is  UP/DOWN...
https://taloscommunity.slack.com/archives/GTMRUB137/p1610112784299800

### Description
![image](https://user-images.githubusercontent.com/8288981/104021676-2e3c5a80-51e5-11eb-81da-c6f6b27541b3.png)

what is needed

![image](https://user-images.githubusercontent.com/8288981/104021723-41e7c100-51e5-11eb-9956-120c21f13e9a.png)

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: kubectl version --short
Client Version: v1.16.0
Server Version: v1.19.1

- Platform: metal
```
/talos# talosctl --talosconfig out.yaml version
Client:
        Tag:         v0.7.1
        SHA:         333bc8fd
        Built:
        Go version:  go1.15.5
        OS/Arch:     linux/amd64

Server:
        NODE:        192.168.253.101
        Tag:         v0.8.0
        SHA:         cf5226a5
        Built:
        Go version:  go1.15.6
        OS/Arch:     linux/amd64
```

**Comment by smira** [comment]
ping @Ulexus

**Comment by Ulexus** [comment]
Yeah, I would agree, and I'd _also_ say that interfaces and addresses should be different API calls, like routes.

**Comment by smira** [comment]
this should now be available in `talosctl get links -o yaml`
