### ISSUE TITLE
Add config option for containerd

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#303]
We should support a user supplied config.toml for containerd.

**Comment by andrewrynhard** [comment]
See https://github.com/containerd/containerd/blob/master/docs/man/containerd-config.toml.5.md.

**Comment by bradbeam** [comment]
Need to figure out if this is what we really want to do in terms of exposing this. Most of the config will always be static//the same, but settings like pause/gc delay/etc might be worthwhile?
