### ISSUE TITLE
Huge pages support

### ISSUE THREAD

**Issue by Born2Bake** [talos-systems/talos#3046]
Hello,

I am wondering, if there is possibility to configure hp on machines? I want to test https://mayastor.gitbook.io/introduction/quickstart/prerequisites new storage solution but it requires hp to be enabled on machines. Thank you

**Comment by andrewrynhard** [comment]
@Born2Bake We have support for tuning the kernel via the `sysctl` key under `machine`. Something like this should work:

```
machine:
  sysctls:
    vm.nr_hugepages: "10"
```

You will probably need to update it with the correct value.

**Comment by Ulexus** [comment]
The sysctl is insufficient alone.  The kubelet needs the hugepages' hugetlbfs mounted, as well:

```
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
```

**Comment by DWSR** [comment]
Looks like https://github.com/talos-systems/talos/pull/3058 will add Huge pages support.

**Comment by Born2Bake** [comment]
Just to confirm, in order to use hugepages, I would need to update talos to the next release and add
```
machine:
  sysctls:
    vm.nr_hugepages: "512"
```
to server configs?

**Comment by smira** [comment]
yes, exactly, it should be 0.9.0-alpha.0 when it gets released
