### ISSUE TITLE
User Triggered Shutdown/Reboot Should Be Graceful

### ISSUE THREAD

**Issue by DWSR** [talos-systems/talos#3095]
As an operator, when I execute `talosctl shutdown` or `talosctl reboot` against a node, I expect that the node will be drained in Kubernetes in order to prevent disruption to workloads in the cluster, similar to [KEP-2000](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/2000-graceful-node-shutdown/README.md).

**Comment by mologie** [comment]
This feature would be helpful for https://github.com/mologie/talos-vmtoolsd for seamless vSphere Lifecycle Manager controller cluster upgrades when VMs cannot be live-migrated to other hosts during the update (e.g. when they have a GPU attached or are encrypted with AMD SEV).

An alternative would be for all cluster upgrading software to also integrate with K8s and drain the node explicitly, but given that `talosctl reset` and `talosctl upgrade` already have graceful shutdown built-in it would make sense to me to expand this functionality to the shutdown and reboot commands.

**Comment by smira** [comment]
Kubelet seems to only have a way to do shutdown via DBus message. 

Go implementation: https://pkg.go.dev/github.com/godbus/dbus

**Comment by sergelogvinov** [comment]
yep... no ```kill``` implementation...
