### ISSUE TITLE
No network connection between (worker) nodes

### ISSUE THREAD

**Issue by mr-sab** [talos-systems/talos#3152]
### Description
I have deploy one master with two worker. All default config. It looks like there is no connection possible between the different worker nodes. I tested it with a nginx deployment. I can get the page from different pods as long as there a running on the same node. I think this is a problem with the firewall. Is there someone that also is using more that 1 worker but is able to connect to pods running on different nodes?

I think it the firewall because it gives me no response, when I do the same test from a pod that is running on the other node it is working.
Also did a Packet Capture from my router to see if there was traffic send but i only saw etcd traffic.

### Environment
Esxi 7 (no vcenter) using the baremetal image.
tested it with version 0.8.2 and 0.8.3

**Comment by smira** [comment]
@mr-sab Talos doesn't set up any firewall at the node level. 

This might be a connectivity issue between the nodes in your environment (ESXi) or CNI issue. Default configuration doesn't limit any communication, so it should work out of the box. 

There are though some caveats with VMWare environment and network drivers in regards to Kubernetes CNI.

Issue #3143 has some hints - I believe vmxnet default networking driver doesn't work in 7.x, and workaround is to use e1000 virtualization.

**Comment by mr-sab** [comment]
Wow that was the fix(using the e1000), never thought it could be that, thanks alot :+1:
