### ISSUE TITLE
Document metrics-server setup on Talos

### ISSUE THREAD

**Issue by DWSR** [talos-systems/talos#3166]
`metrics-server` is a very common Kubernetes add-on that enables the use of things like Horizontal PodAutoscalers and the `kubectl top` commands, however it does not Just Work(tm) on Talos.

The procescs for installing `metrics-server` on Talos should be documented for future users

**Comment by aceat64** [comment]
I was able to get metrics-server working, but it required setting `--kubelet-insecure-tls`. Once issue #3502 is resolved I can write some documentation on deployment.

**Comment by DWSR** [comment]
https://github.com/alex1989hu/kubelet-serving-cert-approver/ This is a "proper" workaround I found, which also supports periodic rotation of `kubelet` certificates.
