### ISSUE TITLE
Rebooting Talos in offline mode is not working

### ISSUE THREAD

**Issue by salkin** [talos-systems/talos#3229]
## Bug Report
Rebooting a talos node in an air-gapped environment is not working as there is a try to pull Etcd image.

### Description

In reboot of talos node without internet connectivity the reboot hangs. Once restoring the internet connectivity reboot continues. It should be possible to run Talos in air-gapped without local registry. Without internet the reboot is stuck with  `failed to pull image`

Etcd service:
```
  80   // Pull the image and unpack it.
  81   containerdctx := namespaces.WithNamespace(ctx, constants.SystemContainerdNamespace)
  82   if _, err = image.Pull(containerdctx, r.Config().Machine().Registries(), client, r.Config().Cluster().Etcd().Image()); err != nil {
  83     return fmt.Errorf("failed to pull image %q: %w", r.Config().Cluster().Etcd().Image(), err)
  84   }
  85
```

### Environment

- Talos version: 0.8.1
- Kubernetes version: v1.19.1
- Platform: Bare-metal

**Comment by smira** [comment]
This is caused by the fact that `etcd` runs in a system containerd which is completely ephemeral - it's using `tmpfs` as storage, so after a reboot it comes with completely empty state.

**Comment by salkin** [comment]
I did not quite get how is that related to you have to pull the image? This issue is only about not pulling the image if it's already present in containerd cache.

**Comment by smira** [comment]
The problem is that `containerd` cache in this case lives in `tmpfs`, so it's gone after a reboot. This is only true for system containerd, not `cri` containerd. I'm just explaining the reason here, we certainly need to discuss ways to fix this

**Comment by salkin** [comment]
got it, I was not aware of the tmpfs for the containerd.
