### ISSUE TITLE
/var/log/containers not mounted to kubelet

### ISSUE THREAD

**Issue by salkin** [talos-systems/talos#3254]
## Bug Report

/var/log/containers is missing as kubelet is not having bind mount for the directory.

### Description

/var/log/containers is the only supported way to collect logs from containers when using fluent-bit. In order to not have need to use FluentD but keep the low foot print of fluent-bit /var/log/containers should be mounted into kubelet to be able to use the kubelet created symlinks for container logs.

### Environment

- Talos version: 0.9.0-alpha.4
- Kubernetes version: 1.20.4
- Platform: bare-metal

**Comment by smira** [comment]
Talos supports this via the config https://www.talos.dev/docs/v0.8/reference/configuration/#kubeletconfig

**Comment by salkin** [comment]
> Talos supports this via the config https://www.talos.dev/docs/v0.8/reference/configuration/#kubeletconfig

I tried that but Talos is not ensuring an extra mount volume directory gets created first. If only adding the mount Kubelet fails to start as the directory is missing on host side.

**Comment by smira** [comment]
Wronf reference: should be #3261
