### ISSUE TITLE
zsh completions are not working

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#3318]
## Bug Report

It has been reported that `zsh` completions for `talosctl` are not working.  This needs to be tested and refreshed.  Some of the comments, for instance, still reference the old `osctl`, at a minimum.

Also, we might take this opportunity to add `fish` completions...

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by jonkerj** [comment]
Let me start by saying I don't understand the internals of zsh/bash-completion at all. But As I'm having this problem with 2 (`flux` and `talosctl`) out of 4 completing tools (the others being `helm` and `kubectl`) all using spf13/cobra v1.1.1 for completion, I did a little comparing.

It seems the working tools explicitly "hook" the generated completion code, which in Talos' case can easily be done by outputting something like `compdef _talosctl talosctl`.
