### ISSUE TITLE
talosctl cluster create fails to create cluster

### ISSUE THREAD

**Issue by FotiadisM** [talos-systems/talos#3352]
### Description
Just trying to start a new docker cluster with `talosctl cluster create --wait` and it fails to start

```
waiting for etcd to be healthy: OK
waiting for bootkube to finish: OK
◳ ◲ waiting for apid to be ready: 1 error occurred:
    * 10.5.0.3: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.5.0.3:50000: connect: connection refused"
```

### Talos version:
```
Client:
	Tag:         v0.9.0
	SHA:         80b7b221
	Built:       
	Go version:  go1.15.9
	OS/Arch:     linux/amd64
```

**Comment by smira** [comment]
This doesn't look like a fatal error yet, talosctl waits for the service to start.

**Comment by FotiadisM** [comment]
I left it running and the context deadline exceed exceeds after a while

**Comment by smira** [comment]
There are usually two reasons for such long bootstrap times: resource constraints, e.g. disk space or RAM, and slow Internet.

Troubleshooting guide: https://www.talos.dev/docs/v0.9/guides/troubleshooting-control-plane/#what-is-a-control-plane-node

It might help to attach docker container logs.

If it's slow Internet, registry mirrors might help: https://www.talos.dev/docs/v0.9/guides/configuring-pull-through-cache/

**Comment by FotiadisM** [comment]
You were right, thanks for your help, and I am sorry for opening an issue quickly. The cause was low internet speeds.
It works fine when using registry mirrors and pre-pulling images.
I will close this issue now.
