### ISSUE TITLE
bug: DNS servers from DHCP with bond ignored

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#3354]
## Bug Report

It appears that DNS servers acquired via DHCP when using a bonded interface are being ignored, and the default 1.1.1.1 and 8.8.8.8 are used instead.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by bzub** [comment]
Similarly (maybe?) I've been seeing Talos taking over the `/etc/resolv.conf` that container runtimes provide when platform is `container`. I haven't been able to find a way to prevent Talos from putting its version of that file there.

**Comment by Ulexus** [comment]
@bzub That is most likely a different bug; more a missing feature, really.  Since Talos is responsible for setting up network things, it naturally does so, even when running inside a container.  I suspect this is simply a feature we need to add to allow Talos to use the container-runtime-injected `resolv.conf` when it is running in the `container` platform.

**Comment by smira** [comment]
that shouldn't be the problem at least with the network stack rewrite
