### ISSUE TITLE
bug: supplying `-e` with apply-config fails

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#3376]
## Bug Report

`talosctl -e X.X.X.X -n X.X.X.X apply-config --interactive --insecure`

When no talosconfig exists, and empty one will be created, and then this command will fail saying that talosconfig is empty.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by smira** [comment]
that's not a bug, `-e master -n new_node` is supposed to use to generate join config for the existing cluster, so it works as expected, but poorly documented?
