### ISSUE TITLE
Build with -race

### ISSUE THREAD

**Issue by AlekSi** [talos-systems/talos#3378]
Currently, we run unit tests with race detector enabled, but not integration tests or Talos components themselves. I propose we do run integration tests with`-race` (easy) and build a separate set of artifacts with `-race` (more work). That should help us uncover data races.

**Comment by smira** [comment]
I'm thinking we should at least support building dev versions with -race enabled. Need to make sure we can do that for machined which is exec'd from init

**Comment by smira** [comment]
Basic support is there, we have another item to track the environment vars
