### ISSUE TITLE
Machine role: worker vs join

### ISSUE THREAD

**Issue by AlekSi** [talos-systems/talos#3413]
Some parts of our code use the "worker" role, and some use "join", and it works in a confusing way.

Here, the documentation says "worker", but provides "join" as an example value: https://github.com/talos-systems/talos/blob/a43acb2150cadd78da51c41569b7f219b704f089/pkg/machinery/config/types/v1alpha1/v1alpha1_types.go#L480-L488

The only reference to "worker" is `talosctl gen config` command implementation: https://github.com/talos-systems/talos/blob/a43acb2150cadd78da51c41569b7f219b704f089/pkg/machinery/config/types/v1alpha1/generate/join.go#L34

This code accepts only "join", not "worker": https://github.com/talos-systems/talos/blob/a43acb2150cadd78da51c41569b7f219b704f089/pkg/machinery/config/types/v1alpha1/machine/machine.go#L9-L49

But the code above is not actually used :) The real work happens there, it accepts "join", "worker", "", "foobar": https://github.com/talos-systems/talos/blob/a43acb2150cadd78da51c41569b7f219b704f089/pkg/machinery/config/types/v1alpha1/v1alpha1_provider.go#L220-L230

Proposed solution:
* remove dead code;
* document "worker";
* mention "join" only briefly as deprecated alias;
* explicitly (not with `default:`) accept both "join" and "worker" for compatibility;
* generate warning for "join";
* generate warning for empty value;
* generate error any other value.

**Comment by andrewrynhard** [comment]
Ideally we should have used "worker". Something we can fix in the next versions of our config.

**Comment by smira** [comment]
I think we still should align the config around one or another term (be it `join` or `worker`)

**Comment by andrewrynhard** [comment]
> I think we still should align the config around one or another term (be it `join` or `worker`)

Agree.

**Comment by AlekSi** [comment]
Updated proposed solution

**Comment by masoudbahar** [comment]
If I may add to this topic, let me say two things:

1. Thank you for deprecating join, as it implies no clear association with a cluster role.
2. A new flag was added to v0.11, which uses join though; if I’m mistaken, it’s `—config-patch-join`; so, it should be updated to align with this change.

**Comment by andrewrynhard** [comment]
> If I may add to this topic, let me say two things:
> 
> 
> 
> 1. Thank you for deprecating join, as it implies no clear association with a cluster role.
> 
> 2. A new flag was added to v0.11, which uses join though; if I’m mistaken, it’s `—config-patch-join`; so, it should be updated to align with this change.

I think we haven't moved to this yet. I believe this is still just a proposal.

**Comment by masoudbahar** [comment]
I understand; my point was worker is a universally recognized term and cluster role, but join isn’t; and to not add to the use of join, in the latest version of Talos, if you’re planning to make this change.

**Comment by andrewrynhard** [comment]
> I understand; my point was worker is a universally recognized term and cluster role, but join isn’t; and to not add to the use of join, in the latest version of Talos, if you’re planning to make this change.

Yep, just wanted to be clear that we haven't "officially" deprecating join _yet_ 🙂 .

**Comment by AlekSi** [comment]
In 0.12, `--config-patch-join` still exists and works but is deprecated in favor of the new `--config-patch-worker`.
