### ISSUE TITLE
Compatible with ARM? 

### ISSUE THREAD

**Issue by unixfox** [talos-systems/talos#343]
Hello,

I didn't find any information about the compatibility with ARM. Is the project only compatible with x86_64?
I'm interested to use talos on a raspberry pi.

**Comment by andrewrynhard** [comment]
Hello @unixfox. Unfortunately ARM is not supported at the moment. But we aren't ruling it out. The bulk of the work would be creating an arm toolchain from https://github.com/autonomy/toolchain-musl. I think Talos would be a great for fit for things like this.

**Comment by andrewrynhard** [comment]
We are considering prioritizing this, but the only problem I see is that I don't have hardware to test this :D . Anyone willing to help out in any way here? I think I can supply an ARM toolchain, and get things to build but someone would have to run it.

**Comment by unixfox** [comment]
Scaleway provides ARM VPS for really cheap and AWS too but it's a bit more expensive.
I could help you with that and even provides you an SSH access to an older raspberry pi 1 but it would be quite slow on this :D.
Anyway it's up to you to know the best solution.

**Comment by andrewrynhard** [comment]
Forgot about the cloud somehow :D ... I started working on the arm toolchain tonight. Good progress so far but hit a bump.

**Comment by andrewrynhard** [comment]
Closing as we are handling this in v0.2.

**Comment by lwolf** [comment]
Does it mean current v0.2 could be tried with arm or there will be other ticker to track the progress?

**Comment by andrewrynhard** [comment]
@lwolf Sorry about that. I will create a ticket shortly to track the progress towards ARM support and be sure to ping you there.

**Comment by lwolf** [comment]
Thank you very much.
// looking forward to try it in multiarch setup.

**Comment by andrewrynhard** [comment]
For anyone wanting to see our progress towards this, please see: https://github.com/talos-systems/talos/issues/846

**Comment by andrewrynhard** [comment]
@unixfox @lwolf Next alpha release of Talos will have support for the Raspberry Pi 4.
