### ISSUE TITLE
kubelet certificate does not have entries from machine.certSANs

### ISSUE THREAD

**Issue by aceat64** [talos-systems/talos#3502]
## Bug Report
The TLS certificates used by the kubelet do not include `machine.certSANs` and only have the hostname of the node in the SAN.

### Description
I deployed metrics-server but it was unable to securely connect to the kubelet on my nodes due to a certificate error (see logs). I pulled the cert from the kubelet by connecting to it on port 10250 and noticed it only has one SAN, the hostname of the node (metrics-server is only using the IP). When I first deployed the nodes I didn't have `machine.certSANs` set, I changed that and did an apply but the cert did not get regenerated. Next I tried an upgrade of the node, this did cause the certificate to be regenerated (confirmed by the "valid from" updating to today's date). However, the SAN field still only contained the hostname of the node.

### Logs
From metrics-server:
```
unable to fully scrape metrics from node worker-3: unable to fetch metrics from node worker-3: Get "https://192.168.57.18:10250
 /stats/summary?only_cpu_and_memory=true": x509: cannot validate certificate for 192.168.57.18 because it doesn't contain any IP SANs
```

### Environment

- Talos version: v0.10.0-beta.0
- Kubernetes version: v1.21.0
- Platform: arm64

**Comment by andrewrynhard** [comment]
@smira this seems simple enough to add to 0.11? Or if it is a bug maybe 0.10?

**Comment by aceat64** [comment]
I should mention for anyone else having this issue, there is a workaround. I had to configure metrics-server with `--kubelet-insecure-tls` so it would ignore the cert validation.

**Comment by alex1989hu** [comment]
Hello @aceat64, this is not a bug of Talos. It is more related how does Kubernetes handle certificates, especially kubelet serving certificates. I see that my repository is shared in the referenced issue.

Of course, you can do it manually. Once you configured Kubernetes API Server, the certificates in [Certificate Signing Request Objects](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/) will contain all necessary fields to have proper kubelet serving certificate and finally you don't have to use `--kubelet-insecure-tls` option in `metrics-sever`.

/cc @andrewrynhard

**Comment by aceat64** [comment]
Good to know! I'll go ahead and close this issue for now and try out your [kubelet-serving-cert-approver](https://github.com/alex1989hu/kubelet-serving-cert-approver/) when I get a chance.
