### ISSUE TITLE
Validate the provided config

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#358]
We should provide useful feedback to users about the configuration file they supply. The yaml marshal/unmarshal errors are not all that helpful. We can provide a command to validate one locally, and we should also validate it in the `init`.

See #356  and #357.

**Comment by bradbeam** [comment]
`osinstall validate -u <path to userdata either local or http>` might be helpful in this case. It doesnt do any sort of more helpful messaging, but at least provides a way to determine if the userdata is valid.

**Comment by andrewrynhard** [comment]
Closed by #593.
