### ISSUE TITLE
Kernel reports clock to be unsynced

### ISSUE THREAD

**Issue by jonkerj** [talos-systems/talos#3582]
### Description
The general problem is that although Talos is taking care of keeping the system clock in sync with NTP peers, the kernel considers it being unsynced, because of timex status bit `STA_UNSYNC` being set. This bit is cleared by Talos, when time is adjusted using `adjtimex()`, but it seems to get auto-set after 1s. Also, when Talos sets the time using `settime()`, the kernel sets the bit as well.

This affects observability of the nodes sync status using tools like prometheus-node-exporter (metric `node_timex_sync_status` is consistently 0 in my case).

### Logs
not really applicable, but here is some proof NTP is doing its work:
```
9ka-w-1: 2021/05/06 08:16:02  time.SyncController: synchronized RTC with system clock
9ka-w-1: 2021/05/06 08:26:28  time.SyncController: adjusting time by 36.851404ms via 87.249.121.122, state TIME_OK, status STA_PLL | STA_NANO
9ka-w-1: 2021/05/06 08:32:58  time.SyncController: adjusting time by 22.849319ms via 87.249.121.122, state TIME_OK, status STA_NANO | STA_PLL
9ka-w-1: 2021/05/06 08:42:35  time.SyncController: adjusting time by -69.222376ms via 87.249.121.122, state TIME_OK, status STA_NANO | STA_PLL
9ka-w-1: 2021/05/06 08:52:34  time.SyncController: setting time to 2021-05-06 08:52:35.145987688 +0000 UTC m=+2202.010626531 via 87.249.121.122
9ka-w-1: 2021/05/06 08:52:35  time.SyncController: synchronized RTC with system clock
9ka-w-1: 2021/05/06 08:53:12  time.SyncController: adjusting time by 15.811782ms via 87.249.121.122, state TIME_OK, status STA_NANO | STA_PLL
9ka-w-1: 2021/05/06 09:08:45  time.SyncController: setting time to 2021-05-06 09:08:45.427246984 +0000 UTC m=+3172.039830608 via 87.249.121.122
```

### Environment

- Talos version: v0.10.0
- Kubernetes version: v1.21.0
- Platform: metal/kvm

**Comment by jonkerj** [comment]
I did a little experiment, wrote some Go that polls the timex status every 50ms, which outputs this:
```
root@9ka-w-1:/# /tmp/main
2021/05/06 10:24:40 sync state changed from false to true
2021/05/06 10:24:41 sync state changed from true to false
2021/05/06 10:27:05 sync state changed from false to true
2021/05/06 10:27:06 sync state changed from true to false
2021/05/06 10:29:08 sync state changed from false to true
2021/05/06 10:29:09 sync state changed from true to false
2021/05/06 10:41:35 sync state changed from false to true
2021/05/06 10:41:36 sync state changed from true to false
2021/05/06 10:43:33 sync state changed from false to true
2021/05/06 10:43:34 sync state changed from true to false
2021/05/06 10:53:18 sync state changed from false to true
2021/05/06 10:53:19 sync state changed from true to false
```
At the same time, Talos logs:
```
9ka-w-1: 2021/05/06 10:24:40  time.SyncController: adjusting time by -33.463884ms via 87.249.121.122, state TIME_OK, status STA_PLL | STA_NANO
9ka-w-1: 2021/05/06 10:27:05  time.SyncController: adjusting time by 32.817607ms via 87.249.121.122, state TIME_OK, status STA_NANO | STA_PLL
9ka-w-1: 2021/05/06 10:29:08  time.SyncController: adjusting time by -3.744381ms via 87.249.121.122, state TIME_OK, status STA_NANO | STA_PLL
9ka-w-1: 2021/05/06 10:41:35  time.SyncController: adjusting time by -755.698µs via 87.249.121.122, state TIME_OK, status STA_PLL | STA_NANO
9ka-w-1: 2021/05/06 10:43:33  time.SyncController: adjusting time by 601.52µs via 87.249.121.122, state TIME_OK, status STA_NANO | STA_PLL
9ka-w-1: 2021/05/06 10:53:18  time.SyncController: adjusting time by 139.907µs via 87.249.121.122, state TIME_OK, status STA_PLL | STA_NANO
```

This gives me the idea that the kernel expires timex sync status after 1s.

**Comment by smira** [comment]
The reason is that (most probably) we don't set properly `ADJ_TIMECONST` in `adjtimex` call.

For the reference, see `systemd` code: https://cgit.freedesktop.org/systemd/systemd/tree/src/timesync/timesyncd-manager.c?id=v217#n293

This requires major rewrite of the sync code to propagate poll interval to the `adjtimex` call, plus we can use `adjtimex` to set time as well.

**Comment by jonkerj** [comment]
I think [this kernel code](https://github.com/torvalds/linux/blob/master/kernel/time/ntp.c#L457-L462) could be responsible for re-setting the `STA_UNSYNC` bit every second. Maybe fiddling with `maxerror` already solves it.

**Comment by jonkerj** [comment]
Could be completely wrong, but if you don't touch `maxerror`, it's initialized as `NTP_PHASE_LIMIT` (16M). And the function `second_overflow(..)` has the following code:
```c
/* Bump the maxerror field */
time_maxerror += MAXFREQ / NSEC_PER_USEC;
if (time_maxerror > NTP_PHASE_LIMIT) {
	time_maxerror = NTP_PHASE_LIMIT;
	time_status |= STA_UNSYNC;
}
```
So, not setting it could cause it to set `STA_UNSYNC` every second overflow. 

systemd-timesyncd [explicitly initializes `maxerror` to zero](https://cgit.freedesktop.org/systemd/systemd/tree/src/timesync/timesyncd-manager.c?id=v217#n341), causing above code (if I understand everything correct) to bump `maxerror` with 500 every second.
