### ISSUE TITLE
MTU setting for VLAN interfaces

### ISSUE THREAD

**Issue by dln** [talos-systems/talos#3600]
## Feature Request

It'd be nice to be able to set the MTU for VLAN interfaces, just as regular ones - maybe even have all the Device settings even for the VLAN ones. I noticed that MTU ended up at 1500 for all VLAN interfaces on a bonded nic with MTU 9000.

**Comment by andrewrynhard** [comment]
Nice catch. Seems easy enough for 0.11 @smira ?
