### ISSUE TITLE
Control plane shared VIP on a VLAN interface.

### ISSUE THREAD

**Issue by dln** [talos-systems/talos#3601]
## Feature Request

I just ran into this on a lab cluster, where I'd like to have the shared vip on a vlan. Right now its just possible to put it on a "main" interface, though.

I'm not sure what we'd like the UX to be like though, since it doesn't make much sense to have more than one (?). Maybe move the control plane vip config outside the interface config(s) and keep it separate?

**Comment by sergelogvinov** [comment]
I'm no sure.

Hezner cloud for example.
They have a native vlan for public network. And any other vlans for private subnets.
May be @dln wants to make a private subnet to the k8s and keep a public ip as EXTERNAL-IP node.

This is very common case (network solutions) on many dedicated cloud providers.

**Comment by Ulexus** [comment]
That's perfectly fine.  The VIP is bound to the interface you specify; there is no problem with multiple interfaces, physical or logical.

**Comment by smira** [comment]
The problem is that Talos machine configuration doesn't support VIPs on VLANs, only on the top-level interfaces
