### ISSUE TITLE
dm-crypt and options parameters

### ISSUE THREAD

**Issue by sergelogvinov** [talos-systems/talos#3606]
## Feature Request

Add capabilities to set dm-crypt performance flags.
Sometimes on special equipments we needs to change the default performance flags in dm-crypt module.

For instance etcd makes many IO with small block size. Cloudflare research can help to solve this.

### Description

Based on https://blog.cloudflare.com/speeding-up-linux-disk-encryption
In my test case, I used the KVM virtual machine 2vCPU-4RAM 

1. Check aes optimisation - already done [PR-275](https://github.com/talos-systems/pkgs/pull/275)

Current talos kernel v0.10.1 results:
```
# grep -A 11 'xts(aes)' /proc/crypto
name         : xts(aes)
driver       : xts(ecb(aes-generic))
module       : kernel
priority     : 100
refcnt       : 3
selftest     : passed
internal     : no
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 32

# fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=fiotest --filename=testfio --bs=4k --iodepth=64 --size=4G --readwrite=randrw --rwmixread=75

'''
   READ: bw=136MiB/s (143MB/s), 136MiB/s-136MiB/s (143MB/s-143MB/s), io=3070MiB (3219MB), run=22499-22499msec
  WRITE: bw=45.6MiB/s (47.8MB/s), 45.6MiB/s-45.6MiB/s (47.8MB/s-47.8MB/s), io=1026MiB (1076MB), run=22499-22499msec
```

New future kernel results:
```
# grep -A 11 'xts(aes)' /proc/crypto
name         : __xts(aes)
driver       : cryptd(__xts-aes-aesni)
module       : kernel
priority     : 451
refcnt       : 3
selftest     : passed
internal     : yes
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 32
max keysize  : 64
--
name         : xts(aes)
driver       : xts-aes-aesni
module       : kernel
priority     : 401
refcnt       : 3
selftest     : passed
internal     : no
type         : skcipher
async        : yes
blocksize    : 16
min keysize  : 32
max keysize  : 64
--
name         : __xts(aes)
driver       : __xts-aes-aesni
module       : kernel
priority     : 401
refcnt       : 3
selftest     : passed
internal     : yes
type         : skcipher
async        : no
blocksize    : 16
min keysize  : 32
max keysize  : 64

# fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=fiotest --filename=testfio --bs=4k --iodepth=64 --size=4G --readwrite=randrw --rwmixread=75

...
   READ: bw=225MiB/s (236MB/s), 225MiB/s-225MiB/s (236MB/s-236MB/s), io=3070MiB (3219MB), run=13669-13669msec
  WRITE: bw=75.1MiB/s (78.7MB/s), 75.1MiB/s-75.1MiB/s (78.7MB/s-78.7MB/s), io=1026MiB (1076MB), run=13669-13669msec

```

About two time performance. Very well.

2. Disable queues in crypto api

```
# dmsetup table /dev/mapper/sda6-encrypted --showkeys
0 66047933 crypt aes-xts-plain64 :64:logon:cryptsetup:f6ce1681-00d4-4fd4-ac81-3e8d0ea5fff1-d0 0 8:6 32768

# fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=fiotest --filename=testfio --bs=4k --iodepth=64 --size=4G --readwrite=randrw --rwmixread=75

...
   READ: bw=226MiB/s (237MB/s), 226MiB/s-226MiB/s (237MB/s-237MB/s), io=3070MiB (3219MB), run=13587-13587msec
  WRITE: bw=75.5MiB/s (79.2MB/s), 75.5MiB/s-75.5MiB/s (79.2MB/s-79.2MB/s), io=1026MiB (1076MB), run=13587-13587msec

### Set feature flags
# cryptsetup refresh --perf-no_read_workqueue --perf-no_write_workqueue sda6-encrypted
# dmsetup table /dev/mapper/sda6-encrypted --showkeys

0 66047933 crypt aes-xts-plain64 :64:logon:cryptsetup:f6ce1681-00d4-4fd4-ac81-3e8d0ea5fff1-d0 0 8:6 32768 2 no_read_workqueue no_write_workqueue

# fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=fiotest --filename=testfio --bs=4k --iodepth=64 --size=4G --readwrite=randrw --rwmixread=75

...
   READ: bw=251MiB/s (264MB/s), 251MiB/s-251MiB/s (264MB/s-264MB/s), io=3070MiB (3219MB), run=12208-12208msec
  WRITE: bw=84.0MiB/s (88.1MB/s), 84.0MiB/s-84.0MiB/s (88.1MB/s-88.1MB/s), io=1026MiB (1076MB), run=12208-12208msec
```

The result is not too much that I expected, but anyway it is also add some performance. After reboot the kernel lost that flags.

So, what do you think? Is it possible to add that [parameters](https://www.kernel.org/doc/html/latest/admin-guide/device-mapper/dm-crypt.html) to the talos machineconfig?

**Comment by smira** [comment]
I like the idea to allow to customize `dm-crypt` for performance

**Comment by sergelogvinov** [comment]
As alternative AES-NI witch does not have on all CPUs (raspberry pi 4 for instance) we can use adiantum cipher

documentation witch I use
* https://security.googleblog.com/2019/02/introducing-adiantum-encryption-for.html
* https://source.android.com/security/encryption/adiantum
* https://www.raspberrypi.org/forums/viewtopic.php?t=252980
* https://patchwork.kernel.org/project/linux-crypto/cover/20181205062005.27727-1-ebiggers@kernel.org/


My results

```
# Tests are approximate using memory only (no storage IO).
aes-xts                       256b      3209.5 MiB/s      3282.7 MiB/s
xchacha12,aes-adiantum        256b      1691.9 MiB/s      1734.0 MiB/s
```

kernel changes - https://github.com/talos-systems/pkgs/pull/290

**Comment by sergelogvinov** [comment]
So what we have.

* chiper: [aes-xts-plain64,xchacha12,aes-adiantum,xchacha20,aes-adiantum] (ENUM?)
* key-size: 256,512 (integer)
* sector-size: 512,4096,8192 (integer) Best size depends on disk (hdd,ssd,hvme), very hard to define automatically best value. Many vendors' show fake information. 
* perf options: [no_read_workqueue,no_write_workqueue,same_cpu_crypt] (ENUM?)


Default params

aes-xts-plain64:
* key-size = 512
* sector-size = 4096 (SSD/NVME)

xchacha12,aes-adiantum-plain64/xchacha20,aes-adiantum-plain64:
* key-size = 256
* sector-size = 4096 (SSD/NVME)

machine-config proposal:
```
machine:
  systemDiskEncryption:
    state:
      provider: luks2
      cipher: aes-xts-plain64
      keySize: 512
      blockSize: 4096
      options:
        - no_read_workqueue
        - no_write_workqueue
      keys:
        - nodeID: {}
          slot: 0
```
