### ISSUE TITLE
failure to to partition device

### ISSUE THREAD

**Issue by imle** [talos-systems/talos#3609]
### Description

Made an [issue in go-blockdevice](https://github.com/talos-systems/go-blockdevice/issues/37), but I realize that may not be the most appropriate place.

When trying to install directly on metal, I was unable to successfully partition the target install media unless the drive was very large.

Method:
1. Load SD card with talos.iso (used balenaEtcher)
2. Created a config following the [digital-rebar guide](https://www.talos.dev/docs/v0.10/bare-metal-platforms/digital-rebar/)
3. Apply config following the maintenance mode command in talos console output
4. Try all of the following:
   * Try to overwrite the SD card (32 GB) with no additional drives in the system
      * Experience the exact error message below (in Logs)
   * Try with a drive of 120 GB using the SD card to do the initial boot
      * Experience the exact error message below (in Logs)
      * Ensured that the drive's DEV path was specified in `machine.install.disk`
   * Try with a drive of 1 TB using the SD card to do the initial boot
      * Talos installs with no issues and can be adopted into a k8s cluster

### Logs
```
failed to partition device: requested partition size 104857600, available is 72879104 (31978496 too many bytes)
```

### Environment

- Talos version: v0.10.1
- Kubernetes version: NA
- Platform: Metal
- Server: HP Proliant DL380 G7

**Comment by smira** [comment]
Can you post please more logs before that message to understand the context?

**Comment by imle** [comment]
@smira is there a way to get talos to output over a serial port? I can possibly post some images otherwise.

**Comment by smira** [comment]
you can attach the image to this issue (simply pasting an image works on GitHub)

Talos by default enables serial console `ttyS0` on bare metal.

**Comment by imle** [comment]
Perfect, I will do so as soon as I run the process through again.

**Comment by imle** [comment]
I tried to capture the serial output but was unable to get anything from it.

![Screen Shot 2021-05-14 at 9 14 27 PM](https://user-images.githubusercontent.com/4809109/118343914-9f747d00-b4f9-11eb-8989-2b30109a280f.png)
![Screen Shot 2021-05-14 at 9 14 52 PM](https://user-images.githubusercontent.com/4809109/118343912-9edbe680-b4f9-11eb-8183-8986df60bc34.png)
![Screen Shot 2021-05-14 at 9 15 17 PM](https://user-images.githubusercontent.com/4809109/118343913-9f747d00-b4f9-11eb-9142-473222fffe26.png)
![Screen Shot 2021-05-14 at 9 15 41 PM](https://user-images.githubusercontent.com/4809109/118343915-a00d1380-b4f9-11eb-9993-07abec7193e6.png)
![Screen Shot 2021-05-14 at 9 15 46 PM](https://user-images.githubusercontent.com/4809109/118343917-a0a5aa00-b4f9-11eb-9547-47bf5a8ffefe.png)

**Comment by imle** [comment]
Ignoring the additional logs of me attaching a USB, it also fails to shut down gracefully when it reaches this state.
![PXL_20210515_012917714](https://user-images.githubusercontent.com/4809109/118344325-ad2b0200-b4fb-11eb-8a56-3c1307e3b9a2.jpg)

**Comment by imle** [comment]
I am beginning to think this is something to do with the disks or the machine.

During a few more attempts to get talos installed, I was experiencing some really random disk availability.

Once I finally got the disk to show up, it ended up with this error:
`Error: expected partition checksum of 2874462854, got 1899812701`

And ended in the same way by printing the help text for the installer container.

**Comment by Ulexus** [comment]
I don't know what `/dev/sda` is on that system, but it looks like your SD card is coming up as `/dev/sdb`

**Comment by Ulexus** [comment]
Never mind; you meant that we should ignore that USB stick.

**Comment by imle** [comment]
Yeah, I do not currently have another server to test this on, but my attempt to install with the same disk but through a virtual machine (using almost the exact same method) was successful. So once I get the replacement for this machine I will update the ticket with whether or not the server was to blame.

**Comment by imle** [comment]
So after being able to install this on a different server, with the same disk, in the exact same way I tried with the server mentioned here, I am chalking this up to hardware issues.

**Comment by bcspragu** [comment]
For what it's worth, I hit this exact issue (`failed to partition device: ... too many bytes`) setting up a cluster and partitioning a fresh-out-of-the-box disk. It failed twice in a row, then I opened up a live CD and ran `wipefs -a /dev/<device> && mkfs -t ext4 /dev/<device>` and it succeeded on the subsequent attempt.

No idea what the underlying issue is, or if formatting is even necessary, but that solved it for me.
