### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by unixfox** [talos-systems/talos#375]
Currently the documentation lacks of complete guides for new up-comers.

Here is a list of some ideas to implement on the docs:
- [ ] Improve the worker documentation
- [ ] A one-page guide to quickly setup a "dev"/test environment of Talos on `virtualbox` (?).
- [ ] Retrieve the memory and cpu usage of each node/pod with `osctl`
- [ ] Retrieve the memory and cpu usage of each node/pod with `kubectl` (with explaining how to correctly deploying the metrics server on talos)
- [ ] A friendly home page with key points of the documentation [just like the Kubernetes doc](https://kubernetes.io/docs/home/) (?)
- [ ] Improve the KVM guide
   * [ ] Improve with commands that actually work for most setup (`image.raw`)
- [ ] Improve the AWS EC2 guide (need autonomy/talos#351    to have an easier guide):
  * [ ] How to specify the user data
  * [ ] Explain how to generate the AWS EC2 credentials (optional if the AWS AMI are publicly available)
  * [ ] How to set up the networking (static IPs with elastic interface)
- [ ] Document the arguments of the command `osctl` with examples (could similar to a man on linux)
- [ ] How to monitor talos with Prometheus (or others monitoring tools)
- [ ] Document random crng init and the `random.trust_cpu=on` option
- [ ] Add a reference to releases page and the `osctl` binary.

**Comment by andrewrynhard** [comment]
@unixfox Thanks for taking the time to go through this process. These are some valuable notes on doc improvements. One of our main goals at the moment is to make the barrier to entry as low as possible. This will be very helpful with that.

**Comment by andrewrynhard** [comment]
Looks like we could do something like this for the man pages: https://github.com/spf13/cobra/blob/master/doc/man_docs.md
