### ISSUE TITLE
Will Talos self-update?

### ISSUE THREAD

**Issue by activeshadow** [talos-systems/talos#383]
Very cool project! I was excited to see a Go application being used for PID 1. :smiley:

I didn't see any (obvious) documentation about Talos self-updating. Is the expectation that new instances will be created when new versions of Talos comes out, or will Talos self-update its core components? I have a potential use case that involves remote deployment on hardware, so I don't want to consider Talos for this use case if the plan isn't for it to self-update.

My apologies if GitHub Issues isn't the best place to ask questions like this. I didn't see any details about a Talos community (chat, email group, etc) for asking general questions, so I figured I'd just ask here.

**Comment by andrewrynhard** [comment]
@activeshadow First of all, thanks for the interest! The plan is to self-update. We have a few things to implement before we get there, but I don't think its too far off. See #257. We have a slack we can invite you to. I need to add it to the README, but I would need you to email me so I can send an invite.

**Comment by andrewrynhard** [comment]
@activeshadow We have started work on upgrades, see #623. This should allow us to start thinking about how self-upgrades might work. If you still interested, we would be happy to hear your use case some more to make sure we are doing it right.

**Comment by andrewrynhard** [comment]
Closing as we have decided to tackle this in v0.2.
