### ISSUE TITLE
Talos rbac os:etcd:backup certs

### ISSUE THREAD

**Issue by sergelogvinov** [talos-systems/talos#3831]
## Feature Request

Store certs **os:etcd:backup** to the Kubernetes secrets (kube-system namespace?).

### Description

It helps to make the automation easily (For example - cronjob backups to s3)

**Comment by andrewrynhard** [comment]
I remember kubeadm or maybe some other project being explicitly against this. Storing the keys to the kingdom in cluster is likely to be held against us by security engineers.

**Comment by sergelogvinov** [comment]
Definitely yes,  this is a bad idea )

**Comment by andrewrynhard** [comment]
> I think we should in general look into a way to do auth via K8s RBAC to Talos API. So if somone deploys properly annotated pod, it should have access to Talos API with some role.
> 
> 
> 
> E.g. Talos API might accept service token from K8s.

I could see this for sure.
