### ISSUE TITLE
Talos refuses to boot with disabled IPv6

### ISSUE THREAD

**Issue by rgl** [talos-systems/talos#3847]
### Description

My network is not ready for IPv6, so I've disabled IPv6 with the kernel command line argument `ipv6.disable=1`, but Talos refuses to boot because the `writeRequiredSysctls` step fails due to missing `/proc/sys/net/ipv6/config/default/forwarding`:

![image](https://user-images.githubusercontent.com/43356/123521995-20ef2b80-d6b2-11eb-92ab-302379f39fd0.png)

### Logs

N/A

### Environment

- Talos version: v0.11.0-alpha.2
- Kubernetes version: None yet. Din't pass the boot phase yet.
- Platform: "Metal" (its actually using KVM and Matchbox).

**Comment by alex1989hu** [comment]
I think the root cause is the same: <https://github.com/talos-systems/talos/issues/3919>

**Comment by smira** [comment]
I feel these issues are a bit different, but all around IPv6. I'll take a look at both of these.
