### ISSUE TITLE
Failed to pull image 

### ISSUE THREAD

**Issue by liangyuanpeng** [talos-systems/talos#3892]
## Bug Report

Failed to pull image ` gcr.lank8s.cn/etcd-development/etcd:v3.4.15`

### Description  

I have to try reproduce it and got nothing.  

1. docker pull gcr.lank8s.cn/etcd-development/etcd:v3.4.15.  [OK]
2. ctr images pull gcr.lank8s.cn/etcd-development/etcd:v3.4.15  [OK]

And gcr.lank8s.cn just is a docker registry proxy cache.

### Logs  

![image](https://user-images.githubusercontent.com/28711504/124552107-ac607d80-de65-11eb-8e76-755365f73db7.png)

### Environment

- Talos version: v0.10.4
- Kubernetes version: v1.21.1
- Platform:  VirtualBox  for talos-amd64.iso

Thanks any help.

**Comment by smira** [comment]
Could it be that your node is out of disk space?

**Comment by liangyuanpeng** [comment]
> Could it be that your node is out of disk space?

Thanks for your reply and i have 8GB disk space...

**Comment by smira** [comment]
I tried using `gcr.lank8s.cn/etcd-development/etcd:v3.4.15` as etcd image in my test environment with Talos, and it worked just fine, so I assume, it's not a problem with Talos itself (tested with 0.11-beta.2).

**Comment by liangyuanpeng** [comment]
Thanks, I juse use `--registry-mirror gcr.io=https://gcr.lank8s.cn` param for this issue and it's can pull image. 

Now, i just get the error. 127.0.0.1:10248 connection refused. If talos work for me, i will update it.
