### ISSUE TITLE
Kubernetes 1.22

### ISSUE THREAD

**Issue by AlekSi** [talos-systems/talos#3967]
We should upgrade to k8s 1.22. Known problems that were fixed:

# DynamicKubeletConfig feature gate

```
"Failed to validate kubelet flags" err="the DynamicKubeletConfig feature gate must be enabled in order to use the --dynamic-config-dir flag"
Flag --cni-conf-dir has been deprecated, will be removed along with dockershim.
Flag --dynamic-config-dir has been deprecated, Feature DynamicKubeletConfig is deprecated in 1.22 and will not move to GA. It is planned to be removed from Kubernetes in the version 1.23. Please use alternative ways to update kubelet configuration.
```

~For 1.22, we enabled the `DynamicKubeletConfig` feature gate by default (and correctly merge it with `extraArgs`). We should find a better solution that would work for 1.23 that will remove DynamicKubeletConfig completely.~ We were not really using it, removed. See also #3997.

# `--audit-log-path=-`

https://github.com/kubernetes/kubernetes/pull/95387 broke `--audit-log-path=-` support. It was fixed at https://github.com/kubernetes/kubernetes/issues/103845.

---

https://github.com/talos-systems/talos/pull/3935

**Comment by sergelogvinov** [comment]
Set DynamicKubeletConfig feature by default is bad idea. DynamicKubeletConfig - this is security hole. 
Bette to use talos api to configure the KubeletConfig file (few parameters not all).

**Comment by andrewrynhard** [comment]
Let's remove it.

**Comment by AlekSi** [comment]
https://github.com/talos-systems/talos/pull/3935 hacks around both these problems to show that there are no others.
