### ISSUE TITLE
/etc/os-release HOME_URL is broken

### ISSUE THREAD

**Issue by rgl** [talos-systems/talos#3968]
### Description

The `/etc/os-release` `HOME_URL` is https://docs.talos-systems.com/ and that URL is broken:

![image](https://user-images.githubusercontent.com/43356/126283722-7f7c5fab-4c7d-4d81-bf5c-7bca83d8058a.png)

### Environment

- Talos version: v0.11.2

**Comment by AlekSi** [comment]
It looks like only one line should be updated: https://github.com/talos-systems/talos/blob/c780821d0b8fda0b3ef6d33b63b595e40970a897/internal/app/machined/pkg/runtime/v1alpha1/v1alpha1_sequencer_tasks.go#L309

Would you send a PR?

**Comment by rgl** [comment]
Should the address be https://www.talos.dev?

**Comment by AlekSi** [comment]
Yes

**Comment by rsmitty** [comment]
Gong to close since that PR was merged. Thanks @rgl!
