### ISSUE TITLE
kernel: support multiple console= args

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#3972]
## Bug Report

Some time ago, the kernel commandline parameters parsing and assembly were made more optimised and better validated.  However, in so doing, we lost the ability to specify multiple `console=` arguments.  Instead, Talos' installer now only allows one, and it silently elides any additional such arguments.

While it is true that the kernel only supports one of each _type_ of console (video and serial), it _does_ support _both_ kinds.  Thus, we should allow a video _and_ a serial console option.

**Comment by smira** [comment]
bug in in the `go-procfs`, `cmdline.AppendAll` with AlwaysOverwrite set to console

not only it overwrites previous platform defaults, it also overwrites settings from the cmdline

**Comment by smira** [comment]
@Ulexus I actually verified that the console argument gets set correctly, including multiple values:

```
talos.platform=metal talos.platform=metal talos.config=http://172.20.0.1:45943/config.yaml console=ttyS0 console=tty0 init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 random.trust_cpu=on printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 reboot=k panic=1 talos.shutdown=halt initrd=/B/initramfs.xz
```

So I'm not sure what the bug is. The only caveat is that `console` overrides anything in the platform config, so both console arguments should be set in the machine config if they both are desired. Settings just one removes platform defaults and puts new value.

**Comment by Ulexus** [comment]
Perhaps this was already fixed somewhere along the line, then?  I'll try it on my DC machines, which definitely had this issue before.

**Comment by Ulexus** [comment]
Confirmed.  Seems to be working now.
