### ISSUE TITLE
Document interface configuration merging behavior

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#4009]
Since an `interface` in our config only accepts one `cidr`, it can be confusing when a user wants to add more than one address to an interface. The way in which this is done is by adding another entry to the list for the same interface. Talos will merge all these settings. We should document this behavior.

**Comment by smira** [comment]
I would rather implement #3940 and document that

**Comment by andrewrynhard** [comment]
> I would rather implement #3940 and document that

Agree

**Comment by smira** [comment]
as #3940 was implemented, I think we should close this
