### ISSUE TITLE
Etcd advertise address

### ISSUE THREAD

**Issue by sergelogvinov** [talos-systems/talos#4107]
Now Talos search all IP addresses on local machine and get first one to set advertise address for the etcd node.
It will be better to make possible change this address.

https://github.com/talos-systems/talos/blob/576ba195784abf275256c861d5f811ab1f7b1102/internal/app/machined/pkg/system/services/etcd.go#L667-L680

Proposal:
```yaml
cluster:
  etcd:
    advAddress: 10.10.1.1
```

where advAddress can be:
* ExternalIP (string)  - external ip received from meta server cloud provider
* InternalIP (string) -  first ip =! ExternalIP (like current algorithm do)
* a.b.c.d (IP address v4 or v6)

**Comment by andrewrynhard** [comment]
If it can be set using `extraArgs`, that would be ideal IMHO.

**Comment by andrewrynhard** [comment]
In other words, just check if the `etcd` arg is present in `extraArgs` and then skip `primaryAndListenAddresses()`.

**Comment by sergelogvinov** [comment]
Good idea, but in some clouds you cannot figure out ExternalIP/InternalIP before create. 

ExternalIP/InternalIP -- this is cloud specific dynamic parameter.

**Comment by sergelogvinov** [comment]
Good solution for protection etcd daemon, thanks.

But I have another case here.

[ExIP] <-> [DNAT] <-> [VM-Local-ip]

We have instance with only local IP. Cloud provider makes DNAT from external IP to the local IP. 
In this case instance does not have ExIP on local interface and Etcd adv-address will be always local IP.

If you have multi-cloud/multi-region installation the controlplane nodes cannot reach each other... (local networks is not linked)

**Comment by andrewrynhard** [comment]
> Good solution for protection etcd daemon, thanks.
> 
> But I have another case here.
> 
> [ExIP] <-> [DNAT] <-> [VM-Local-ip]
> 
> We have instance with only local IP. Cloud provider makes DNAT from external IP to the local IP.
> In this case instance does not have ExIP on local interface and Etcd adv-address will be always local IP.
> 
> If you have multi-cloud/multi-region installation the controlplane nodes cannot reach each other... (local networks is not linked)

Sounds like another issue could be made to track this.
