### ISSUE TITLE
duplicated cgroup2 /proc/mounts entry

### ISSUE THREAD

**Issue by rgl** [talos-systems/talos#4108]
### Description

`talosctl -n cp1 read /proc/mounts | sort` shows `cgroup /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime 0 0` twice.

that's the only duplicated line in the mounts file.

I'm not sure if this is really a problem, but it might be worth investigating.

BTW, the cgroup2 mount flags on debian 11 also have the `nsdelegate,memory_recursiveprot` flags:

```
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot 0 0
```

And by https://github.com/talos-systems/talos/blob/b9d04928d960f9d576671c6f3511cf242ff31cb7/internal/pkg/mount/cgroups.go#L16 it seems to infer that talos should also have them. this might be worth investigating.

### Environment

- Talos version: 0.12.0-beta.0
- Kubernetes version: 1.22.0
- Platform: amd64

**Comment by sergelogvinov** [comment]
Thank you for notice that.

Talos runs kubelet in the container, it runs pods using runc. Runc mount cgroup... https://github.com/opencontainers/runc/issues/2158

Cilium also can remount cgroup, and remove flags nsdelegate,memory_recursiveprot

**Comment by rgl** [comment]
Ah so its normal to have these mounts. Thanks for the details!
