### ISSUE TITLE
Automatically change node type init -> controlplane

### ISSUE THREAD

**Issue by sergelogvinov** [talos-systems/talos#4178]
## Feature Request

After finish bootstrap node first node (init type) Talos should change automatically type to controlplane.
Sometimes people forget do it. 

In some reason we need to clean EPHEMERAL partition... 
So if you have many controlplane nodes and load balancer on top, the clean init-node give you split brain.
LB checks will pass, and some nodes (kubelet) reconnect to clean Kubernetes cluster.

**Comment by andrewrynhard** [comment]
We thought about this, but we opted against it since we a goal of ours is to _not_ modify the config out from underneath the user.

**Comment by smira** [comment]
We would like to make sure there's no `init` node type in the first place, or we have ideas for automatic bootstrap, but that approach is limited.

**Comment by sergelogvinov** [comment]
Life time of init node a few minutes. Some one can forget to change this "state" after bootstrap node. 
This thing can break the cluster. If you don't want to change anything automatically let's deprecate it.

This very dangerous type of node.

**Comment by smira** [comment]
Actually `init` nodes are now deprecated, and not used by default in the Talos docs and flows

**Comment by sergelogvinov** [comment]
Nice, thank you!
