### ISSUE TITLE
Cilium on rp4 fails to start

### ISSUE THREAD

**Issue by githubcdr** [talos-systems/talos#4194]
## Bug Report

Cilium deploy does not work on ARM platform

### Description

Cilium on rp4 is installed with wrong architecture

### Logs

wrong exec format

### Environment

Client:
        Tag:         v0.12.0
        SHA:         ff9681a7
        Built:
        Go version:  go1.16.7
        OS/Arch:     linux/amd64
Server:
        NODE:        10.18.24.106
        Tag:         v0.12.0
        SHA:         ff9681a7
        Built:
        Go version:  go1.16.7
        OS/Arch:     linux/arm64
        Enabled:     RBAC

**Comment by smira** [comment]
There's nothing related to Talos here, usually this error means that Cilium doesn't support arm64.

**Comment by xUnholy** [comment]
You'll want to specify "none" when selecting the CNI in your setup during Talos, then you'll want to use the Cilium v1.10+ which includes the arm64 image post this version. The exact values and steps I use are captured here if you wish to look @githubcdr https://github.com/xUnholy/k8s-gitops/tree/main/k8s/namespaces/base/kube-system/cilium/install

Just remember to change the respective values for IPs/CIDRs to your desired ones and you will have a working Cilium CNI running on Talos. 🙏

**Comment by smira** [comment]
see also https://github.com/cilium/cilium/issues/16771

**Comment by smira** [comment]
And https://github.com/cilium/cilium/issues/17883
