### ISSUE TITLE
configuration to deliver Talos system logs to some destination

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#4225]
## Feature Request

Could be one of the common protocols, we can start with some common denominator, e.g. Syslog protocol.

### Description

One can set up listener via Filebeat, FluentD or anything like that and deliver logs to the final destination (e.g. ELK).

**Comment by Ulexus** [comment]
FWIW, an ancient tool I build to ship stderr logs from an app to logstash (ELK):  https://github.com/CyCoreSystems/logshipper

**Comment by Ulexus** [comment]
Hah, never mind.  That just hands the problem off to `log15`!

**Comment by sergelogvinov** [comment]
as an option, create a syslog socket in /var/... directory
and log-delivery-pod can open/receive the logs

https://docs.fluentbit.io/manual/pipeline/inputs/syslog
```ini
[SERVICE]
    Flush               1
    Log_Level           info
    Parsers_File        parsers.conf

[INPUT]
    Name                syslog
    Path                /var/lib/syslog
    Buffer_Chunk_Size   32000
    Buffer_Max_Size     64000
```

**Comment by Ulexus** [comment]
That's actually a really good, simple and flexible idea, @sergelogvinov

**Comment by Ulexus** [comment]
The main problem is that we want to be able to collect logs _early_ before any Pods have been started, so while that works well for a "normal" case, it isn't so useful before Kubernetes is started.

**Comment by Ulexus** [comment]
I think we can _also_ do that, though.  It's simple and flexible to just

```go
select {
  case logPipe<-msg:
  default:
}
```

**Comment by Ulexus** [comment]
It should probably be in `/run/talos/log` or `/var/run/sidero/log`  (not `/var/lib` being the point)

**Comment by smira** [comment]
I don't think any host path is a good option to be honest.

**Comment by sergelogvinov** [comment]
> I don't think any host path is a good option to be honest.

fluent-bit and other solutions mount the host-path /var/log/containers/ to the container

**Comment by smira** [comment]
I really want to get rid of hostPath mounts, as they are security issue, so I would rather not rely on them

**Comment by smira** [comment]
machine config:

```yaml
machine:
   log:
     destinations:
       - transport: json
         url: tcp://some.destination:5432/
```

first destination transport: JSON over TCP, structured, logs are buffered in the ring buffer in memory (as it is today) to handle network outages, initial network configuration on boot

we can also send kernel logs to the same destination

fields (need more research):

* `service`
* `hostname`
* `nodeId`
* standard: `msg`, `lvl`, `ts`

**Comment by Ulexus** [comment]
nit:  `transport` should be something like `tcp`, `udp`...; `encoding` for `format` would be `json` (or more commonly perhaps `json_lines`

**Comment by koushickp** [comment]
@smira @sergelogvinov any idea how to read container logs from TalOS?

We are trying to use fluentd to read the container/pod logs 
In TalOS /var/log/containers path does not exist

**Comment by sergelogvinov** [comment]
Yep, all works fine in Talos v0.13.x

Part on the fluent bit config:
```ini
    [INPUT]
      Name          tail
      Alias         kubernetes
      Path          /var/log/containers/*.log
      # Db            /var/lib/fluentd/containers.db
      # DB.Sync       Off
      Parser        containerd
      Tag           kubernetes.*

      Skip_Long_Lines   On
      Mem_Buf_Limit     5MB
      Buffer_Chunk_Size 128k
      Buffer_Max_Size   512k
```

**Comment by smira** [comment]
@AlekSi what is left on this issue? tests? can we drive it to completion?
