### ISSUE TITLE
Persist kubeadm logs

### ISSUE THREAD

**Issue by rsmitty** [talos-systems/talos#423]
As it stands now, once the kubeadm container dies, there is no way to get the logs so you can troubleshoot what happened. Would love to figure out a way to persist those logs or somehow make them available to the ./osctl logs command after the fact.

**Comment by smira** [comment]
`docker cp master-1:/var/log/kubeadm.log -` works for docker-compose, but that's not universal of course...

**Comment by bradbeam** [comment]
https://github.com/talos-systems/talos/pull/663 should fix this ( definitely room for improvement )
