### ISSUE TITLE
Upgrade instance memory issue

### ISSUE THREAD

**Issue by sergelogvinov** [talos-systems/talos#4274]
Here Talos downloads the image and just run it.
constants.SystemContainerdAddress - uses memory disk to store images.

https://github.com/talos-systems/talos/blob/d9eb18bfddf69a61712d930b53aec489a806394a/internal/app/machined/internal/server/v1alpha1/v1alpha1_server.go#L1295-L1305

Node has running pods inside in this time. Talos did not drain node yet, so in this case we have OOM killer or another problems...

I think Talos needs to try CRIContainerdAddress first, if it is not working well, fallback to system...

**Comment by sergelogvinov** [comment]
+ System Container does not have Mirror/Registry config too... 
It can be affect the test.

**Comment by smira** [comment]
system containerd doesn't need mirror/registry config, as image pull is handled by Talos itself, so it uses proper configuration always

as for the tmpfs concerns, it's a valid point, but I'm not sure what we can do immediately now.

**Comment by sergelogvinov** [comment]
When node does not have enough memory
```
172.16.0.11: user: warning: [2021-09-28T05:36:48.463160284Z]: [talos] upgrade request received: preserve true, staged true, force false
172.16.0.11: user: warning: [2021-09-28T05:36:48.468327284Z]: [talos] validating "ghcr.io/sergelogvinov/installer:v0.13.0-alpha.1-14-gba27bc366"
172.16.0.11: user: warning: [2021-09-28T05:37:20.176891284Z]: [talos] service[apid](Running): Health check failed: dial tcp 127.0.0.1:50000: i/o timeout
172.16.0.11: user: warning: [2021-09-28T05:37:22.824258284Z]: [talos] service[kubelet](Running): Health check failed: Get "http://127.0.0.1:10248/healthz": context deadline exceeded
172.16.0.11: user: warning: [2021-09-28T05:37:23.004889284Z]: [talos] service[trustd](Running): Health check failed: dial tcp 127.0.0.1:50001: i/o timeout
172.16.0.11: user: warning: [2021-09-28T05:37:23.616056284Z]: [talos] service[containerd](Running): Health check failed: failed to dial "/system/run/containerd/containerd.sock": context deadline exceeded
172.16.0.11: user: warning: [2021-09-28T05:37:23.636440284Z]: [talos] service[apid](Running): Health check successful
```

**Comment by sergelogvinov** [comment]
https://github.com/containerd/containerd/discussions/6295

```
discard_unpacked_layers = true
```

**Comment by smira** [comment]
This doesn't apply to us directly as we're not using CRI plugin with system containerd, but definitely something to look into.

By the way, `installer` image is much smaller in 0.14: #4641
