### ISSUE TITLE
Rootless podman without privileged flag on talos/Setting max_user_namespaces

### ISSUE THREAD

**Issue by fritterhoff** [talos-systems/talos#4385]
## Feature Request

For some use cases we need a docker (compatible) api. Sysbox isn't working due to there quite strict requirements and limitations. I want to avoid the classic dind, because it requires a privileged pod, so I stumpled over an article by redhat (https://www.redhat.com/sysadmin/podman-inside-kubernetes)

Rootful Podman with and without the privileged flag set are working, but the rootless variants are not working. These crash with the follwing error:
```
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
cannot clone: No space left on device
user namespaces are not enabled in /proc/sys/user/max_user_namespaces
Error: cannot re-exec process
```

To get that working we must set the sysctl param to != 0. My first attempts setting it from an privileged container work fine and I could not detect any negative sideeffects, but setting that param from the machine config using the yaml fail.
```
    # # Used to configure the machine's sysctls.

    # # MachineSysctls usage example.
    sysctls:
          user.max_user_namespaces: 15000
    #     kernel.domainname: talos.dev
    #     net.ipv4.ip_forward: "0"
```

### Description

It would be great if setting the max_user_namespaces param works as setting other params. Propably the error gets cause here?
https://github.com/talos-systems/talos/blob/423861cf9f99eaf034a4f0cb243d73d1275c3f38/pkg/kernel/kspp/kspp.go#L68-L71

**Comment by fritterhoff** [comment]
Yep. That's why im searching for an workaround/alternative solution which provides comparable features with less permissions...

**Comment by fritterhoff** [comment]
Changing that param would allow us to use rootless podman without any further privileges or capabilities so I think that would be the best solution...

**Comment by fritterhoff** [comment]
Hi :) Any update on this issue? Can you estimate a release date for a new version?

**Comment by smira** [comment]
If it makes into 0.14, it should be around Dec 21st

**Comment by sanmai-NL** [comment]
See also: https://github.com/containers/podman/blob/main/rootless.md

**Comment by sanmai-NL** [comment]
See also: https://rootlesscontaine.rs/

**Comment by sanmai-NL** [comment]
@smira I’m looking to understand why `--privileged` is needed, and why `seccomp=unconfined`. I’m trying to reduce and  then document the required parameters of the security model and the frameworks in place.

**Comment by sanmai-NL** [comment]
@fritterhoff Ad https://github.com/siderolabs/talos/issues/4385#issuecomment-2058812039: containerized Talos Linux started working for me too after I switched the container runtime from runc to crun, even with cgroups v1. I had to create this configuration file:

```console
$ cat /etc/containers/containers.conf
[engine]
runtime = "crun"
```

**Comment by fritterhoff** [comment]
Uff. I'm not longer using talos so I can't provide any further input.
