### ISSUE TITLE
Booting with talos.config=metal-iso is not working

### ISSUE THREAD

**Issue by U1F984** [talos-systems/talos#4459]
### Description

I am trying to install a machine which is unable to connect to the network without prior static configuration. To install talos normally is not possible since it requires a network connection, so using `talos.config=metal-iso` was recommended to me.

I created a vfat image with the following commands:

```
# truncate -s 16M /tmp/metal-iso.img
# mkfs.vfat -n 'metal-iso' /tmp/metal-iso.img
mkfs.fat 4.1 (2017-01-24)
mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
# mount /tmp/metal-iso.img /mnt
(reverse-i-search)`dev': cd score-^Cv/
(failed reverse-i-search)`nc ': tru^Cate -s 16M /tmp/metal-iso.img
# cp ./controlplane.yaml /mnt/config.yaml
# umount /mnt
```

I also tried using the `mkisofs` command from [qemu.sh](https://github.com/talos-systems/talos/blob/master/hack/test/qemu/qemu.sh).

In both cases, the machine refused to read the configuration:

```
[talos] error running phase 5 in initialize sequence: task 1/1 failed, failed to find metal-iso iso: file does not exist
```

### Environment

- Talos version: v0.11.5
- Kubernetes version: N/A
- Platform: bare metal HP server accessible via iLO

**Comment by smira** [comment]
I verified that Talos correctly mounts the ISO and uses the config from it. 

Here is a simple example (it's not a good way to run Talos this way in QEMU, but it verifies that it works correctly):

```bash
$ talosctl gen config ....
$ mkdir iso/
$ cp controlplane.yaml iso/config.yaml
$ mkisofs -joliet -rock -volid 'metal-iso' -output config.iso iso/
$ sudo -E qemu-system-x86_64 -m 3072 -smp cpus=2 -cpu max -nographic -no-reboot -drive format=raw,if=virtio,file=/home/smira/.talos/clusters/disk.raw -machine q35,accel=kvm -kernel _out/vmlinuz-amd64 -initrd _out/initramfs-amd64.xz -append "init_on_alloc=1 slab_nomerge pti=on consoleblank=0 nvme_core.io_timeout=4294967295 random.trust_cpu=on printk.devkmsg=on ima_template=ima-ng ima_appraise=fix ima_hash=sha512 console=ttyS0 reboot=k panic=1 talos.shutdown=halt talos.platform=metal talos.config=metal-iso" -cdrom config.iso
```
