### ISSUE TITLE
documentation typo: "Enquinix" for "Equinix"

### ISSUE THREAD

**Issue by vielmetti** [talos-systems/talos#4488]
## Bug Report

Typos in "Equinix" (as "Enquinix") 

### Description

Search for https://github.com/talos-systems/talos/search?q=enquinix and see several
places in the docs where the brand name is misspelled.

**Comment by rsmitty** [comment]
lol, nothing like copy/pasting that same typo all over the place :smile: 

Thanks for the heads up, we'll get this fixed.

**Comment by vielmetti** [comment]
At least it's consistent and easy to fix!
