### ISSUE TITLE
Show disk names in maintainence mode

### ISSUE THREAD

**Issue by danielr1996** [talos-systems/talos#4507]
I tried installing Talos with the default generated config but it failed with the following error
```
error applying new configuration: rpc error: code = Unknown desc = configuration validation failed: 1 error occurred:
        * specified install disk does not exist: "/dev/sda"
```

After booting a standard ubuntu image and running `lsblk` I noticed that my disk was named `/dev/xvda` (it's running inside xpc-ng, therefore a virtual disk). 

However it's quite unhandy to boot up a new vm just to see the disk name. Therefore it would be nice to see the available disk in maintance mode like I can already with the ip.

Other solutions to that problem I can image but are more complex are:
1. implement something like `talosctl list-disk --nodes 10.0.0.10` for scenarios where no console log is available
2. make disk selection completely automatic by default and just pick the first disk found.

**Comment by rsmitty** [comment]
Hey @danielr1996, thx for dropping by. This should actually already work for you. Here's the command I issued from a booted ISO (drops into maintenance mode by default):

```bash
$ talosctl -e 192.168.1.38 -n 192.168.1.38 disks --insecure
DEV        MODEL           SERIAL   TYPE   UUID   WWID   MODALIAS      NAME   SIZE
/dev/sda   VBOX HARDDISK   -        HDD    -      -      scsi:t-0x00   -      8.6 GB
```

I do think, however, that we have some weirdness with the order of flags for that command in particular. But let me know if you're seeing something different.

**Comment by danielr1996** [comment]
Hey @rsmitty thanks for the fast reply. This indeed solves my problem, therefore I'm closing my issue. What do think about adding this to the instructions? I think most people are running talos in a VM/Cloud environment instead of real bare metal, so I assume it's fairly common for people to have /dev/vda or /dev/xvda disks instead of /dev/sda.

**Comment by rsmitty** [comment]
Yep, adding it to the docs is a great idea. Will take a note of that.
