### ISSUE TITLE
updating manifests for externalCloudProvider  has no effect

### ISSUE THREAD

**Issue by frezbo** [talos-systems/talos#4542]
## Bug Report

Updated the manifests for `externalCloudProvider` tried updating the machine config via `--immediate` and also tried a reboot. The cluster still picks up the old manifests.

**Comment by smira** [comment]
Talos never deletes or updates existing bootstrap resources (for safety reasons), it only creates missing resources.

@Unix4ever recently added a feature to `talosctl upgrade-k8s` to update bootstrap manifests. You can try with upgrade to same version to make it re-apply bootstrap manifests.
