### ISSUE TITLE
Cannot apply config due to utf-8 encoding

### ISSUE THREAD

**Issue by Rusiecki** [talos-systems/talos#4575]
### Description
- installed succesfully on pine64 with MacOSX
- when using the command `talosctl apply-config --insecure --interactive --nodes 192.168.178.128`
- I recieve a `rpc error: code = Internal desc = grpc: failed to unmarshal the received message string field contains invalid UTF-8`

### Environment

- Talos version: 0.14
- Kubernetes version: Client Version: v1.20.1
- Platform: OSX Big Sur 11.6

**Comment by smira** [comment]
Does it in fact contain invalid UTF-8?

**Comment by Rusiecki** [comment]
@smira How can verify that it is not?

**Comment by Rusiecki** [comment]
I could solve the problem on a different machine. Thanks
