### ISSUE TITLE
Support setting hostnames without DHCP option-12

### ISSUE THREAD

**Issue by TimJones** [talos-systems/talos#458]
In DHCP environments where the server either expects a request to have a hostname already, or does not supply one in the reply we still need a way of setting the hostname.

Options:
1. **Add kernel param:** Something like `talos.autonomy.io/hostname` which will be used to set option 12 in the first DHCP request. Possible issue: which takes preference between kernel param and DHCP reply option-12 if they do not match.
2. **Add hostname to user-data:** Something like `UserData.Networking.OS.Hostname` which will be used if not set in DHCP reply, also trigger a second DHCP request with option-12 set. Possible issue: should always be used even if it doesn't match what is already set?

**Comment by bradbeam** [comment]
Seems like they both have the same issue with regards to being used with a DHCP server that supports defining a hostname. I'd argue that if a DHCP server supports setting a hostname and responds with one, we should always honor that ( try to enforce conformity ) and only use the kernel param / userdata options as a fallback.

**Comment by andrewrynhard** [comment]
I’m torn on using the user supplied Hostname as a fallback :/. It feels to me like something a power user would want control over. But I could also appreciate that we conform to the DHCP server. I need to look into how other distros might be doing it. But I think the suggested way is fine. We could always change it if it becomes a problem.

**Comment by andrewrynhard** [comment]
@TimJones We discussed this a bit. I think we decided to just go with the kernel param route. If you don't have time then feel free to close this and one of us can start a new PR. Thanks!

**Comment by TimJones** [comment]
Not a problem, in fact it simplifies the logic a bit more. Though with it being a kernel parameter I would err on using it as the definitive name i.e. use it even if the DHCP server returns something different in option-12. Thoughts @andrewrynhard @bradbeam??

**Comment by TimJones** [comment]
Not a problem, in fact it simplifies the logic a bit more. Though with it being a kernel parameter I would err on using it as the definitive name i.e. use it even if the DHCP server returns something different in option-12. Thoughts @andrewrynhard @bradbeam??

**Comment by andrewrynhard** [comment]
@TimJones works for me!
