### ISSUE TITLE
Deployed on Proxmox Stuck

### ISSUE THREAD

**Issue by uhlhosting** [talos-systems/talos#4595]
## Bug Report

We tried to deploy it on Proxmox and it gets stuck after failing to pull NTP time via [::] ipv6 . In all our deployments we never had issues, since we do not have DHCPv6 enabled now this is maybe something to look into.

### Logs

<img width="1570" alt="image" src="https://user-images.githubusercontent.com/6324047/143392986-e00fc636-faed-4704-b2ce-c1f55a4720cc.png">

<img width="1555" alt="image" src="https://user-images.githubusercontent.com/6324047/143393017-35e31091-a9d9-4eb1-be19-03c32631ce34.png">

<img width="1572" alt="image" src="https://user-images.githubusercontent.com/6324047/143393048-cfeb244c-34e1-4340-aa64-8c090704bf92.png">

### Environment

- Talos version: Latest stable
- Kubernetes version: n/a
- Platform: Proxmox

**Comment by sergelogvinov** [comment]
Talos waits ```apply-config```  сcommand, because it is now in maintenance mode.

https://www.talos.dev/docs/v0.13/virtualized-platforms/proxmox/#create-control-plane-node good example of next steps.

**Comment by uhlhosting** [comment]
@sergelogvinov thanks for the tip, followed the docs there alto a bit confused with them, some cli are not working as expected:

1 cosmic@Revenger ~/.talos % talosctl kubeconfig .
error copying: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"x509: Ed25519 verification failure\" while trying to verify candidate authority certificate \"talos\")"
1 cosmic@Revenger ~/.talos % talosctl bootstrap
error executing bootstrap: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority (possibly because of \"x509: Ed25519 verification failure\" while trying to verify candidate authority certificate \"talos\")"

Any workaround this?

**Comment by sergelogvinov** [comment]
Hello, first you need to bootstrap your cluster.

```
# create a talos configs
talosctl gen config talos-proxmox-cluster https://$CONTROL_PLANE_IP:6443 --output-dir _out

# and here ```_out``` you will see ~3 files - controlplane,worker,talosctl-config
ls -la  _out

# next, send the contolplane config to the server 
talosctl apply-config --insecure --nodes $CONTROL_PLANE_IP --file _out/controlplan.yaml

# bootstrap the first node
talosctl --talosconfig _cfgs/talosconfig -n $CONTROL_PLANE_IP  bootstrap
```

If you have more questions, please join the slack https://www.talos.dev/docs/v0.13/#community

**Comment by smira** [comment]
first of all, NTP sync messages were temporary failures during network initialization, they're followed by the successful sync message, and even NTP failure is not a problem to bootstrap the node.

the error about certificate validation failure 99% of the time means that you're using wrong `talosconfig` or running it against wrong cluster. 

`talosctl gen config` generates server configs `*.yml` and client-side config `talosconfig`. `talosctl` by default uses `~/.talos/config`, but this can be overridden with `--talosconfig` flag; or you can merge `talosconfig` file into default location with `talosctl merge config talosconfig`. 

Also please keep in mind that generated `talosconfig` doesn't have endpoints and nodes set, they can be set with `talosctl config nodes|endpoints`.

I would highly recommend [walkthrough](https://www.talos.dev/docs/v0.13/introduction/getting-started/) in our docs.

**Comment by uhlhosting** [comment]
```
1 cosmic@Revenger ~/.talos % talosctl merge config talosconfig
unknown command "merge" for "talosctl"
```

Guess would be 1 cosmic@Revenger ~/.talos % talosctl config merge talosconfig

**Comment by uhlhosting** [comment]
Not sure what happened yet not it seems my configs have been mixed somehow no nodes are accepted

`cosmic@Revenger ~ % !394                   
talosctl dashboard -d 5s
error constructing client: failed to determine endpoints
1 cosmic@Revenger ~ % talosctl dashboard -d 5s  `

**Comment by smira** [comment]
This is covered in the documentation: https://www.talos.dev/docs/v0.13/introduction/getting-started/#configure-your-talosctl-client
