### ISSUE TITLE
Drain the node on shutdown event.

### ISSUE THREAD

**Issue by sergelogvinov** [talos-systems/talos#4618]
## Feature Request

Better to make drain node (Kubernetes method) on shutdown event. 
Currently Talos just kills(stop) all pods...

For example you have spot instance, and cloud provider trying to stop the node.
Talos will drain node, and all pods gracefully migrate to another instance.

**Comment by andrewrynhard** [comment]
The hardest part here is that the individual nodes don't have the auth to drain themselves IIRC. 🤔  We could issue this from the "cluster level" (control plane nodes know that this is the RPC and the target node).

**Comment by smira** [comment]
I think we already drain on reset, but not on shutdown. I don't remember about worker nodes though

**Comment by smira** [comment]
`talosctl shutdown --grace-period=90s` (wait 90s to drain the node, set to `0s` to skip draining)

Note: make sure `shutdown` sequence on failure should `shutdown` anyways (not `reboot`).

Accepted as a feature proposal.
