### ISSUE TITLE
Increase adoption timeout

### ISSUE THREAD

**Issue by p3lim** [talos-systems/talos#4626]
### Description

It's really a mix of a feature request and a bug report.

When we boot control plane nodes they end up in a state where they wait to be bootstrapped, which has a timeout, and then reboots.

This timeout period needs to be drastically increased! I'd be happy with a few hours/day(s).

Out problem right now is that we boot a number of nodes, which never finish at the same time (the difference has a tendency to be more than that timeout period), we have maybe 2 out of 3 nodes ready while the 3rd lags behind. By the time the 3rd is ready one or both of the first nodes will timeout and reboot, meaning the cluster can't be bootstrapped until they're all there.

I know that control plane nodes can join the cluster after the fact, it's more of a convenience thing.

**Comment by smira** [comment]
@p3lim can you please be more specific with details. I think timeout on booting up is around 10 minutes. Once the bootstrap API is called, that node should bootstrap even if it is rebooted (it will keep bootstrapping anyways). Other nodes should join even if they reboot.

I agree the timeout might be bumped, but it sounds like there's something else going on.

**Comment by p3lim** [comment]
We've got enterprise hardware that has a tendency to spend up to 5 minutes just in POST due to a stupid amount of hardware that needs to be checked before it can boot, and we're on a corporate network behind proxies which makes downloads slower than ideal.

So if a node fails (for whatever reason) to install it can easily take 10-15+ minutes for it to become ready, and it has a tendency to become ready _just_ as the other nodes are timing out.

**Comment by smira** [comment]
Thanks, this makes sense. I think we could bump both timeouts to join etcd and overall boot timeout.
