### ISSUE TITLE
pause the boot process on some failures instead of rebooting

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#4669]
## Feature Request

Talos aborts the boot and issues a reboot sequence on any failure in the boot sequence. 

Some failures are related to machine configuration issues or hardware failures, they can't be fixed with a reboot, so node goes into a reboot loop.

One example is a failure to mount user disks (e.g. #4594)

### Description

Instead of immediate reboot, Talos should pause the boot on failures which can be remediated with the machine configuration change.

`apid` should be brought up, if `apid` is not up yet, Talos should still reboot.

There might be a timeout (similar to `BootTimeout`) to issue automatic reboot if no other action was taken.

**Comment by SixFive7** [comment]
Would it be possible to classify setting `cluster.network.cni=none` to a case where a reboot is not required?
This would make method 3 of installing Cilium [Deploying Cilium CNI - Method 3: Helm manifests hosted install](https://github.com/talos-systems/talos/blob/f40b480bddcfcd1109a7455d19d77c5488500a11/website/content/docs/v0.14/Guides/deploying-cilium.md#method-3-helm-manifests-hosted-install) more friendly to new users that need more than 10 min. to see what is happening on their fresh Talos cluster.
