### ISSUE TITLE
Sponsored: descriptive boot names

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#4725]
### Description

When rebooting to a previous version of talos, it would be nice to have a description of what version of talos is laying on that partition.
Instead of partition A or B, having a "Talos version  v0.14.0-beta.1 - bc8983b9 - installed on 12/21/21 - 18:08" would be  nice to figure out which is which

**Comment by andrewrynhard** [comment]
output example:

```
Booting A (Talos v0.14.0)
```

**Comment by andrewrynhard** [comment]
Update grub config with the Talos version and everything else should "just work" TM.

**Comment by sbskas** [comment]
This is ok with us for this.
Also, version information should include the sha signature like in the talosctl version output.
