### ISSUE TITLE
Cilium Documentation Generates Clusters Without a CNI

### ISSUE THREAD

**Issue by ewohltman** [talos-systems/talos#4756]
### Description
The documentation provided at https://www.talos.dev/docs/v0.14/guides/deploying-cilium/ includes instructions for creating a cluster without a CNI, followed by installing Cilium. In testing however, it was found that a cluster cannot be initially created without a CNI.

### Logs
Following the instructions for `talos gen config`, followed by `talos cluster create` results in a timeout from `context deadline exceeded` because networking cannot work without a CNI.

### Environment
All new clusters built using the instructions.

- Talos version: `v0.14.0`
- Kubernetes version: `v1.23.1`
- Platform: `All`

**Comment by SixFive7** [comment]
The new documentation describes why the `context deadline exceeded` happens and how to correctly install Cilium without installing another CNI first.

**Comment by frezbo** [comment]
Thanks for fixes :+1:
