### ISSUE TITLE
Configure bonding through talos cmdline

### ISSUE THREAD

**Issue by sbskas** [talos-systems/talos#4765]
## Feature Request
LACP configuration for machine in maintenance mode.

### Description
Talos provides a bond configuration in the machineconfig.
We encountered a case where the switchs ports are suspended if the machine doesn't setup a LACP bond.
This prevents talos to get network configuration and go to maintenance mode at boot time.
Redhat provides some extra configuration on the cmdline 'bond=xxx' to configure the bonding at boot time.
It would be nice to be able to setup the network at boot time through a config switch i.e.:
`linux ... bond=bond0:eth0,eth1:bonding_options`
or if you want to prefix it with talos:
`linux ... talos.experimentatl.bond=bond0:eth0,eth1:bonding_options`

**Comment by smira** [comment]
`talos.network.interface.<bond0>={JSON dump of the v1alpha1 Device machine config structure (no spaces)}`

* we keep using same machine config format, so it's easy to parse
* relatively easy to write and keep in sync with machine config: `yq  -o json .machine.network.interfaces[].bond0`


Questions:

* what are we going to do when we switch to multi-doc YAML?
* can kernel parse it correctly? (no spaces at the very least in the value)
