### ISSUE TITLE
Documentation: Invalid download link vmware cp.patch

### ISSUE THREAD

**Issue by ShaharNaveh** [talos-systems/talos#4793]
### Description

At the section of [Generating Base Configurations](https://www.talos.dev/docs/v0.14/virtualized-platforms/vmware/#generating-base-configurations) for the vmware installation guide for versions `v0.14` and `v0.15`, there's a link for a ```cp.patch``` file, but the current link is dead (getting 404).

![talos_cp_patch_not_found_v14](https://user-images.githubusercontent.com/50263213/149503634-8330359e-95c7-4da6-b1e4-683ead3b7416.png)

![talos_cp_patch_not_found_v15](https://user-images.githubusercontent.com/50263213/149503658-be424547-64d8-4516-a3b6-8f16bdb5e381.png)

**Comment by rsmitty** [comment]
Fixed by #4794
