### ISSUE TITLE
Probably incorrect error variable added to the multierror.

### ISSUE THREAD

**Issue by DmitriyMV** [talos-systems/talos#4834]
### Description

[Here](https://github.com/talos-systems/talos/blob/b1e61fa5b1bcd5affd42b498711b9e3378344c33/internal/app/machined/pkg/controllers/runtime/kernel_param_spec.go#L115) you probably wanted to add `e` instead of an `err` into the multierror.

**Comment by Unix4ever** [comment]
Yeah, that's an error! Thanks for the report.
