### ISSUE TITLE
compaction of etcd not possible. etcdserver: mvcc: database space exceeded

### ISSUE THREAD

**Issue by cmdcelp** [talos-systems/talos#4888]
### Description
The error appeared while upgrading a pod. A reboot of the controlplane nodes did not help, but rendered the cluster unusable. I dont know if auto compaction is enabled on the etcd cluster, alternatively a hint on how to access the etcd cluster with etdctl woult be great.

General diskspace is fine. `talosctl usage' gave me 9GB of used disk with a raw image size of 25GB.

### Logs
```
10.1.16.89: user: warning: [2022-01-27T14:31:25.392352282Z]: [talos] controller failed {"component": "controller-runtime", "controller": "k8s.ManifestApplyController", "error": "error creating etcd session: etcdserver: mvcc: database space exceeded"}
```
### Environment
- Talos version:
Client:
	Tag:         v0.14.0
	SHA:         675dee0e73bb4b866d2a07b9b2f0a54fb7f3b575
	Built:
	Go version:  go1.17.5
	OS/Arch:     linux/amd64
Server:
	NODE:        10.1.16.89
	Tag:         v0.14.0
	SHA:         675dee0e
	Built:
	Go version:  go1.17.5
	OS/Arch:     linux/amd64
	Enabled:     RBAC

- Kubernetes version:
Client Version: v1.23.2
Server Version: v1.23.1

- Platform: QEMU VMs of Talos installed in bare metal fashion.

**Comment by smira** [comment]
I think the most important metric might be 

```
talosctl du -H /var/lib/etcd
```

**Comment by smira** [comment]
we need to certainly look into the `etcd` settings and provide a way to run compaction/defragmentation automatically, but one workaround is:

> you can grab the required PKI to setup `etcdctl` up by running `talosctl cp -r /etcd/kubernetes/pki/etcd ./etcd` against a control plane node.

**Comment by smira** [comment]
As API server should perform compaction automatically, my only guess is that you might need to do `etcdctl defrag`

**Comment by cmdcelp** [comment]
thanks for the direction. i searched /etc[sic!]/kubernetes/pki/etcd without success, but found /system/secrets/etcd.

**Comment by smira** [comment]
> thanks for the direction. i searched /etc[sic!]/kubernetes/pki/etcd without success, but found /system/secrets/etcd.

sorry, yep, we changed that in recent versions of Talos :facepalm:

**Comment by smira** [comment]
> * talosctl du -H /var/lib/etcd
>   NODE         SIZE     NAME
>   10.1.16.89   47 MB    member/snap
>   10.1.16.89   384 MB   member/wal
>   10.1.16.89   431 MB   member
>   10.1.16.89   431 MB   .

That's interesting, it's well under 2GiB limit. I wonder if that's the alarm in etcd which needs to be cleared.

But we definitely need to improve Talos tooling to manage that kind of etcd issues.

**Comment by cmdcelp** [comment]
```
export ETCDCTL_ENDPOINTS="10.1.16.88:2379"
export ETCDCTL_INSECURE_SKIP_TLS_VERIFY="true"
export ETCDCTL_KEY=$(pwd)/etcd/admin.key
export ETCDCTL_CERT=$(pwd)/etcd/admin.crt

etcdctl compaction $(etcdctl endpoint status --write-out="json" | egrep -o '"revision":[0-9]*' | egrep -o '[0-9].*')
# actually for every etcd member:
etcdctl defrag
etcdctl alarm disarm
```
and everything works like a charm!

**Comment by rust84** [comment]
Worth noting that the cert path has been changed to /system/secrets/etcd when running the commands above.
