### ISSUE TITLE
Upgrade kubernetes with Talos

### ISSUE THREAD

**Issue by mr-sab** [talos-systems/talos#4906]
## Bug Report
Talosctl not reading kubernetes version correctly

### Description
When trying to upgrade kubernetes to a newer level on my cluster it fails because there is no upgrade patch available.
```bash
talosctl -n 192.168.40.167 upgrade-k8s --to=1.23.3
automatically detected the lowest Kubernetes version 1.20.5
unsupported upgrade path "1.20->1.23" (from "1.20.5" to "1.23.3")
```
The information seems not to be red correctly for the cluster, because:

```bash
kubectl version --short
Client Version: v1.23.3
Server Version: v1.23.1
```

```bash
kubectl get nodes -o wide
NAME                   STATUS   ROLES                  AGE    VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE          KERNEL-VERSION   CONTAINER-RUNTIME
talos-192-168-40-165   Ready    control-plane,master   303d   v1.23.1   192.168.40.165   <none>        Talos (v0.14.1)   5.15.16-talos    containerd://1.5.8
talos-192-168-40-166   Ready    control-plane,master   157d   v1.23.1   192.168.40.166   <none>        Talos (v0.14.1)   5.15.16-talos    containerd://1.5.8
talos-192-168-40-167   Ready    control-plane,master   303d   v1.23.1   192.168.40.167   <none>        Talos (v0.14.1)   5.15.16-talos    containerd://1.5.8
````

If you need more information feel free to let me know or if can help you in a other way
Thanks for the great work :)

EDIT: cluster was installed talos version 0.12.0 and upgrade later.

**Comment by rsmitty** [comment]
@mr-sab I think this may simply be because you can only bump two versions at a time (from what I'm seeing in our code). So try going from `1.20 -> 1.22.x`, then from `1.22.x -> 1.23.3`

**Comment by mr-sab** [comment]
My talosctl is version 0.14.1

```bash
Client:
        Tag:         v0.14.1
        SHA:         7182bcf2
        Built:
        Go version:  go1.17.5
        OS/Arch:     linux/amd64
```

**Comment by smira** [comment]
@mr-sab `kubectl get nodes` only shows `kubelet` version, not the API server version

I guess you might have API server or other control plane components of the old version.

You can check that by checking respective pods definition.

**Comment by mr-sab** [comment]
API is also using the 1.23.1 image:
'''bash
kubectl get pods -n kube-system -o jsonpath="{.items[*].spec.containers[*].image}" | tr -s '[[:space:]]' '\n' | grep api
k8s.gcr.io/kube-apiserver:v1.23.1
k8s.gcr.io/kube-apiserver:v1.23.1
k8s.gcr.io/kube-apiserver:v1.23.1
'''

The kubeproxy is using 1.20.5, so I thing that is the problem?
Is this normal behavior that all components are upgraded except the proxy?
Can I without destroying or breaking my cluster, upgrade the kube proxy to the new as level?
Thanks!

'''bash
k get pods -n kube-system -o jsonpath="{.items[*].spec.containers[*].image}" | tr -s '[[:space:]]' '\n' | grep kube
k8s.gcr.io/kube-apiserver:v1.23.1
k8s.gcr.io/kube-apiserver:v1.23.1
k8s.gcr.io/kube-apiserver:v1.23.1
k8s.gcr.io/kube-controller-manager:v1.23.1
k8s.gcr.io/kube-controller-manager:v1.23.1
k8s.gcr.io/kube-controller-manager:v1.23.1
k8s.gcr.io/kube-proxy:v1.20.5
k8s.gcr.io/kube-proxy:v1.20.5
k8s.gcr.io/kube-proxy:v1.20.5
k8s.gcr.io/kube-scheduler:v1.23.1
k8s.gcr.io/kube-scheduler:v1.23.1
k8s.gcr.io/kube-scheduler:v1.23.1
'''

**Comment by smira** [comment]
`talosctl upgrade-k8s` should take care of upgrading `kube-proxy` as well, but right now it fails the pre-checks. So you can try upgrading it manually by simply updating the daemonset. But in general `talosctl upgrade-k8s` should take care of all of that.

**Comment by mr-sab** [comment]
Nice, After changing the kube-proxy to 1.23.1 and running talosctl upgrade-k8s again everything was updated and working fine.
Thanks alot 👍 

I will close the issue.
