### ISSUE TITLE
set streamingConnectionIdleTimeout to non-zero

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#4990]
## Feature Request

Is there any reason streamingConnectionIdleTimeout is set to 0s in /etc/kubernetes/bootstrap-kubeconfig by default?

Got some resources:

* https://docs.datadoghq.com/security_platform/default_rules/cis-kubernetes-1.5.1-4.2.5/
* https://rancher.com/docs/rancher/v2.0-v2.4/en/security/rancher-2.2/hardening-2.2/
* https://gsl.dome9.com/D9.K8S.NET.03.html

Suggesting it might be better to have long timeout to prevent denial of service issues or running out of ephemeral ports over time if something is consuming but not closing streams.

**Comment by Ulexus** [comment]
STIGs recommend 5m, FWIW
