### ISSUE TITLE
kube-apiserver audit log changes

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#5000]
## Feature Request

There are few recommended settings for the kube-apiserver's audit log settings which we
should consider:
 - `audit-log-maxsize = 100` (currently `50`)
 - `audit-log-maxbackup = 10` (currently `3`)
 - `audit-log-maxage = 10` (number of days' worth of log files to keep before deleting)

Additionally, a common requirement for audit logs is that they be stored to
file.  Presently, they are sent to stdout, which works well for tying into an
external logging system, but does not meet all logging requirements.
Ideally, we should be storing the audit logs to non-volatile local storage in a
way which:
 - does not lend itself to mounting from arbitrary Kubernetes workloads
 - does not present a risk of denial of service due to disk overflow

`audit-log-path = <something>` (pointing to a real directory; currently, this is `stdout`)

I view this latter as being a much less universal option which should probably _not_ be enabled by default.  Perhaps, in fact, this is best left up to a machine config patch to the apiserver.

### Description

These items address STIG vulnerabilities:
 - v-242465
 - v-242462

**Comment by smira** [comment]
Arguably, `stdout` still goes to `/var/log/containers` so there's not much lost if we send audit log to a file.

And same way log collectors _have_ to pick it up from the filesystem today, separate location doesn't sound too crazy.

I would prefer to see actual API server logs on `stdout` vs. the audit log which is somewhat useless for debugging.

As `kube-apiserver` can rotate the audit log on its own, I vote for separate filesystem location for it.

**Comment by frezbo** [comment]
It's preferable to have the log's sent to a separate file and also logged to an external system so that the audit logs are not lost upon a node being lost/rebooted/power cycled

**Comment by Ulexus** [comment]
Good points on the separation of apiserver logs from apiserver _audit_ logs, which point more toward setting the log path by default after all.

**Comment by Ulexus** [comment]
So presuming we _do_ have a separate apiserver audit log directory, _where_ should that be?  Do we have persistent, writable directory trees which arbitrary Pods cannot mount (but that static pods like the apiserver _can_)?

**Comment by smira** [comment]
I don't think that is technically achievable, I would rather in general limit hostPath mounts via PSS `baseline`.

It might be `/var/log/audit` for KISS.
