### ISSUE TITLE
talosctl apply-config says: failed to read configuration from "_out/init.yaml": open _out/init.yaml: no such file or directory

### ISSUE THREAD

**Issue by davidthewatson** [talos-systems/talos#5042]
## Bug Report

I was following the instructions here:

https://www.talos.dev/docs/v0.7/virtualized-platforms/proxmox/#create-control-plane-node

And expected each command to take inputs as described and produce outputs as described. But the `gen config` command didn't produce the `init.yaml` that `apply-config` expects.

### Description

When I got between `talosctl gen config` and `talosctl apply-config` I saw that the gen command didn't produce the expected output in `_out/init.yaml` such that when I issued the following `talosctl apply-config` the last command failed to read configuration from `_out/init.yaml` since the file wasn't output from the gen config.

Is there a workaround that I could try?

I noted that the command inputs to talosctl seemed inconsistent with respect to `gen config` parameters and `apply-config` parameters. Why not use the same style for `gen config` and `apply-config`?
### Logs
```
 λ talosctl gen config talos-proxmox-cluster https://$CONTROL_PLANE_IP:6443 --output-dir _out

generating PKI and tokens
created _out/controlplane.yaml
created _out/worker.yaml
created _out/talosconfig
```
```
 λ talosctl apply-config --insecure --nodes $CONTROL_PLANE_IP --file _out/init.yaml

failed to read configuration from "_out/init.yaml": open _out/init.yaml: no such file or directory
```
### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
[🔴] × talosctl version
Client:
        Tag:         v0.15.0-alpha.2
        SHA:         f1a93d28
        Built:
        Go version:  go1.17.7
        OS/Arch:     linux/amd64
Server:
error constructing client: failed to determine endpoints

- Platform:
Host: Proxmox VE 7.1-2
Guest: https://github.com/talos-systems/talos/releases/download/v0.15.0-alpha.2/talos-amd64.iso

**Comment by frezbo** [comment]
@davidthewatson please follow the latest docs here https://www.talos.dev/docs/v0.15/virtualized-platforms/proxmox/#generate-machine-configurations

The `init.yaml` has been deprecated for a while

**Comment by davidthewatson** [comment]
Makes sense. I'd suggest that it would be easier for potential users of Talos to redirect from the 0.7 version to the current version with a permanently moved HTTP response or similar since google has the result for "proxmox talos" at:

https://www.talos.dev/docs/v0.7/virtualized-platforms/proxmox/

Why leave the deprecated content if it's actually deprecated? Either that, or have the google search redirect to current and just symlink the current to 0.15 or whatever.

**Comment by Ulexus** [comment]
We need to leave old version up for people who are still running the old versions.  However, it _is_ certainly a problem that Google fixates on old versions, and the more people click on those old versions, the worse the problem becomes.

We have been discussing resolutions to this, including (among others):
 - showing a banner when viewing out-dated documentation
 - checking the Referrer, and if it is a search engine, proactively redirect to current documentation

Neither of these are _great_ solutions, and the second in particular is rather invasive, but just doing a permanent redirect is not undesirable, as well.

**Comment by steverfrancis** [comment]
The better solution is to just tell Google (et al) which are the canonical pages.
https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls
