### ISSUE TITLE
Refine `osctl top`

### ISSUE THREAD

**Issue by bradbeam** [talos-systems/talos#567]
There are a number of improvements we can make to `osctl top` 

- ~~flag to set the sort by field ( cpu/rss seem to be the two big ones that stand out )~~
- ~~flag to allow for one time execution/print out ( skip the gui )~~
- limit the responses to X
- change failures in proc to continues/review this section
- review proteus implementation to help with message <-> struct parity.
- ~~get proper term dimensions~~
- ~~switch to tab output writer(?) or something else to make the columns better aligned~~

**Comment by bradbeam** [comment]
partially resolved in #568

**Comment by andrewrynhard** [comment]
@bradbeam I'm gonna take this off a milestone and put it in the backlog.
