### ISSUE TITLE
Refactor containerd code into a single client package

### ISSUE THREAD

**Issue by bradbeam** [talos-systems/talos#570]
We make use of a containerd client across a number of packages. We should look at making a single containerd client package.

**Comment by andrewrynhard** [comment]
@smira With your recent work, how close would you say we are to closing this issue?

**Comment by smira** [comment]
hm, I'm not sure  what we can actually do here. We use it in containerd runner, image puller and container inspector. We create new instance of the client, but that seems fine to me. Not sure what @bradbeam meant here. We could probably single instance of the client variable, not sure if that is going to bring any benefit

**Comment by bradbeam** [comment]
I don't have much in terms of specifics, but the thought came in when dealing with some of the osd api + service interaction. 
I think you've captured a bunch of the work already in the pkgs/containers/containerd package ( not sure how much of the code is shared between the uses you mention ). The only other part I can think of is moving the containerd client connection code into that package as well. That way if we need to change the client -> containerd interaction, we can just update our package and hopefully keep it transparent to callers. 
If you don't think there's much value in doing that, I'm fine to close this since there's quite a bit that was already done.

**Comment by smira** [comment]
Feels like client code is only one-liner:

```
	i.client, err = containerd.New(constants.ContainerdAddress)
	if err != nil {
		return nil, err
	}
```

It might be overkill to encapsulate it. I will expose CRI client package though as top-level today so that we can re-use it.
