### ISSUE TITLE
Migrate golangci-lint.sh to toolchain

### ISSUE THREAD

**Issue by bradbeam** [talos-systems/talos#607]
In the current chain/order of events, this will always gets downloaded. Should save us a few seconds each build doing the download/install.

**Comment by andrewrynhard** [comment]
Just saw the PR for this in toolchain-must. I think we should keep this here (see comments in PR). One of the things we can do though is figure out how to get it in the base container in such a way that we don't have to re-download it because it is cached.

**Comment by andrewrynhard** [comment]
@bradbeam Since @smira improved our Dockerfile so that it doesn't download golangci-lint every run, I'm going to close this.
