### ISSUE TITLE
support hostnames/DNS for cluster bootstrapping

### ISSUE THREAD

**Issue by ptone** [talos-systems/talos#666]
Currently requires IP addresses, for example this error when using hostname on GCE:

```
[    5.310024] [talos] [initramfs] encountered error reading userdata: 2 errors occurred:
[    5.310024] 	* [services.trustd.endpoints[0]] "master2": invalid network address
```

**Comment by andrewrynhard** [comment]
@bradbeam looks like our verification step? I'm thinking we maybe verify that the value is a valid IP or valid DNS.
