### ISSUE TITLE
HTTPS errors pulling .yaml configs 

### ISSUE THREAD

**Issue by lrsmith** [talos-systems/talos#678]
I am hosting the YAML config files generated by osctl on a local server, secured using Let's Encrypt SSL certs. When using https, the ISO image is not able to validate the cert and fails to load the .yaml configuration. The SSL cert is obtain from 'production' Let's Encrypt, not their staging site. 

Presumably this would also be an issue with any self-signed certs.

As a work-around I disabled http->https redirect for install. But on reboots the image will try to pull from https again, if I re-enable the redirect. 

<img width="963" alt="https-error-lets-encrypt" src="https://user-images.githubusercontent.com/1671343/58207487-9d271180-7c97-11e9-948d-5c4956639732.png">

**Comment by smira** [comment]
Looks like we need to enable fetch by hostname (via DNS) to address that? (if we have some DNS config by that time), or ability to disable TLS verify?

**Comment by andrewrynhard** [comment]
🤔 I think DNS would work here actually. Being that we are security focused I'm hesitant to give an option to disable TLS verify, but on the other hand it is valuable for dev/home use cases.

**Comment by andrewrynhard** [comment]
@lrsmith Have you tried using the hostname that this cert if valid for?

**Comment by lrsmith** [comment]
I have not. I'll give that a try tonight and comment.

**Comment by lrsmith** [comment]
This works fine if the DNS name is resolvable. I think requiring a resolvable DNS name is acceptable, especially for prod. It could be a small barrier but then just use http and don't redirect, like I did. :) Closing
