### ISSUE TITLE
v0.1.0-alpha.27 : Failure to copy /etc/kubernetes/{audit-policy.yaml, encryptionconfig.yaml}

### ISSUE THREAD

**Issue by lrsmith** [talos-systems/talos#679]
I rebuilt from scratch my Talos Kubernetes cluster. The nodes came up fine, but on applying the psp.yaml and flannel.yaml I lost access to the kube-apiservers. When looking into it, kube-apiserver failed to start on the two other master nodes. Describing the pod showed errors accessing encryptionconfig.yaml.  I was able to hit the API server directly on 6443, just not 443.

I manually copied the files over to the other two images, restarted the nodes and they came up fine and I was able to hit the API server on 443 again.

Andrew helped me debug this and can provide more details.

**Comment by andrewrynhard** [comment]
Fixed in `v0.1.0-alpha.28` by #38.
