### ISSUE TITLE
test suite for osctl cli

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#691]
As osctl cli grows bigger and bigger, it probably makes sense to have a test suite for the cli.

It should execute command with some parameters and assert on command exit status/output.

Need some good framework?

Probably test should run as part of the integration test. Another idea is to launch mock osd with fixed response (I don't like it)

**Comment by andrewrynhard** [comment]
I like the idea of running it in our integration test. The trick is gonna be finding output we can depend on to be there that isn't unique to the node.

**Comment by andrewrynhard** [comment]
Do we still need this ticket?

**Comment by smira** [comment]
we have first test + some framework here https://github.com/talos-systems/talos/blob/master/internal/integration/cli/version.go

I guess we could close it or rename it, as we just need to fill in the tests

**Comment by smira** [comment]
I'm going to close this one, as we have good first chunk of CLI tests now. Of course there's huge room for improvement, but better to have it as specific tickets.
