### ISSUE TITLE
How To Install GlusterFS

### ISSUE THREAD

**Issue by cbluth** [talos-systems/talos#709]
I use glusterfs in my kubernetes clusters.
How do i install the gluster client on talos?

**Comment by bradbeam** [comment]
I don't believe you need to install it. We use hyperkube to host the kubelet which includes the glusterfs client.

**Comment by andrewrynhard** [comment]
👋 @cbluth. We currently run the `kubelet` as a container using `hyperkube`. As @bradbeam pointed out, it _should_ work:

https://github.com/kubernetes/kubernetes/blob/master/build/debian-hyperkube-base/Dockerfile#L51

**Comment by rsmitty** [comment]
Closing, since this should be working.
