### ISSUE TITLE
Routes API enhancements

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#753]
There are some important limitations in the current routes API which should probably be addressed with the v0.2.0 API:

- [ ] No support for IPv6 (routes query is IPv4-only; no facility to choose, in API)
- [ ] No route metric returned (critical to diagnosing conflicting route problems)
- [ ] No protocol returned (cannot tell how the route got in the table)
- [ ] No table ID returned (needed for systems with multiple routing tables)
- [ ] No scope returned (probably of lesser significance, but useful filter point, especially for IPv6 addresses)

After internally griping about the library that is being used, I realize that the fault is not the library, but with the kernel API itself.  Netlink is pretty painful.

Regardless, I have most of this addressed in a local branch.  I'll try to get a PR  up soon, barring any objections in scope.

**Comment by Ulexus** [comment]
The main thing here is the breaking change in the Routes API:  Routes currently takes an `empty.Empty` struct, which means we cannot add fields without breaking the API.  This is a really good reason to NOT use `empty.Empty`, even if an API does not presently support any input parameters.

**Comment by andrewrynhard** [comment]
Good point about `empty.Empty`. I think this PR sounds great.
