### ISSUE TITLE
Allow additional IP SAN entries for `osctl cluster create`

### ISSUE THREAD

**Issue by mstansberry** [talos-systems/talos#800]
Allow for user-defined IP address to be added to certificate on new cluster creation.

Use cases:
* remote `DOCKER_HOST` defined for deployment of cluster

Stretch:
* return user-defined IP as `target` when generating `kubeconfig` to allow for followup query/reuse against dockerhost

**Comment by andrewrynhard** [comment]
Nice, I was just thinking about this the other day. We should absolutely support this. 👍

**Comment by Ulexus** [comment]
Yes, both IPs and hostnames should be configurable.  Good point!

**Comment by andrewrynhard** [comment]
Would a config file makes sense here? Maybe something like:

```
docker_host: 127.0.0.1
cider_block: a.b.c.d/x
masters:
- count: 3
  hostname prefix: master-
workers: 1
- count: 1
  hostname prefix: worker-
```

**Comment by bradbeam** [comment]
I think docker host, cidr block, master count, worker count would be sufficient. The name prefix seems unnecessary given `cluster create` should just be for funsie environments.

**Comment by smira** [comment]
Go template everything! :) 

(being serious here, just have default Go template, and allow user to override it for any customization)

**Comment by mstansberry** [comment]
An option to create a default Talos config, then allow the user to update, with that being consumed during cluster create might be useful as well. Not sure how much of that is simply read from the cluster following deploy vs applied.
