### ISSUE TITLE
Talos conformance

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#865]
We currently run Kubernetes specific conformance tests, but we have zero conformance around anything Talos specific. For starters we should have a conformance test around testing/ensuring the root partition is read-only. We can add more ideas here over time.

**Comment by bradbeam** [comment]
https://github.com/cruise-automation/fwanalyzer might be interesting to look at as a framework around this.

**Comment by andrewrynhard** [comment]
Ooh looks very interesting.
