### ISSUE TITLE
NVIDIA Support

### ISSUE THREAD

**Issue by xieydd** [talos-systems/talos#868]
Is it a plan to support GPU device?

**Comment by andrewrynhard** [comment]
Hey @xieydd we would love to support this. To be honest I'm not sure what we need but I can start looking.

**Comment by xieydd** [comment]
Maybe this will give some help [minikube gpu](https://github.com/kubernetes/minikube/blob/master/docs/gpu.md)

**Comment by andrewrynhard** [comment]
Awesome I will take a look.
