### ISSUE TITLE
osctl cp treats everything as a directory

### ISSUE THREAD

**Issue by Ulexus** [talos-systems/talos#981]
May be not worth fixing, with the upcoming changes to osctl, but this results in unexpected behaviour:

```
osctl cp /etc/resolv.conf -
<binary garbage>
```

```
osctl cp /etc/resolv.conf test.conf
ls -l test.conf
total 4
-rw-r--r-- 1 scmccord scmccord 19 Aug 10 20:04 resolv.conf
```
(`test.conf` is a _directory_ containing `resolv.conf`)

**Comment by smira** [comment]
`osctl cp` produces tar archive always if the output is stdout (tar archive carries also file attributes in addition to contents)

`docker cp` does the same iirc
